### ISSUE TITLE
ettercap 24559 dconf-CRITICAL 

### ISSUE THREAD

**Issue by salwaalem** [Ettercap/ettercap#1003]
Hi, 

I have a problem with ettercap. When I want to use filter I get this error:

ettercap 24559 dconf-CRITICAL **: unable to create directory '/root/.cache/dconf':  dconf will not work properly.

Any help please ?

**Comment by koeppea** [comment]
Please provide the ettercap debug logfile which is generated in the directory where ettercap has been started when built in debug mode.
Thanks.

**Comment by koeppea** [comment]
Please also provide the source code of your filter.

**Comment by salwaalem** [comment]
Here is the debug logfile.

[etterfilter-0.8.3_debug.log](https://github.com/Ettercap/ettercap/files/4146961/etterfilter-0.8.3_debug.log)

My filter is this one (see bellow), but the critical error occurs before using this filter. exactely when I clic on load filter and go to the ettercap directory to load it

if (tcp.src == 502 && DATA.data + 11 == "\x00\x00") {

DATA.data + 11 = "\x00\x01";
msg("Data replaced");
}

I compiled with : ettercap filter.ecf -o filter.ef

Thanks in advance for your help

**Comment by koeppea** [comment]
Sorry but I didn’t mean the etterfilter debug log die but the ettercap debug log file.

**Comment by salwaalem** [comment]
Oh sorry. Here it is. In the attached file

[ettercap-0.8.3_debug.log](https://github.com/Ettercap/ettercap/files/4152946/ettercap-0.8.3_debug.log)

**Comment by koeppea** [comment]
Please try `mkdir -p /root/.cache/dconf` before you start ettercap.

**Comment by salwaalem** [comment]
Thanks Alexandre for your implication

It does not work by adding dconf dir but I re-install ettercap and now I dont have the critical error but a warning when I load my filter: 
Gtk-WARNING **: Failed to read filechooser settings from "/root/.config/gtk-2.0/gtkfilechooser.ini": Permission non accordée
Which means That I dont have the permission for this folder. But When I check I dont find gtk2.0 but gtk3.0

**Comment by salwaalem** [comment]
And the filter stay a one step whithout modifying the value (see picture please) 
![Capture](https://user-images.githubusercontent.com/40567501/74020971-f7d5da00-499a-11ea-9bc5-cdab086c56d7.PNG)

**Comment by koeppea** [comment]
Wow, we're becoming a little bit unstructured.
So the Gtk Warning can be safely ignored. This is due to the permission dropping of ettercap.
So let's close this issue for now, since it becomes quite off-topic otherwise.
Feel free to open another more specific issue for the filter thing.
