### ISSUE TITLE
Install ettercap directory in /usr/local/etc instead of /etc

### ISSUE THREAD

**Issue by Arthur111** [Ettercap/ettercap#1007]
Hello,

Is it possible to install ettercap directory in /usr/local/etc instead of /etc (/private/etc) ?

I ask that because on macOS there is more and more restriction on unix file system hierarchy and i bet soon or later they will lock /private directory like they did for /usr/bin, /usr/lib ...

Thank you

**Comment by koeppea** [comment]
Yes, use ccmake $BUILDDIR. There you can adjust all paths. Then make and make install again.
