### ISSUE TITLE
[QUERY] etterfilter : Use offset in log function ?

### ISSUE THREAD

**Issue by sladecraven** [Ettercap/ettercap#1010]
Hi all, 
I would like to use the log() function to do something like that log(DATA.data+12, "/tmp/mylog.bin"), but etterfilter returns the message : "Unknown offset DATA+12"

After a quick look into the code, it seems that the log() function is calling 'encode_offset', suggesting to me that it should work. Is it the case ? Am i doing something wrong ?

Thanks,

**Comment by koeppea** [comment]
Where have you see this 'encode_offset'?
As far as I can see, you have only the choice between DATA.data and DECODED.data.
Offsets are AFAICS not yet implemented.

**Comment by sladecraven** [comment]
encode_offset : In the C source code.
Anyway, i switched to the Lua scripts, so topic closed
