### ISSUE TITLE
Using --lua-args argument

### ISSUE THREAD

**Issue by sladecraven** [Ettercap/ettercap#1011]
I am not able to guess how the lua-ags are received in the Lua script itself
Any idea on how the get it inside the script ?

**Comment by koeppea** [comment]
Sorry but I don't have any experience with the Lua interface.

**Comment by koeppea** [comment]
@sladecraven Please try pull-request #1021.
It should fix passing `--lua-args` to the LUA script.
Check **README.LUA** how this works.

**Comment by sladecraven** [comment]
Seems to work !:
