### ISSUE TITLE
0.8.4

### ISSUE THREAD

**Issue by Bobowonnell** [Ettercap/ettercap#1030]
So I deleted all of my ettercap files to try and get 0.8.4 and I tried to follow the instruction to get it and install but i still had 0.8.3 plz help

**Comment by koeppea** [comment]
0.8.4 hasn't yet being released. So internally it's still firming as 0.8.3.
I guess I'll adjust that to 0.8.4_rc so that it's clear that it's not 0.8.3 and even not 0.8.4.
Thanks for the hint.

**Comment by Bobowonnell** [comment]
Ok np
