### ISSUE TITLE
--certificate/--private-key doesn't work

### ISSUE THREAD

**Issue by Tatuck** [Ettercap/ettercap#1031]
Hello!
I tried to use this command: ettercap -G --certificate cert.pem --private-key cert.pem

I cloned the certificate from facebook.com.
And i made a dns spoof with the arp poisoning but it doesn't work.

I don't know if i have to change something or what.

**Comment by koeppea** [comment]
Does _cert.pem_ really contains both, the private key and the certificate?
Is it possible to share the certificate / private key file? Maybe you can generate a one-off pair.
Is is possible to follow [these instructions](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) to provide debug information to troubleshoot your issue?

**Comment by Tatuck** [comment]
I think it has both, you can obtain it by clicking in the lock at the left of the url like so: 
![image](https://user-images.githubusercontent.com/59171409/80999820-901e1680-8e45-11ea-9913-038ba6a03d49.png)
then clicking in certificate -> details -> copy to a file.

And it didn't give me any error so it wouldn't be in the log.

**Comment by 0x6773** [comment]
@Tatuck if getting private key was that easy, there would have been no concept of certificates.

**Comment by Tatuck** [comment]
@0x6773 Oh that IS true, and, If I do a fake internet point, do you think I will be able to spoof their web?

**Comment by koeppea** [comment]
@Tatuck as @0x6773 has already pointed out, the server certificate that is presented to the browser is ONLY the certificate, with NO private key. So I assume your _cert.pem_ file didn't contain the private key, hence the command you've used cannot work.

You need to understand first what Internet security means and how it works, then you can answer your question yourself.
Without this understanding, I would say: no.

**Comment by Tatuck** [comment]
Thanks
