### ISSUE TITLE
what's wrong with sslstrip plugin?

### ISSUE THREAD

**Issue by phlmox** [Ettercap/ettercap#1032]
ettercap crashes when i double click sslstrip. my ettercap version is 0.8.3

**Comment by koeppea** [comment]
What OS do you use? I have tested the latest code from GitHub on Debian, and I have absolutely no issues.
Have you executed ettercap from the Terminal? Does it quit with some message?

I need a little more info to help you there.

**Comment by phlmox** [comment]
I'm using kali linux.
![m](https://user-images.githubusercontent.com/62145317/81008690-03cb1e00-8e5c-11ea-8872-b8b3a760a413.PNG)

**Comment by phlmox** [comment]
@koeppea can you help?

**Comment by koeppea** [comment]
This is fixed meanwhile in the latest code on GitHub.
So I would strongly recommend using this by compiling it from source.

Using the distribution provided version, you can avoid the behaviour setting UID and GID to 0, and uncomment the iptables redir and redir6 commands in **etter.conf**.

**Comment by koeppea** [comment]
BTW, this is anyway necessary to make the _sslstrip_ plugin work.

**Comment by phlmox** [comment]
i downloaded plugin sslstrip.c how can i install that

**Comment by koeppea** [comment]
No you have to edit the /etc/ettercap/etter.conf. There are 4 lines:
```
ec_uid = 65534                # nobody is the default
ec_gid = 65534                # nobody is the default
#redir_command_on = "iptables ....
#redir_command_off = "iptables ....
#redir6_command_on = "ip6tables ....
#redir6_command_off = "ip6tables ....
```
You need to change the two numbers to 0 and remove the '#' sign in front of the iptables redir commands.

**Comment by phlmox** [comment]
thank you for your patience :)
