### ISSUE TITLE
My ettercap says ""Failed to create secure directory (/root/.config/pulse): Permission denied""

### ISSUE THREAD

**Issue by Sevada797** [Ettercap/ettercap#1040]
Also in running it writes.

Lua: no scripts were specified, not starting up!

Please tell me how to fix this.
Can you tell me the name of directory i think i can create it with mkdir.
Do i need to install something else?

**Comment by koeppea** [comment]
How exactly do you call Ettercap?

**Comment by Sevada797** [comment]
sudo su
Ettercap -G

**Comment by koeppea** [comment]
OK please read [this page](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) and provide debug information as described there. With this level of information I can't really help.

**Comment by klokwert** [comment]
I have the same issue but I don't notice a something going wrong, but I'm interested what the file "/root/.config/pulse" is

**Comment by koeppea** [comment]
So basically this is something that is implicitely used by the GTK framework but isn't essential for Ettercap.
With Ettercap, we're following the approach to drop the privileges by default to avoid harm when parsing malicious packets that Ettercap processes as MITM software.
This has the consequence, that the "implicit" actions of the GTK library suffer the lack of permissions to do these background things.

However as you already recognized, nothing severe, therefore closing this issue with these words.
