### ISSUE TITLE
Ettercap v 0.8.3 no menu

### ISSUE THREAD

**Issue by sxm22** [Ettercap/ettercap#1048]
ettercap v 0.8.3 has no menu whatsoever on Kali Linux 
<img width="996" alt="Screen Shot 2020-06-18 at 9 30 26 PM" src="https://user-images.githubusercontent.com/67118371/85053016-eef7df00-b1aa-11ea-9c54-9024487089b0.png">

**Comment by NanduKkd** [comment]
You can use all those menu options by clicking that button on top right
side with three dots. I think this is not a problem with ettercap, it has
to deal with the version of Kali Linux you are using.

**Comment by sxm22** [comment]
the menu shows these options only. 

<img width="252" alt="Screen Shot 2020-06-18 at 9 53 01 PM" src="https://user-images.githubusercontent.com/67118371/85055080-1603e000-b1ae-11ea-9f52-6908309fd4d9.png">

**Comment by NanduKkd** [comment]
Ok I understand what you mean. Select the interface that you want, check
bridged sniffing if you want and then click on the button with the tick
mark on the top right side of the screen. Then you can find all those
options you need by clicking the same three dots button.

**Comment by sxm22** [comment]
Thank you so much !!!  It worked !!

**Comment by koeppea** [comment]
Great. I know the shift from the GTK2 to the GNOME/GTK3 UI design is not easy. However, all GTK/GNOME programs have had made this step and got rid of the classic menu bars.

I'm glad that you found it our yourself.

**Comment by stdedos** [comment]
If you are collecting the number of people hating that GTK3 transition somewhere, count me in 😕
