### ISSUE TITLE
Injecting a modified packet

### ISSUE THREAD

**Issue by electron1** [Ettercap/ettercap#1050]
I am trying to write a filter that has an external script modify a packet, and then send it on. 
What I did to this point is to first use log() to write the packet's payload, then call exec() to run the script (which alters the file that was just logged), then call drop(), then inject() the changed payload. Finally, I removed the log file so that I'm ready for the next packet. 
I think the problem I'm having is that the inject() happens too soon after the script is started, and the packet file hasn't been updated yet. Is there any way to fix this?

**Comment by koeppea** [comment]
Please read about the execinject function of etterfilter in the man page 
of etterfilter.

**Comment by electron1** [comment]
I'm unclear on how exactly it works: when the manual says "that it uses the output of a shell command to inject data rather than the contents of a file", what format of text does the shell command need to output? When I use inject() with a file it's raw binary, so I'm guessing it should be binary as well. Does the shell command need to output a sequence of ASCII characters? And how will that work if a given byte doesn't have a shell-printable encoding?

**Comment by electron1** [comment]
Thanks so much for pointing me to this. After some experimentation, I have figured it out. I greatly appreciate your quick response.

**Comment by charlie-12138** [comment]
> Thanks so much for pointing me to this. After some experimentation, I have figured it out. I greatly appreciate your quick response.

I have the same problem as you have,Can you tell me how you deal with it?

**Comment by electron1** [comment]
See this thread: https://github.com/electron1/LinearAlgebra/issues/1#issue-688669963
