### ISSUE TITLE
Can anyone help me??

### ISSUE THREAD

**Issue by kapadash** [Ettercap/ettercap#1051]
I used to be familiar with Ettercap on Kali, and back then when I wanted to use sslstrip I uncommented the lines that refer to iptables from the .conf file and also changed ec_uid and ec_gid to 0 , but now when I either do that or simply try to activate the sslstrip plugin from the manager the program crashes and I get the following:

 Ooops ! This shouldn't happen...
Segmentation Fault...

Please recompile in debug mode, reproduce the bug and send a bugreport

 Have a nice day!

I know this message applies for most issues so that's why I'm being as specific as possible about my case.
And I know that sslstrip is no longer part of Kali's tools but, with almost no effort, I could get it to work, and, even that there could possibly be something wrong with it, I am 100% it has nothing to do with this issue. I tried to use it with arpspoof and worked just fine but I didn't even get to try to use it with Ettercap, since it crashes, as I said, due to me trying to uncommenting the lines:

    #redir_command_on = "iptables -t nat -A PREROUTING -i %iface -p tcp -s %source -d %destination --dport %port -j REDIRECT --to-port %rport"
    #redir_command_off = "iptables -t nat -D PREROUTING -i %iface -p tcp -s %source -d %destination --dport %port -j REDIRECT --to-port %rport"

I don't know if there is ever been a solution for this problem  neither if is a new issue or not, but if anyone can help me I'd be really greatful.

PS: I used to play around with ettercap and sslstrip on a laptop running Kali and worked fine but now I'm doing it from a Virtual Machine using a bridged connection to my home network so maybe this might be happening because the traffic isn't being redirected correctly, but even if that's the case, why would it work with arpspoof? and why would it cause Ettercap to crash just by having the iptables option enabled?

**Comment by kapadash** [comment]
Just realized my mistake, I will close the issue but not delete it so if anyone has the same problem they know what to do, I think I was a little rusty and forgot to also uncomment:

redir6_command_on = "ip6tables -t nat -A PREROUTING -i %iface -p tcp -s %source -d %destination --dport %port -j REDIRECT --to-port %rport"
   redir6_command_off = "ip6tables -t nat -D PREROUTING -i %iface -p tcp -s %source -d %destination --dport %port -j REDIRECT --to-port %rport"

And that caused the program to crash.

**Comment by koeppea** [comment]
No that's fine. This is a bug. It's already known. It's fixed in 
0.8.4-rc which is the latest version on Github.

**Comment by koeppea** [comment]
Hi,

the external program sslstrip does the same thing as sslstrip plugin does.
The reason of the crash is most probably due to a bug in version 0.8.3 
when the IPv6 version of the redir commands are not activated while the 
IPv4 version is.

Please try to uncomment the redir6_... command lines as well.
