### ISSUE TITLE
drop() and replace() doesn't work in ROS

### ISSUE THREAD

**Issue by alexis-pepe** [Ettercap/ettercap#1053]
Hello, I am studying the communication of robot operating system recently. I learned from the literature that its communication mode is based on tcpros. I want to use ettercap to replace and change the payload in the communication process，I follow the filter.example , edit my own filter ,and the kill() functions can cut off the communication between the two srcip and dstip, but the drop() and replace() functions does not work. The packets can still reach the destination IP normally. I also want to use the inject() function. However, I don't know what format the contents of the inject() file are,like this    inject("./fake_telnet")     in the filter.example  ,What is the format and composition of the content in this document   "./fake_telnet"   Can you answer my questions and give me some suggestions? Thank you.

**Comment by alexis-pepe** [comment]
@koeppea

**Comment by alexis-pepe** [comment]
My approach is similar to this。。。{drop(); replace("\xff\xfe\x30\x00\xcf\xf8\x3f","\xff\xfe\x30\x00\xcf\x00\x00"）}

**Comment by koeppea** [comment]
Hi,

what does **ROS** mean?
First of all, `drop()` and `replace()` in combination does not make sense.
In your example you mark a packet to be dropped and then you replace the content.

Regarding the `inject()` function: The content of the file (raw) is used as the whole packet incl. IP header and TCP/UDP header.

The `inject()` function instead does make sense to be combined with the `drop()` function. Check also the `execinject()` and the newly introduced function `execreplace()` which might open upu new use-cases.

**Comment by alexis-pepe** [comment]
> Hi,
> 
> what does **ROS** mean?
> First of all, `drop()` and `replace()` in combination does not make sense.
> In your example you mark a packet to be dropped and then you replace the content.
> 
> Regarding the `inject()` function: The content of the file (raw) is used as the whole packet incl. IP header and TCP/UDP header.
> 
> The `inject()` function instead does make sense to be combined with the `drop()` function. Check also the `execinject()` and the newly introduced function `execreplace()` which might open upu new use-cases.

It's a great pleasure to receive your reply. ROS stands for robot operating systems, which are master-slave architectures whose communications are based on TCPROS.

I am trying to do a variety of attacks against robots, such as False Data Injection attacks and so on. According to your suggestion, the replace() function worked and successfully replaced the payload.

But I would like to ask if the 'with' in the replace(what,with) function can be turned into a formatted random content. For example, in the present moment, do replace("\xff\x30","\xff\x31") , In the next second, do replace("\xff\x30","\xff\x32") , let the replace() function make a random substitution.

Thank you for your guidance

**Comment by koeppea** [comment]
The newly introduced filter function `execreplace()` could help. it passes the data to an external program which is responsible to do the replacement and output the modified data on STDOUT.

**Comment by alexis-pepe** [comment]
Excuse me, I'm here again to ask you a question. I use the replace() function to handle the TCP payload, like this "replace("\xff\x30","\xff\x32")",  it works well. 

Now I want to try inject(), I first use the drop() function to discard the entire payload and then write "\xff\x32" to a file named "fake_telnet", using inject("./fake_telnet"), as described in the "etterfilter.8.pdf" file, but it didn't seem to work.

Am I doing this correctly? Is the content in the "fake_telnet" correct like this "\xff\x32" , do I need to use "" . Is the content in the "fake_telnet" the same as "with" in replace(what, with)?

Looking forward to your reply!

**Comment by alexis-pepe** [comment]
@koeppea

**Comment by koeppea** [comment]
@alexis-pepe Sorry for my late response. I've overlooked your reply.
I've tried to reproduce and it worked for me.
I've let a server run on port 1234.
I wrote a filter that injects payload if conditions are met.
See the screenshot as proove of concept:
![Bildschirmfoto vom 2020-09-26 19-24-12](https://user-images.githubusercontent.com/4201853/94346713-d3646600-002e-11eb-9c80-62883c6ff578.png)

You can see the filter source code, the content of the fake response file and that the server received the fake payload.
Hope that helps you.
