### ISSUE TITLE
menu bar not visible 

### ISSUE THREAD

**Issue by sethkuma** [Ettercap/ettercap#1056]
![Screenshot_20200709_203019](https://user-images.githubusercontent.com/68070667/87056299-0c0c5480-c223-11ea-8cc8-d5a8135a1e8e.png)
as see in the image there is no menu option i'm using kali linux

**Comment by NanduKkd** [comment]
See [this issue](https://github.com/Ettercap/ettercap/issues/1048)

**Comment by sethkuma** [comment]
> See [this issue](https://github.com/Ettercap/ettercap/issues/1048)

Thabks nandu :1st_place_medal:

**Comment by NanduKkd** [comment]
Anytime
