### ISSUE TITLE
Convert fingerprint POST to use libcurl instead

### ISSUE THREAD

**Issue by eaescob** [Ettercap/ettercap#1059]
https://github.com/Ettercap/ettercap/blob/4998b5726ddf136a3f6808c0f59f072a96a7a9d5/src/ec_fingerprint.c#L340

**Comment by diamant3** [comment]
I think this is already fixed by PR https://github.com/Ettercap/ettercap/commit/7065b664ca722a606e3b39919c9ddd4667d68d85 and hopefully can be closed now
