### ISSUE TITLE
Issue with DNS_SPOOF

### ISSUE THREAD

**Issue by volt2054** [Ettercap/ettercap#1061]
I cannot get dns spoof to work, I saw an earlier post from 2018 here : https://github.com/Ettercap/ettercap/issues/889. I did everything he did but instead on 0.8.3 of course. Everything was set up properly. The issue is instead of redirecting it is just not loading the page. I am running ettercap as root with -G

It was also saying it was spoofing

![Screenshot_2020-07-21_20-09-29](https://user-images.githubusercontent.com/31824408/88096252-e158bf00-cb85-11ea-8b91-8aeabc338696.png)
![Screenshot_2020-07-21_20-10-04](https://user-images.githubusercontent.com/31824408/88096257-e1f15580-cb85-11ea-829c-727c585fba20.png)

These screenshots are from /etc/ettercap/etter ".conf/dns"

And yes i do have an Apache server running that I have checked works on other devices on LAN

EDIT: My phone was on 192.168.1.199 and my laptop was at 192.168.1.220
EDIT2: I can't seem to even find my phone anymore when I scan and can't get a screenshot while spoofing.

**Comment by koeppea** [comment]
Does Ettercap show anything in the message pane during the spoof action?
Please also read [our info about HSTS](https://github.com/Ettercap/ettercap/wiki/HTTPS-and-HSTS).

**Comment by volt2054** [comment]
I can't access it right now but it said something along the lines of, and in that info are you suggesting that I use the sslstrip plugin.
[Dns Spoof] www.google.com A 192.168.1.220
[Dns Spoof] clients4.google.com A 192.168.1.220

and in that wiki page are you suggesting that I use the sslstrip plugin. is this basically just removing the https from the website.

**Comment by koeppea** [comment]
> is this basically just removing the https from the website

correct. It modifies the `https://` scheme to `http://`.

> in that wiki page are you suggesting that I use the sslstrip plugin

basically not. For HSTS enabled websites, this won't work. HSTS makes the browser to insist on `https://`. it should just make you aware about the technology and that it's not that trivial to break into a SSL connection.



> [Dns Spoof] [www.google.com](http://www.google.com) A 192.168.1.220
> [Dns Spoof] clients4.google.com A 192.168.1.220

If you saw such a message, the DNS reply has been spoofed. Looking at your **etter.dns** file, you may have missed the IPv6 related DNS lookups.

Try adding the following line to suppress IPv6 traffic:
```
*    AAAA    ::
```

**Comment by volt2054** [comment]
Thank you.
Thanks for quick replies and helping my problem.
