### ISSUE TITLE
fatal error: hb.h: No such file or directory    28 | #include <hb.h>

### ISSUE THREAD

**Issue by thomas25691** [Ettercap/ettercap#1062]
Hi @koeppea , could you help me ,i got a problem when i run  the "make" command :

fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
   
the details are as following:

root@jackiekali:/opt/ettercap/ettercap-0.8.3/build# make
[  0%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/gtk-3.0/gdk/gdktypes.h:35,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /opt/ettercap/ettercap-0.8.3/src/interfaces/gtk3/ec_gtk3.h:4,
                 from /opt/ettercap/ettercap-0.8.3/src/ec_interfaces.c:31:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
make[2]: *** [src/interfaces/CMakeFiles/ec_interfaces.dir/build.make:63: src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:485: src/interfaces/CMakeFiles/ec_interfaces.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
root@jackiekali:/opt/ettercap/ettercap-0.8.3/build# 

![2020-07-24_181846](https://user-images.githubusercontent.com/13898287/88475837-1ee29100-cf66-11ea-8651-70f26e63338d.jpg)

**Comment by gvanem** [comment]
> fatal error: hb.h: No such file or directory

That is the HarfBuzz library; https://harfbuzz.github.io/building.html#building.linux
Could be a part of the spaghetti-package GNome is responsible for.

**Comment by thomas25691** [comment]
uh but i never used this HarfBuzz , never heard about it . what shoud i do ?

**Comment by thomas25691** [comment]
> 
> 
> > fatal error: hb.h: No such file or directory
> 
> That is the HarfBuzz library; https://harfbuzz.github.io/building.html#building.linux
> Could be a part of the spaghetti-package GNome is responsible for.

uh but i never used this HarfBuzz , never heard about it . what shoud i do ?

**Comment by gvanem** [comment]
Did you read the link I gave you?

Well, HarfBuzz is *text shaping* library that puts together characters into words/sentences like this:
![HarfBuff-basic-use](https://user-images.githubusercontent.com/945271/88477646-17a98c00-cf42-11ea-92f2-23873f6409f2.png)

You do **not** simply draw the fonts of **F** **i** **r** **e** to the screen That goes against 300 years of typography.
But rather combine **F-i** into a ligature **Fi** (note how they overlap). So HarfFuzz is absolutely needed by Pango to produces top-quality text output. Get it?

**Comment by thomas25691** [comment]
> 
> 
> Did you read the link I gave you?
> 
> Well, HarfBuzz is _text shaping_ library that puts together characters into words/sentences like this:
> ![HarfBuff-basic-use](https://user-images.githubusercontent.com/945271/88477646-17a98c00-cf42-11ea-92f2-23873f6409f2.png)
> 
> You do **not** simply draw the fonts of **F** **i** **r** **e** to the screen That goes against 300 years of typography.
> But rather combine **F-i** into a ligature **Fi** (note how they overlap).
> 
> So HarfBuzz is absolutely needed by Pango to produce top-quality text output. Get it?

okay thx ~

**Comment by gvanem** [comment]
> That goes against 300 years of typography.

It's actually 450 years. Gutenberg used the technique.

**Comment by thomas25691** [comment]
i made a new directory /opt/HarfBuzz , and built it from the source in the HarfBuzz git repository.
then changed directory to /opt/ettercap/ettercap-0.8.3/build
then did :
$ make clean-all
$ cmake ../
$ make

still failed in 'make' process

where shoud i build the HarfBuzz?  is it in usr/include/pango-1.0/pango ?

**Comment by gvanem** [comment]
> where shoud i build the HarfBuzz? 

Did you install it too? I guess a `make install` would put `hb.h` under `/usr/include/HarfBuzz`. 
Or `/usr/include/gtk-3.0/HarfBuzz`? But I do not use CMake (hate it). Besides I'm on Windows. 

But it looks like your GTK3 installation is messed up. Where/how did you get it?

**Comment by koeppea** [comment]
@thomas25691 From where have you downloaded the source?
We've done some fixes for detecting the new pango dependency but this is not included in the released package 0.8.3.
It will be included in the next release or if you compile the latest source from GitHub instead.

**Comment by LocutusOfBorg** [comment]
yes, the master branch should have the fix

if you want just that fix, you might want to apply parts of this patch
https://github.com/Ettercap/ettercap/pull/988/files

**Comment by LocutusOfBorg** [comment]
In specific you probably need the changes in FindGTK3.cmake file (delete 3 lines, add one)

**Comment by LocutusOfBorg** [comment]
This one is even more compact
https://sources.debian.org/src/ettercap/1:0.8.3-7/debian/patches/988.patch/

**Comment by thomas25691** [comment]
> 
> 
> > where shoud i build the HarfBuzz?
> 
> Did you install it too? I guess a `make install` would put `hb.h` under `/usr/include/HarfBuzz`.
> Or `/usr/include/gtk-3.0/HarfBuzz`? But I do not use CMake (hate it). Besides I'm on Windows.
> 
> But it looks like your GTK3 installation is messed up. Where/how did you get it?

after i did make install to harfbuzz, i can see hb.h file in /usr/local/include/harfbuzz
![2020-07-28_152150](https://user-images.githubusercontent.com/13898287/88632405-1d3fd700-d0e6-11ea-8960-45a24971289f.jpg)


,but still occur the error when i do make to ettercap.........

i installed GTK3 by following the instruction in the README file in ettercap-0.8.3 fold .

README file said as following:
If you are running on debian, or any debian based distro you can install
the required dependencies by running:

apt-get install debhelper bison check cmake flex ghostscript libbsd-dev \
      libcurl4-openssl-dev libgeoip-dev libltdl-dev libluajit-5.1-dev \
      libncurses5-dev libnet1-dev libpcap-dev libpcre3-dev libssl-dev \
      libgtk-3-dev libgtk2.0-dev

**Comment by thomas25691** [comment]
> 
> 
> > where shoud i build the HarfBuzz?
> 
> Did you install it too? I guess a `make install` would put `hb.h` under `/usr/include/HarfBuzz`.
> Or `/usr/include/gtk-3.0/HarfBuzz`? But I do not use CMake (hate it). Besides I'm on Windows.
> 
> But it looks like your GTK3 installation is messed up. Where/how did you get it?

seems nothing wrong with installing  the required dependencies 
![2020-07-28_152404](https://user-images.githubusercontent.com/13898287/88632719-8fb0b700-d0e6-11ea-9120-8cefa642ba39.jpg)

**Comment by thomas25691** [comment]
> 
> 
> @thomas25691 From where have you downloaded the source?
> We've done some fixes for detecting the new pango dependency but this is not included in the released package 0.8.3.
> It will be included in the next release or if you compile the latest source from GitHub instead.
Hi i got it from   https://github.com/harfbuzz/harfbuzz  
i downloaded it by executing :
gitclone https://github.com/harfbuzz/harfbuzz /opt/HarfBuzz

**Comment by thomas25691** [comment]
> 
> 
> yes, the master branch should have the fix
> 
> if you want just that fix, you might want to apply parts of this patch
> https://github.com/Ettercap/ettercap/pull/988/files

okay thx,but i don't know how to use the code .
and how to change FindGTK3.cmake file (delete 3 lines, add one)
I'm newbie ........

**Comment by LocutusOfBorg** [comment]
apt-get install ettercap-graphical and use it.
I patched it half an year ago, and its available in kali since that time.

**Comment by LocutusOfBorg** [comment]
otherwise, if you want to git clone and build from source, you can follow the instructions in README.GIT file

**Comment by thomas25691** [comment]
> apt-get install ettercap-graphical

okay i did apt-get install ettercap-graphical 
and then  did :
$ make clean-all
$ cmake ../
$ make
and still failed 
![1](https://user-images.githubusercontent.com/13898287/88636796-f5537200-d0eb-11ea-9a1b-0c4a372ae307.jpg)

**Comment by thomas25691** [comment]
> 
> 
> otherwise, if you want to git clone and build from source, you can follow the instructions in README.GIT file

root@jackiekali:/opt/ettercap/ettercap-0.8.3/build# cmake /opt/ettercap/ettercap-0.8.3
-- The C compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for sys/poll.h
-- Looking for sys/poll.h - found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sys/utsname.h
-- Looking for sys/utsname.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for arpa/nameser.h
-- Looking for arpa/nameser.h - found
-- Looking for ltdl.h
-- Looking for ltdl.h - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for libgen.h
-- Looking for libgen.h - found
-- Looking for wsyncup in /usr/lib/x86_64-linux-gnu/libcurses.so
-- Looking for wsyncup in /usr/lib/x86_64-linux-gnu/libcurses.so - found
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncurses.so
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncurses.so - found
-- Found Curses: /usr/lib/x86_64-linux-gnu/libncurses.so  
-- No GTK_BUILD_TYPE defined, default is GTK3
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.10.2") 
-- Found GTK3_GTK: /usr/lib/x86_64-linux-gnu/libgtk-3.so  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1g")  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for iconv
-- Looking for iconv - found
-- CURL support requested. Will look for curl >= 7.26.0
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (Required is at least version "7.26.0") 
-- Looking for poll
-- Looking for poll - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for select
-- Looking for select - found
-- Looking for scandir
-- Looking for scandir - found
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strlcat in bsd
-- Looking for strlcat in bsd - found
-- Looking for strlcpy in bsd
-- Looking for strlcpy in bsd - found
-- Looking for strsep
-- Looking for strsep - found
-- Looking for strcasestr
-- Looking for strcasestr - found
-- Looking for memmem
-- Looking for memmem - found
-- Looking for memrchr
-- Looking for memrchr - found
-- Looking for basename
-- Looking for basename - found
-- Looking for strndup
-- Looking for strndup - found
-- GeoIP support requested. Will look for the legacy GeoIP C library
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'geoip'
-- Found GEOIP: /usr/lib/x86_64-linux-gnu/libGeoIP.so  
-- Found LIBNET: /usr/lib/x86_64-linux-gnu/libnet.so  
-- Found PCRE: /usr/lib/x86_64-linux-gnu/libpcre.so  
-- Performing Test HAVE_MUTEX_RECURSIVE_NP
-- Performing Test HAVE_MUTEX_RECURSIVE_NP - Success
-- Found BISON: /usr/bin/bison (found version "3.6.3") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- The following OPTIONAL packages have been found:

 * Freetype
 * GTK3 (required version >= 3.12.0)
 * CURL (required version >= 7.26.0)
 * PkgConfig
 * GEOIP
 * LIBNET
 * PCRE
 * BISON
 * FLEX

-- The following REQUIRED packages have been found:

 * Curses
 * OpenSSL
 * ZLIB
 * Threads

-- Configuring done
-- Generating done
-- Build files have been written to: /opt/ettercap/ettercap-0.8.3/build

**Comment by thomas25691** [comment]
> use it

i installed it but don't know how to use it
![2](https://user-images.githubusercontent.com/13898287/88638594-46fcfc00-d0ee-11ea-81fe-5a592c4d8554.jpg)

**Comment by koeppea** [comment]
Open a new Terminal and type `sudo ettercap -G`. see `man ettercap` for more information how to use it.
