### ISSUE TITLE
[Request] Device Traffic History

### ISSUE THREAD

**Issue by zero77** [Ettercap/ettercap#1063]
Can you please add a history section for each device because, when using ettercap on networks with a lot of traffic it can be hard to pick out useful info as it can get lost in all the events, thanks.

**Comment by koeppea** [comment]
Please be more specific? Do you mean credential info seen?
At least this topic is already on my TODO.

**Comment by zero77** [comment]
Unless i am mistaken you can already capture credentials with mitm.

I am meaning more of an overview of activity history of the domains visited by a device and the installed applications and antivirus on the device.

**Comment by koeppea** [comment]
> Unless i am mistaken you can already capture credentials with mitm.

Depends. Using standard protocols yes. If protocol uses encryption it can become quite difficult - which is the purpose of encryption.

> ... overview of activity history of the domains visited by a device ....

I think this can be done at least if HTTP is used. In case of HTTPS, a successful SSL interception would be required.


> ... and the installed applications and antivirus on the device

This is not possible, since ettercap does only work on the network traffic layer. The only thing would be the use of fingerprints but this could only detect the OS used with a certain probability. Ettercap is not supposed to look onto devices.

**Comment by gvanem** [comment]
> | ... overview of activity history of the domains visited by a device ....
> I think this can be done at least if HTTP is used. In case of HTTPS, a successful SSL interception would be required.

You mean that most browsers now use DNS-over-HTTPS? My Chrome doesn't since it's slower. I probably can though.
But off-course the URL within the domain goes over TLS.

**PS**. Visiting `github.com` just now with `windump -n port 53` on the since triggered 66 DNS messages  in total!

**Comment by zero77** [comment]
> I think this can be done at least if HTTP is used. In case of HTTPS, a successful SSL interception would be required.

Yes unencrypted traffic would make things easier, though i don't know how widespread encrypted dns is yet.
> This is not possible, since ettercap does only work on the network traffic layer. The only thing would be the use of fingerprints but this could only detect the OS used with a certain probability. Ettercap is not supposed to look onto devices.

This should be possible at the network level perhaps by looking at the user agent, but fingerprinting may be more accurate.
Failing this reverse ip lookup could be used.

The following post explains how you can find installed AV using domains, which could be expanded to common applications.
https://null-byte.wonderhowto.com/how-to/identify-antivirus-software-installed-targets-windows-10-pc-0198775/

**Comment by koeppea** [comment]
Tracking URLs is possible using an existing plugin: **remote_browser**.
It executes the *remote_browser* command and replaces the placeholders `%host` and `%url` with the *Host* HTTP header value and the *GET* String.

So instead of the default value of 
```
remote_browser = "xdg-open http://%host%url"
```

You could use your own logger like:
```
remote_browser = "/path/to/custom_logger.sh %host %url"
```

**Comment by koeppea** [comment]
In my opinion using an customized external program in combination with the *remote_browser* plug-in accomplishes what's been asked here. Closing.
