### ISSUE TITLE
Etterfilter version

### ISSUE THREAD

**Issue by Root-Thomas** [Ettercap/ettercap#1065]
I try to do `etterfilter -t /home/root/test.js` but etterfilter output say that 

**FATAL: Bad magic in filter file**
**Make sure to compile the filter with a current version of etterfilter**

My question is how do you update the Etterfilter ?

**Comment by koeppea** [comment]
Yes. This is mandatory to satisfy a security flaw.
Given your your filter source file being at `/usr/src/filter.ecf` and your destination compiled filter file at `/tmp/filter.ef` you just have to type
```
$ etterfilter -f /usr/src/filter.ecf /tmp/filter.ef
```

**Comment by Root-Thomas** [comment]
Oh thank you very much!

**Comment by Root-Thomas** [comment]
> Yes. This is mandatory to satisfy a security flaw.
> Given your your filter source file being at `/usr/src/filter.ecf` and your destination compiled filter file at `/tmp/filter.ef` you just have to type
> 
> ```
> $ etterfilter -f /usr/src/filter.ecf /tmp/filter.ef
> ```

sorry for bottering you again but its not working, `-f` is not an option of etterfiltter and the there's no file named filter.ecf located at `/usr/src/filter.ecf` or `/tmp/filter.ef`
