### ISSUE TITLE
Wrongly use libdbus API which can cause DoS

### ISSUE THREAD

**Issue by Zero0one1** [Ettercap/ettercap#1070]
Hi, developers:

In souce code `src/ec_capture.c:113`, it calls `pcap_findalldevs()` while missing  `pcap_freealldevs()`  call after use.

According to the [documentation of pcap_findalldevs](https://www.tcpdump.org/manpages/pcap_findalldevs.3pcap.html ) , The list of devices must be freed with `pcap_freealldevs()`.

This bug results in a memory leak and may cause DoS

In some cases,  this function may be called many times, the memory consumption would be huge, which may cause the process to corrupt.

```cpp
105 void capture_getifs(void)
106 {
107    pcap_if_t *dev, *pdev, *ndev;
108    char pcap_errbuf[PCAP_ERRBUF_SIZE];
109 
110    DEBUG_MSG("capture_getifs");
111 
112    /* retrieve the list */
113    if (pcap_findalldevs((pcap_if_t **)&EC_GBL_PCAP->ifs, pcap_errbuf) == -1)
114       ERROR_MSG("%s", pcap_errbuf);

```

**Comment by koeppea** [comment]
Closing as I assume #1075 fixes this issue.
