### ISSUE TITLE
Ettercap and SSL sniffing 

### ISSUE THREAD

**Issue by DominikWeglarz** [Ettercap/ettercap#1076]
Hi !
I cannot run ettercap  with SSL sniffing in Kali Linux (2017.x - 2020.x) nor Parrot OS (4.10)

After  changes in /etc/ettercap/etter.conf  :

-------------------------------------------------------------------------------------------------------
[privs]
                ec_uid = 0                # nobody is the default
                ec_gid = 0                # nobody is the default

...

redir_command_on = "iptables -t nat -A PREROUTING -i %iface -p tcp -d %destination --dport %port -j REDIRECT --to-port %rport"
redir_command_off = "iptables -t nat -D PREROUTING -i %iface -p tcp -d %destination --dport %port -j REDIRECT --to-port %rport"

...
-------------------------------------------------------------------------------------------------------

When I start ettercap -C 
(--> Sniff --> Unified Sniffing --> eth0)
I  get error : 

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

FATAL ERROR: Can't insert firewall redirects

During tests in /var/log/messages  I can see two lines are added : 

Sep 27 16:30:39 parrot kernel: [10833.612842] device eth0 entered promiscuous mode
Sep 27 16:30:39 parrot kernel: [10833.650622] device eth0 left promiscuous mode

Conditions
1. Iptables are installed and running 
2. I run command "ettercap -C" as root.
3. SElinux is disabled.
4. Apparmor is disabled.
5. The same problems are in GUI (ettercap window just disappear)

I have also did tracing this action in strace (in attachment) - but I am not developer/debuger at all so I cannot figure out what is wrong. Strace was run on PID of process "ettercap -C"  after choosing --> Sniff --> Unified Sniffing  but before accepting eth0 (after accept eth0 I get en error) - so it should "catch" momoent with problems.

![parrot1](https://user-images.githubusercontent.com/71975425/94367692-9fe21400-00e0-11eb-87ef-b477b2c85a16.png)
![parrot2](https://user-images.githubusercontent.com/71975425/94367693-a1abd780-00e0-11eb-9256-feb64cc36bc1.png)
![parrot3](https://user-images.githubusercontent.com/71975425/94367694-a2446e00-00e0-11eb-92f0-2031b06f7d20.png)

[ettercap-C_debug.txt](https://github.com/Ettercap/ettercap/files/5288468/ettercap-C_debug.txt)

**Comment by DominikWeglarz** [comment]
Hi again !

Problem solved.
Thanks @koeppea for your comments in other similar thread !!!

The problem was that 
    I DIDN'T uncomment redirection for IPv6 !!!

I'm not sure why - because all my test enviroment use only IPv4 - but trick with IPv6 did job good.

**Comment by koeppea** [comment]
The reason is that ettercap has been compiled with IPv6 support. The latest version 0.8.3.1 should not crash in that event. However the error message could be more meaningful.

**Comment by bolt162** [comment]
Hello there, I am having the same problem. Could you specify the file in which you uncommented the redirect statement? Thanks.

**Comment by DominikWeglarz** [comment]
It’s on top of thread :
/etc/ettercap/etter.conf

Dominik.

**Comment by legioo** [comment]
Elimine los # y si funcionó👍

**Comment by wannacry3030** [comment]
> Hi again !
> 
> Problem solved. Thanks @koeppea for your comments in other similar thread !!!
> 
> The problem was that I DIDN'T uncomment redirection for IPv6 !!!
> 
> I'm not sure why - because all my test enviroment use only IPv4 - but trick with IPv6 did good job.

that worked for me too, tks

**Comment by masshuvo** [comment]
> Hi again !
> 
> Problem solved. Thanks @koeppea for your comments in other similar thread !!!
> 
> The problem was that I DIDN'T uncomment redirection for IPv6 !!!
> 
> I'm not sure why - because all my test enviroment use only IPv4 - but trick with IPv6 did good job.

that worked for me too.....thank you

**Comment by cyberpsychooo** [comment]
> > Hello there, I am having the same problem. Could you specify the file in which you uncommented the redirect statement? Thanks.
> 
> I was looking for the same. I did not understood what he meant to say with redirect statement like you. I did:
> 
> sudo nano /etc/ettercap/etter.conf Press Ctrl+W and paste redir_command_ Look for your operating system and uncomment (remove the #) from #redir_command_on, #redir_command_off, #redir6_command_on and #redir6_command_off.
> 
> And ettercap does not complains now.

worked for me
