### ISSUE TITLE
Unable to create user data directory '/root/.local/share' for storing the recently used files list: Not a directory on Kali

### ISSUE THREAD

**Issue by jacknaguib** [Ettercap/ettercap#1083]
kali@kali:~$ uname -r
5.8.0-kali2-amd64

kali@kali:~$ sudo ettercap -G
[sudo] password for kali: 

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

(ettercap:29126): Gtk-CRITICAL **: 18:00:28.680: Unable to create user data directory '/root/.local/share' for storing the recently used files list: Not a directory

(ettercap:29126): Gtk-WARNING **: 18:00:28.717: Unable to open server bookmarks: Failed to open file “/root/.config/gtk-3.0/servers”: Permission denied

(ettercap:29126): dconf-CRITICAL **: 18:00:28.735: unable to create directory '/root/.cache/dconf': Not a directory.  dconf will not work properly.

**Comment by LocutusOfBorg** [comment]
this is a non issue, but if you use the search on closed issues you will find references related to how to fix (setting uid), or just ignore the problem :)
