### ISSUE TITLE
error message with sub-interface

### ISSUE THREAD

**Issue by Raizo62** [Ettercap/ettercap#1094]
Hi

I use ettercap-text-only 1:0.8.3.1-3 on Debian

I have 1 interface enp1s0 and 2 sub-interfaces enp1s0:10 and enp1s0:20

```
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 0c:a4:b5:91:43:00 brd ff:ff:ff:ff:ff:ff
    altname enp0s4
    inet 10.0.0.1/24 brd 10.0.0.255 scope global enp1s0:10
       valid_lft forever preferred_lft forever
    inet 20.0.0.1/24 brd 20.0.0.255 scope global enp1s0:20
       valid_lft forever preferred_lft forever
    inet6 fe80::ea4:b5ff:fe91:4300/64 scope link 
       valid_lft forever preferred_lft forever
```

The command line of ettercap on the interface enp1s0 runs: `ettercap -Tq -i enp1s0 -M dhcp:10.0.0.10-20/255.255.255.0/10.0.0.100`

but ettercap on the sub-interface enp1s0:10 fails : 
```
ettercap -Tq -i enp1s0:10 -M dhcp:10.0.0.10-20/255.255.255.0/10.0.0.100

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

Listening on:
enp1s0:10 -> 0C:A4:B5:91:43:00
          10.0.0.1/255.255.255.0



ERROR : 2, No such file or directory
[/build/ettercap-6xeL7B/ettercap-0.8.3.1/src/os/ec_linux.c:disable_ipv6_forward:118]

 failed to open /proc/sys/net/ipv6/conf/enp1s0:10/forwarding

```

**Comment by LocutusOfBorg** [comment]
do you have ipv6 on your board?
what is the content of that file that can't be opened?

**Comment by LocutusOfBorg** [comment]
oh indeed, the sub10 should be stripped from the interface when enabling ip forwarding... we should only use enp1s0 maybe...

**Comment by Raizo62** [comment]
Yes. I suppose that you already do that for IPv4 (no warning), and you forgot for IPv6

**Comment by koeppea** [comment]
> and you forgot for IPv6

no unfortunately the explanation isn't that easy.
Under Linux IPv4 allows only one global configuration for packet forwarding while for IPv6, Linux allows this per interface.
So IPv4 doesn't care for interface names at all, while IPv6 has to.
Will raise a pull-request to fix that.

**Comment by koeppea** [comment]
Could you please try if PR #1095 fixes the issue for you?

**Comment by Raizo62** [comment]
I have tested your code and i don't see the issue anymore :-) Thanks
