### ISSUE TITLE
Need help with /etc/ettercap/etter.dns  

### ISSUE THREAD

**Issue by kieran6704** [Ettercap/ettercap#1096]
I'd like to redirect all traffic to my local host, which i can do

when i redirect all traffic to a web address (eg. rickroll) it gets stuck in a loop redirecting to its self
how do i make an exection? in /etc/ettercap/etter.dns

**Comment by LocutusOfBorg** [comment]
are you using dns_spoof plugin?

**Comment by kieran6704** [comment]
yes.

**Comment by LocutusOfBorg** [comment]
did you read online tutorials such as
https://www.thegeekstuff.com/2012/05/ettercap-tutorial/ ?

**Comment by kieran6704** [comment]
Thanks this is quite useful, 
Is target 1 router and target 2 host?

**Comment by LocutusOfBorg** [comment]
```
The parameter "oneway" will force ettercap to poison only from TARGET1 to TARGET2. Useful if you want to poison only the client and not the router (where an arp watcher can be in place).
```

**Comment by koeppea** [comment]
Is this issue answered?

**Comment by koeppea** [comment]
I assume the issue got answered due to the lack of response.
