### ISSUE TITLE
Invalid entry in etter.conf line 31

### ISSUE THREAD

**Issue by etteruser** [Ettercap/ettercap#1097]
When I try to run ettercap I get:

`Invalid entry in etter.conf line 31`

I am using an updated Ubuntu 16.04.7 LTS and I followed exactly the installation guide, didn't touch any source code or anything, just installed the dependences (some of them might be old because 16.04 ubuntu?) / git cloned / cmake / make
I also tried to compile ettercap using cmake -DCMAKE_BUILD_TYPE=Debug but I couldn't see any errors only this warning

`ef_syntax.c:1458:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_s`

Thank you, hope you can help me.

**Comment by koeppea** [comment]
Ok seems you're facing two different issues.
The first one seems to be related to an syntax error in the etter.conf file.
The latter one can be somewhat ignored as it's only a warning (even though warnings almost always point to actual issues).

So I'll always ask you to test against the most current code from GitHub.
However, for that you'd have to completely purge ettercap before getting and compiling the source code on your machine.

You'd first search what's installed using Ubuntu by:
```
dpkg -l | egrep '^i.+ettercap'
```
Uninstall these packages first before you begin to download and compile/install Ettercap source code as it might be conflicting...

**Comment by LocutusOfBorg** [comment]
The second issue is about an old bison/flex on Ubuntu 16.04. Actually harmless...

**Comment by koeppea** [comment]
@etteruser is here any update? Any more details. E.g. do you have more than 1 _etter.conf_ file? or what's at line 31 in the _etter.conf_?

**Comment by koeppea** [comment]
Closing due to no further response. Reopen if you can provide the requested information.
