### ISSUE TITLE
What is the difference between "///" and "//" ?   (TARGET SPECIFICATION)

### ISSUE THREAD

**Issue by uranoni** [Ettercap/ettercap#1098]
In Document "//" means "all the hosts in the subnet.

target: 10.10.1.91
all the host: ///

But I saw  somebody use " /// " like this   => `ettercap -T -q -M ARP:remote /10.10.1.91// /// `  
1.Dobule slash and triple slash is different?
2.Is the order different?
 `ettercap -T -q -M ARP:remote /10.10.1.91// /// `    or  `ettercap -T -q -M ARP:remote  /// /10.10.1.91//`

**Comment by koeppea** [comment]
I think the man page explains it quite well:
```
       If IPv6 is enabled:
       TARGET is in the form MAC/IPs/IPv6/PORTs
       Otherwise,
       TARGET is in the form MAC/IPs/PORTs
```
