### ISSUE TITLE
GTK issue occurs while starting up

### ISSUE THREAD

**Issue by rong-xiaoli** [Ettercap/ettercap#1105]
When I run ettercap in GTK mode, it didn't came up with any graphical interface while starting up and after a while, an error came up like this: 
```
Failed to register: Timeout was reached
```
And then, it kept reporting these two errors:
```
(ettercap:10031): Gtk-CRITICAL **: 16:58:19.892: gtk_text_buffer_get_end_iter: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

(ettercap:10031): Gtk-CRITICAL **: 16:58:19.892: gtk_text_buffer_insert: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed
```
I'm not so familiar with Kali or GTK or sth, forgive me XP. 
(By the way, first time asking a question, sorry for such a messy one)

**Comment by LocutusOfBorg** [comment]
mmm how do you launch it?
did you compile from scratch?
which version?
what does strace ettercap gives you?

**Comment by koeppea** [comment]
@rong-xiaoli : Any update?

**Comment by rong-xiaoli** [comment]
Sorry not replying (because I' m busy doing homework). Now, it was solved and I have no idea how I solved this problem.
I ran it on kali-5.9.0, and it was installed on the system. Actually I upgraded the system from 5.8.0 and, I updated Ettercap with apt, version 0.5.4. 
I launched it with sudo, in console. 
p.s. I 've never tried strace, as I 'm not familiar with the commands on Linux platform. XP

**Comment by rong-xiaoli** [comment]
> Sorry not replying (because I' m busy doing homework). Now, it was solved and I have no idea how I solved this problem.
> I ran it on kali-5.9.0, and it was installed on the system. Actually I upgraded the system from 5.8.0 and, I updated Ettercap with apt, version 0.5.4.
> I launched it with sudo, in console.
> p.s. I 've never tried strace, as I 'm not familiar with the commands on Linux platform. XP

And also, thanks for replying this issue (though no solution was offered.)

**Comment by LocutusOfBorg** [comment]
thanks! I'm closing then, since it seems to be not an issue anymore!
