### ISSUE TITLE
I need the manual (man-page) of etterfilter to study

### ISSUE THREAD

**Issue by gilbertocarcamo** [Ettercap/ettercap#1107]
I need the manual (man-page) of etterfilter to study

**Comment by koeppea** [comment]
This is a good start.
Also consider the examples stored in the share folder.

**Comment by gilbertocarcamo** [comment]
How do I access the shared folder you mention?

**Comment by LocutusOfBorg** [comment]
https://github.com/Ettercap/ettercap/tree/master/share

**Comment by koeppea** [comment]
When Ettercap is installed on your computer you find it either under `/usr/share/ettercap` or `/usr/local/share/ettercap`.
Closing then.
