### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Aco465** [Ettercap/ettercap#1115]
Hello can you please help me? I get the following error: 
┌──(root💀kali)-[~]
└─# sudo ettercap -T -S -i eth0 -M arp:remote /192.168.1.34// /192.168.1.324//                                                                                                                                                          
ERROR : 2, No such file or directory
[/build/ettercap-6xeL7B/ettercap-0.8.3.1/src/ec_conf.c:load_conf:294]

 Cannot open etter.conf
 Can you help me i tried everything?

**Comment by koeppea** [comment]
How have you installed ettercap? From source? Or via apt?

**Comment by Aco465** [comment]
> what says `find / -name etter.conf 2>/dev/null` ?

it says /root/ettercap/build/share/etter.conf

**Comment by koeppea** [comment]
Ok that means that you have not installed ettercap using apt. You have cloned the source code.
Do you know want the Kali provided ettercap package or compiled from GitHub?

**Comment by Aco465** [comment]
> Ok that means that you have not installed ettercap using apt. You have cloned the source code.
> Do you know want the Kali provided ettercap package or compiled from GitHub?

I want the Kali provided ettercap.

**Comment by LocutusOfBorg** [comment]
```
sudo apt-get install ettercap-graphical
```

**Comment by Aco465** [comment]
> ```
> sudo apt-get install ettercap-graphical
> ```

I installed it and tried it again and this is what i get
ERROR : 2, No such file or directory
[/build/ettercap-6xeL7B/ettercap-0.8.3.1/src/ec_conf.c:load_conf:294]

**Comment by LocutusOfBorg** [comment]
remove the one you built from scratch maybe?

**Comment by Aco465** [comment]
> remove the one you built from scratch maybe?
@koeppea 

i fixed the issue myself but i got a new issue this comes up 
ettercap 0.8.4-rc copyright 2001-2020 Ettercap Development Team

Listening on:
  eth0 -> 07:00:21:A9:1F:33
          10.0.4.17/258.257.256.0
          fa46::a04:25ff:fra6:1f45/54

Privileges dropped to EUID 65534 EGID 65534...

  34 plugins
  42 protocol dissectors
  56 ports monitored
28230 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services

Randomizing 255 hosts for scanning...
Scanning the whole netmask for 255 hosts...
* |==================================================>| 100.00 %

Scanning for merged targets (1 hosts)...

* |==================================================>| 100.00 %

3 hosts added to the hosts list...

ARP poisoning victims:


 GROUP 2 : ANY (all the hosts in the list)
Starting Unified sniffing...


Text only Interface activated...
Hit 'h' for inline help
THIS IS THE ISSUE
Privileges dropped to EUID 65534 EGID 65534...

**Comment by koeppea** [comment]
@Aco465 This is not an issue. It's the default behavior.
Why do you think this is an issue?

**Comment by savageprogram** [comment]
@Aco465 How did you fix the issue yourself

**Comment by koeppea** [comment]
Ettercap expects the configuration file at `/etc/ettercap/etter.conf`. This can be adjusted at compile-time or to be more precise at configuration-time using **cmake**.
However the config file can be explicitly supplied with the `-a` or `--config` parameter.

I think this issue can be closed now.

**Comment by savageprogram** [comment]
So how should I edit it in the config file

**Comment by koeppea** [comment]
Search for etter.conf: `find / -name etter.conf 2>/dev/null`.
Assume etter.conf has been found at `/usr/local/etc/ettercap/etter.conf`.
Then start Ettercap (pretending you start Ettercap using the GUI): `sudo ettercap -G --config usr/local/etc/ettercap/etter.conf`

**Comment by savageprogram** [comment]
Got it, thanks!
