### ISSUE TITLE
Inject() does not work!!!!

### ISSUE THREAD

**Issue by Raphabarata** [Ettercap/ettercap#1118]
Hi, I am having a similar issue to https://github.com/Ettercap/ettercap/issues/1110 , where I have a payload for my injection and receiving the "filter engine: inject() File not found" error message. I understand this is thrown when the file itself is unreadable. I have placed the payload and filter into /tmp/ as suggested, but this does not change the error message. I am using the graphical UI. I have run this injection before with a previous version of ettercap with the other extension (*.filter) but now I am running into this issue. I would appreciate feedback.

![image](https://user-images.githubusercontent.com/65733052/114581522-64a2cf00-9c45-11eb-9ca1-d42bd9309132.png)
![image](https://user-images.githubusercontent.com/65733052/114581677-88661500-9c45-11eb-8c55-a92c77a6a467.png)

**Comment by koeppea** [comment]
The error message suggests that you've supplied the data to be injected by it's relative path `./mydata`.
Question is: relative to what?
Please try to use the absolute path in the filter source file: `/tmp/mydata`.
Don't forget to recompile the changed filter source file using **etterfilter**.
