### ISSUE TITLE
DNS Spoof Dont Work 

### ISSUE THREAD

**Issue by KokoD3veloper** [Ettercap/ettercap#1128]
Im trying to start MITM Attack in ettercap.
The dns_spoof plugin doesn't work although I get no errors.
![image](https://user-images.githubusercontent.com/63654629/122918093-47c5fe80-d34e-11eb-9697-bd37da4eeb40.png)
![image](https://user-images.githubusercontent.com/63654629/122918152-58767480-d34e-11eb-8154-371840eb1fe7.png)

**Comment by koeppea** [comment]
Can you please run ettercap with -w set to a file location where nobody can write e.g. /tmp/packets.pcap 
And share the pcap file? I’d like to see what’s going on on the wire.

**Comment by KokoD3veloper** [comment]
I think the error is due to phone cookies, I cleared the history and dns spoof started working again

**Comment by koeppea** [comment]
Great to hear. So the issue can be closed?
