### ISSUE TITLE
MAKE PROBLEM , PLEASE HELP ME :(

### ISSUE THREAD

**Issue by Danendraa** [Ettercap/ettercap#1134]
When i do cmake , cmake progress if fully completed and there is nothing problems . But when i Do make command. I got this error message : 

 error: invalid use of incomplete typedef ‘X509_EXTENSION’ {aka ‘struct X509_extension_st’}

Please tell me how to solve this problem ..

**Comment by Danendraa** [comment]
Here are the full Error Message :

[ 19%] Built target ec_interfaces
[ 19%] Built target libnet
[ 19%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o
/root/Downloads/ettercap-0.8.2/src/ec_sslwrap.c: In function ‘sslw_create_selfsigned’:
/root/Downloads/ettercap-0.8.2/src/ec_sslwrap.c:978:13: error: invalid use of incomplete typedef ‘X509_EXTENSION’ {aka ‘struct X509_extension_st’}
  978 |          ext->value->data[7] = 0xe7;
      |             ^~
/root/Downloads/ettercap-0.8.2/src/ec_sslwrap.c:979:13: error: invalid use of incomplete typedef ‘X509_EXTENSION’ {aka ‘struct X509_extension_st’}
  979 |          ext->value->data[8] = 0x7e;
      |             ^~
make[2]: *** [src/CMakeFiles/lib_ettercap.dir/build.make:667: src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:474: src/CMakeFiles/lib_ettercap.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by koeppea** [comment]
You are most probably using a OpenSSL compatible replacement library. But Ettercap relies on features only OpenSSL library is providing. Please provide more details on the ssl library used to compile your version of Ettercap.

**Comment by Danendraa** [comment]
Hello koeppea , thankyou for answering my problems.

But i want to ask , how to i see the details on the ssl library  in my linux computer ?

**Comment by Danendraa** [comment]
> You are most probably using a OpenSSL compatible replacement library. But Ettercap relies on features only OpenSSL library is providing. Please provide more details on the ssl library used to compile your version of Ettercap.

 
Hello koeppea , thankyou for answering my problems.

But i want to ask , how to i see the details on the ssl library in my linux computer ?

**Comment by koeppea** [comment]
Delete the built directory, re-create it, then change into the newly created built directory and run 

cmake -DCMAKE_BUILD_TYPE=Debug ..

Paste the output of this command. In addition it creates a file in that directory called CMakeCache.txt . Please attach that file as well.

**Comment by Danendraa** [comment]
Ok I will try it , please wait :)

**Comment by LocutusOfBorg** [comment]
Also, ettercap 0.8.2 might not have the openssl 1.1 code compatibility fixes? better use 0.8.3.1...

**Comment by Danendraa** [comment]
> Also, ettercap 0.8.2 might not have the openssl 1.1 code compatibility fixes? better use 0.8.3.1...

Hello koeppea and Locutus of borg , Thankyou for answering . Now the problems is fixed . I changed the ettervap version 0.8.2 to 0.8.3.1 . and after i change it . Its work . Thankyouu !!

**Comment by koeppea** [comment]
Glad that the new version fixed the issue. Closing
