### ISSUE TITLE
help please GTK ERROR ettercap

### ISSUE THREAD

**Issue by lilshako1** [Ettercap/ettercap#1140]
sudo -E ettercap -G                                                                                

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

GTK support is not compiled in ettercap

**Comment by koeppea** [comment]
﻿I guess you installed a -text-only package from your distribution.

You have to install the -graphical package.

Cheers

Von meinem iPhone gesendet



Von meinem iPhone gesendet

**Comment by lilshako1** [comment]
Package ettercap-graphical is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ettercap-graphical' has no installation candidate


look what that give me

**Comment by koeppea** [comment]
What is your operating system?

**Comment by lilshako1** [comment]
kali linux from termux

**Comment by LocutusOfBorg** [comment]
Should be there, maybe you need some apt-get update on your apt cache?

**Comment by veereshgadige** [comment]
Install this sudo apt-get install ettercap-graphical
enter this command -->  ettercap -G

**Comment by koeppea** [comment]
Thanks for your comment. However I think this issue has gone stale. Hence closing it. Feel free to reopen if the issue is still present.

**Comment by saffkoo** [comment]
soo i have the same problem and i do them itssss woorkkk thhxx bro 

Install this sudo apt-get install ettercap-graphical
enter this command --> ettercap -G
