### ISSUE TITLE
nmap error please help

### ISSUE THREAD

**Issue by lilshako1** [Ettercap/ettercap#1141]
$sudo nmap -O <target ip>

nmap: netutil.cc:3190: int route_dst_netlink(const sockaddr_storage*, route_nfo*, const char*, const sockaddr_storage*): Assertion `p != NULL' failed.
Aborted

**Comment by LocutusOfBorg** [comment]
mmm this is ettercap project not nmap?
maybe https://github.com/nmap/nmap is a better place to ask for help
