### ISSUE TITLE
Ettercap does not work in the docker container. 

### ISSUE THREAD

**Issue by AlirezaDehlaghi** [Ettercap/ettercap#1144]
The Problem is that it is impossible to run Ettercap in the docker containers. At least I am getting the following error:

ERROR : 30, Read-only file system
[/build/ettercap-TFupjX/ettercap-0.8.3/src/os/ec_linux.c:disable_ipv6_forward:124]

failed to open /proc/sys/net/ipv6/conf/all/forwarding

**Comment by koeppea** [comment]
Well it relies on a Linux as an operating system.

When you run a the minimal Linux footprint incl. the required dependency 
libraries in a container it should work.

**Comment by AlirezaDehlaghi** [comment]
Thanks for your answer.
I found that   creating container in docker container with  "privileged: true" will solve the issue.

**Comment by koeppea** [comment]
Thanks for providing the solution
