### ISSUE TITLE
GTK3 failed to initialize. Is X running

### ISSUE THREAD

**Issue by ghost** [Ettercap/ettercap#1148]
Dear all,

Just to inform you that during installation I've had this message :

`-- No GTK_BUILD_TYPE defined, default is GTK3
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (GTK3_GTK)
  does not match the name of the calling package (GTK3).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindGTK3.cmake:546 (find_package_handle_standard_args)
  cmake/Modules/EttercapLibCheck.cmake:48 (find_package)
  CMakeLists.txt:106 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.`

And, when I wanted to launch the program, 

`ettercap -G`

I got the following message:

`Unable to init server: Could not connect: Connection refused
GTK3 failed to initialize. Is X running?`

Any idea ?
Thanks for your help.
Regards,
Christophe.

**Comment by ToOlUsERNeWbie0** [comment]
I can't solve this error too. I really want to know which part is missing for me. If you have time, please help me for solve this error.
++>
root@kali:~# ettercap -G

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team


GTK3 failed to initialize. Is X running?

root@kali:~#

**Comment by gtasb** [comment]
> I can't solve this error too. I really want to know which part is missing for me. If you have time, please help me for solve this error. ++> root@kali:~# ettercap -G
> 
> ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team
> 
> GTK3 failed to initialize. Is X running?
> 
> root@kali:~#

I get same problem. I installed xorg.

**Comment by koeppea** [comment]
@ToOlUsERNeWbie0 , @gtasb This is probably a known issue outside Ettercap. But we're having a [Wiki article](https://github.com/Ettercap/ettercap/wiki/X-DISPLAY-issue-with-sudo) how to fix that.

**Comment by BrunoThums** [comment]
> @ToOlUsERNeWbie0 , @gtasb This is probably a known issue outside Ettercap. But we're having a [Wiki article](https://github.com/Ettercap/ettercap/wiki/X-DISPLAY-issue-with-sudo) how to fix that.

Thank you! Easy solution!
Spoiler -> Run `xhost local:root` then try executing again `sudo ettercap -G`
