### ISSUE TITLE
DNS_Spoof don't redirect

### ISSUE THREAD

**Issue by calilkhalil** [Ettercap/ettercap#1165]
Guys,

I don't know what I'm doing wrong. But I have an assumption about my ettercap.dns file.

I'm working on a new Kali Linux and trying to use ettercap.

I do these steps:
echo 1 > /proc/sys/net/ipv4/ip_forward
setoolkit to clone a website
mousepad /etec/ettercap/etter.dns (and I change the site and IP to redirect)
mousepad /etec/ettercap/etter.conf (to change ports to 0 and enable iptables commands)

When I've done these steps, I open ettercap, select targets, enable dns_spoof and enable arp spoof.

Ready, but when I access the url (which I cloned) it does not redirect to the fake site.

I think the problem is in my ettercap.dns file as the problem is with the redirect. When I access my ip 192.160.0.X in HTTP, I can access the fake website. The problem is with the DNS.

What am I doing wrong? Can someone help me?

**Comment by koeppea** [comment]
Hi,
I assume you use Windows as the victim. You have to clear the DNS cache before using `ipconfig -flushdns`.
Which ports you've changed to 0 ???
With this little detail information, it's like looking into a glass ball.

Best is, when you can provide the debug log and a packet capture. See our [Wiki article](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information).

At minimum, we need the output of Ettercap in Text-Mode and the content of the two mentioned files to get a rough idea what you did.

**Comment by Kadir-NONX** [comment]
Hi @koeppea. 

Yes, i'm trying with a Windows as the victim. I'll try clear the DNS cache.

**Comment by Kadir-NONX** [comment]
@koeppea 

I running ipconfig -flushdns, and i can see now the DNS_Spoof logs on GUI. 

Evidence:
dns_spoof: A [facebook.com] spoofed to [192.168.0.26] TTL [3600 s]

But, the request still going to original website. 

[etter.dns.txt](https://github.com/Ettercap/ettercap/files/7981839/etter.dns.txt)
[conf ettercap.txt](https://github.com/Ettercap/ettercap/files/7981840/conf.ettercap.txt)

**Comment by koeppea** [comment]
From the provided files I can see, that the version of ettercap is not the most recent one. Kali provides version 0.8.3.1 which is the latest release.

Please also consider the wiki link I provided above.

**Comment by Kadir-NONX** [comment]
@koeppea i'm trying with latest release, but without success.

I'll download all dependencies necessary to build Ettercap from source, and test again.


[ettercap conf.txt](https://github.com/Ettercap/ettercap/files/7987139/ettercap.conf.txt)
[ettercap dns.txt](https://github.com/Ettercap/ettercap/files/7987140/ettercap.dns.txt)

**Comment by koeppea** [comment]
Yes we'll need the debug log and the packet capture to reconstruct what happens.

**Comment by Naughty-SEC** [comment]
> Yes we'll need the debug log and the packet capture to reconstruct what happens.

I got some problem like him on Kali 2022.2 Ettercap v0.8.3.1. and my ettercap.conf & ettercap.dns same setting like him with different domain.

**Comment by Naughty-SEC** [comment]
this is my debug file. hope this can help developer. my dns_plug config set to domain g0*gle
[ettercap_debug.txt](https://github.com/Ettercap/ettercap/files/9164444/ettercap_debug.txt)

**Comment by koeppea** [comment]
@Naughty-SEC I went through your debug log file.

Ettercap has seen multiple DNS packets but at a time where the dns_spoof plugin wasn't yet started.

To check if the dns_spoof plugin works, you can issue the following command on the victim machine:
`nslookup www.google.com 192.168.1.1`
This way you enforce a DNS and should see that you get the expected response from dns_spoof plugin (ARP poisoning enable before of course).

I've also seen that you've enabled IPv6 in your network. When you use ARP poisoning only, you have to be sure, the victim machine is using an IPv4 address for Name resolution.

**Comment by Naughty-SEC** [comment]
> @Naughty-SEC I went through your debug log file.
> 
> Ettercap has seen multiple DNS packets but at a time where the dns_spoof plugin wasn't yet started.
> 
> To check if the dns_spoof plugin works, you can issue the following command on the victim machine: `nslookup www.google.com 192.168.1.1` This way you enforce a DNS and should see that you get the expected response from dns_spoof plugin (ARP poisoning enable before of course).
> 
> I've also seen that you've enabled IPv6 in your network. When you use ARP poisoning only, you have to be sure, the victim machine is using an IPv4 address for Name resolution.

I have turn it ON. and when check on "arp -a" on terminal my victim has changed to my dns or subnet. I dont know what is name

**Comment by Naughty-SEC** [comment]
I don't know why but this is working for me, I think this is just a problem with SSL certificates and modern browser cache. Different ways if we return to 4 years ago. With the same settings but I chose all the hosts that appeared on Ettercap, adding all of them to Target 1 and not for Target 2. and run ARP Poisoning. And to the target browser I have to delete cache browser first. If not, the DNS spoofing doesn't work

**Comment by koeppea** [comment]
I recommend you reading our [Wiki Article regarding HSTS](https://github.com/Ettercap/ettercap/wiki/HTTPS-and-HSTS).
Especially the big famous websites are strongly secured using the new Browser/Webserver standards.

Have you now tested with nslookup as I told you to see if dns_spoof works or not?

**Comment by NobelCodes** [comment]
koeppea im having the same issues can you please help me my gmail is nobeltadele.official@gmail.com

> I recommend you reading our [Wiki Article regarding HSTS](https://github.com/Ettercap/ettercap/wiki/HTTPS-and-HSTS). Especially the big famous websites are strongly secured using the new Browser/Webserver standards.
> 
> Have you now tested with nslookup as I told you to see if dns_spoof works or not?
koeppea im having the same issues can you please help me my gmail is nobeltadele.official@gmail.com

**Comment by koeppea** [comment]
@NobelCodes If you have a issue with the DNS spoof plugin, please open a dedicated issue including required information to describe the issue so that I can understand.
Since @calilkhalil haven't ever returned with the required output of `nslookup` to prove whether or not DNS Spoof plugin worked or not, I'm closing this issue now.
