### ISSUE TITLE
Kali Linux issue with ettercap -G

### ISSUE THREAD

**Issue by ignacio0821** [Ettercap/ettercap#1175]
sudo ettercap -G

receive following error:
sudo ettercap -G

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

GTK3 failed to initialize. Is X running?

**Comment by koeppea** [comment]
Please follow the instructions on our [Wiki page](https://github.com/Ettercap/ettercap/wiki/X-DISPLAY-issue-with-sudo).

**Comment by ignacio0821** [comment]
Thank you for the fast reply. Yes I have tried that listed solution but that did not correct the issue.

**Comment by LocutusOfBorg** [comment]
$ ettercap-pkexec -G
does it work?

**Comment by ignacio0821** [comment]
no it does not, I went back and reviewed my steps I think I am having problems with dependencies

sudo apt-get install ettercap-common ettercap-graphical
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ettercap-common is already the newest version (1:0.8.3.1-6).
ettercap-graphical is already the newest version (1:0.8.3.1-6).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 kali-anonsurf : Depends: secure-delete but it is not going to be installed
                 Depends: i2p but it is not installable
                 Recommends: gtkdialog but it is not installable
                 Recommends: gufw but it is not going to be installed
 libjetty8-java : Depends: libservlet3.0-java but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by LocutusOfBorg** [comment]
no, ettercap dependencies are already fine.

**Comment by LocutusOfBorg** [comment]
what does the pkexec command do? Do you have wayland or X?

**Comment by viky88** [comment]
您好,您的邮件我已经收到.

**Comment by ismailstore** [comment]
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by koeppea** [comment]
> E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
> 

Sorry but this doesn't look like a issue with ettercap itself rather than a issue with the packaging.

I even think, that your system is kind of messed up.

But you're better off opening a case with the bug report system of the Kali package.

Regards
