### ISSUE TITLE
Traffic on Layer 2

### ISSUE THREAD

**Issue by IRicI** [Ettercap/ettercap#1180]
Hi i am trying to use Ettercap to manipulate layer 2 traffic (profinet) so the components are only communicating via Ethernet (Mac). So when I am using Ettercap I can’t see the traffic when they are communicating. Can Ettercap only work on layer 3 (IP) or am I doing something wrong?

**Comment by koeppea** [comment]
When you have two network interfaces, you can run Ettercap in bridge mode.
When you only have one network interface, you can only do Unified sniffing which implies Layer 3 MITM.

**Comment by IRicI** [comment]
Thanks for the fast answer
