### ISSUE TITLE
Run scan attack without requesting user input

### ISSUE THREAD

**Issue by AlirezaDehlaghi** [Ettercap/ettercap#1187]
Running scan attack using 'sudo -S ettercap -Tq -Q   --save-hosts $2 -i eth0', finally shows some massage which says, press H for the hint.

As I am running ettercap in an automated bash script, so this request of input hinders execution for the rest code.  
I tried all available solutions, but nothing works on that.

**Comment by koeppea** [comment]
pls. paste here the full output incl. the command here.
The information you provided are even not enough for a wizard....

**Comment by koeppea** [comment]
Feel free to re-open if you want to continue and provide the requested information
