### ISSUE TITLE
Segmentation Fault during ARP poison

### ISSUE THREAD

**Issue by tro11s1ayer** [Ettercap/ettercap#1194]
Segmentation Fault during ARP poisoning

Reports attached contain frame, register, backtrace and disassembly.
core-4047773 contains a core dump immediately before the crash.
ettercapCoreDump-4047773 contains a core dump after startup.

[core-4047773.zip](https://github.com/Ettercap/ettercap/files/9378695/core-4047773.zip)
[ettercapCrashReport-08-18-2022.txt](https://github.com/Ettercap/ettercap/files/9378677/ettercapCrashReport-08-18-2022.txt)
[ettercapCoreDump-4047773.zip](https://github.com/Ettercap/ettercap/files/9378707/ettercapCoreDump-4047773.zip)

**Comment by koeppea** [comment]
Hi, unfortunately the core fire has no debug symbols from ettercap included.
This makes it next to impossible to trace the reason of the segmentation fault.
Please follow the instructions on our [Wiki page](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) regarding the provision of debug information.
Please upload a core fire with included debug symbols from Ettercap.

Thanks.

**Comment by tro11s1ayer** [comment]
Will recompile with symbols and post new crash report

**Comment by tro11s1ayer** [comment]
I simply forgot to load the symbol-file /usr/bin/ettercap after starting gdb -- will submit the crash report after the next segmentation fault.

**Comment by tro11s1ayer** [comment]
Cmake didn't output symbols to binary

**Comment by tro11s1ayer** [comment]
Voila!  Here is the report:
[ettercapCrashReport-08-19-2022.txt](https://github.com/Ettercap/ettercap/files/9386222/ettercapCrashReport-08-19-2022.txt)

Here is the link to the core dump (41MB archive exceeds the 25MB capacity here):
https://drive.google.com/file/d/15rsp45eFyEjoFmpnQYuS1j8JBLOKXdjE/view?usp=sharing

(Let me know if the drive link doesn't have adequate permissions for download)

**Comment by tro11s1ayer** [comment]
Here is the crash report:
[ettercapCrashReport-08-19-2022.txt](https://github.com/Ettercap/ettercap/files/9386235/ettercapCrashReport-08-19-2022.txt)

Here is the core dump:
https://drive.google.com/file/d/1URnJ1pB_j_DgVJUnKgvDx9wMFRZx2Cl5/view?usp=sharing
(Let me know if the drive link is inadequate for download.)

**Comment by tro11s1ayer** [comment]
Sorry I sent the wrong core file again
This is the right one
https://drive.google.com/file/d/1WSTDyfXhyAvBbILTRDGyx5Z0IRvrlDRt/view?usp=sharing
