### ISSUE TITLE
Error 90: message too long in bridged mode (Ettercap 0.8.3.1)

### ISSUE THREAD

**Issue by kahays** [Ettercap/ettercap#1195]
I'm running Ettercap 0.8.3.1 in bridge mode on a Raspberry Pi 3B, sitting between a switch and a receipt printer, and I'm running into errors of the type
```
ERROR : 90, Message too long
[.../ettercap/src/ec_send.c:send_to_iface:151]

libnet_write 2962 (-1): libnet_write_link(): only -1 bytes written (Message too long)
```
with 100% reproducibility when attempting to print a receipt.

Ettercap is run as `sudo ettercap -Tq -i eth0 --bridge eth1`. I've attached a PCAP file captured by running `sudo ettercap -Tq -i eth0 --bridge eth1 -w 20220819-minimal-reproduce-message-too-long.pcap`.

Please let me know what other information could be helpful :)

**Comment by kahays** [comment]
I apologize, I forgot to attach the file earlier.
[20220819-minimal-reproduce-message-too-long.pcap.zip](https://github.com/Ettercap/ettercap/files/9384547/20220819-minimal-reproduce-message-too-long.pcap.zip)

**Comment by koeppea** [comment]
Hi,
Thanks for the information.
I checked the PCAP file.

The problem really seem to be, that the last packet in the PCAP file has a raw length (2962 bytes) which exceeds the capability of the transmitting interface. --> MTU

Can you please paste the output of the command `ifconfig` or `netstat -ei` or `ip link`?

The full TCP handshake as well as the MTU setting of the sending device (with IP 192.168.192.18) would also be interesting to see.

**Comment by kahays** [comment]
Thank you for the reply, the default MTU of 1500 definitely was the issue here. `ifconfig eth0` and `ifconfig eth1` had the following lines:
```
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
eth1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
```
`netstat -ei` and `ip link` showed similarly.

I didn't have access to confirm, but internet search suggested the default MTU for the switch is 9578. Changing the MTU to 9000 for both interfaces on the Pi resolved the problem.

Sorry about the spurious bug report, I'm new to ettercap sniffing and appreciate your help :) I'll go ahead and close this issue later today unless there is anything you'd like to dig into further.
