### ISSUE TITLE
Cant make build

### ISSUE THREAD

**Issue by Azrael1980** [Ettercap/ettercap#1197]
CMake Warning:
  Ignoring extra path from command line:

   "/home/kali/ettercap/build/ENABLE_PDF_DOCS=On"

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning (dev) at /usr/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (GTK3_GTK)
  does not match the name of the calling package (GTK3).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindGTK3.cmake:546 (find_package_handle_standard_args)
  cmake/Modules/EttercapLibCheck.cmake:48 (find_package)
  CMakeLists.txt:106 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CURL support requested. Will look for curl >= 7.26.0
-- GeoIP support requested. Will look for the legacy GeoIP C library
-- Checking for one of the modules 'geoip'
-- Could NOT find GEOIP (missing: GEOIP_LIBRARY GEOIP_INCLUDE_DIR) 
CMake Error at cmake/Modules/EttercapLibCheck.cmake:214 (message):
  GeoIP not found!
Call Stack (most recent call first):
  CMakeLists.txt:106 (include)

-- Configuring incomplete, errors occurred!
See also "/home/kali/ettercap/build/CMakeFiles/CMakeOutput.log".
See also "/home/kali/ettercap/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by LocutusOfBorg** [comment]
how do you call the cmake command?

I guess you forgot a -D parameter

**Comment by LocutusOfBorg** [comment]
cmake .. -DENABLE_PDF_DOCS=ON should work

**Comment by Azrael1980** [comment]
cd ettercap/
mkdir build
cd build
cmake DENABLE_PDF_DOCS=On ../
make
sudo make install
mkdir: cannot create directory ‘build’: File exists
CMake Warning:
  Ignoring extra path from command line:

   "/home/kali/ettercap/build/DENABLE_PDF_DOCS=On"


CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at /usr/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (GTK3_GTK)
  does not match the name of the calling package (GTK3).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindGTK3.cmake:546 (find_package_handle_standard_args)
  cmake/Modules/EttercapLibCheck.cmake:48 (find_package)
  CMakeLists.txt:106 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CURL support requested. Will look for curl >= 7.26.0
-- GeoIP support requested. Will look for the legacy GeoIP C library
-- Checking for one of the modules 'geoip'
-- Could NOT find GEOIP (missing: GEOIP_LIBRARY GEOIP_INCLUDE_DIR) 
CMake Error at cmake/Modules/EttercapLibCheck.cmake:214 (message):
  GeoIP not found!
Call Stack (most recent call first):
  CMakeLists.txt:106 (include)


-- Configuring incomplete, errors occurred!
See also "/home/kali/ettercap/build/CMakeFiles/CMakeOutput.log".
See also "/home/kali/ettercap/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
[sudo] password for kali: 
make: *** No rule to make target 'install'.  Stop.

**Comment by Azrael1980** [comment]
└─$ cd ettercap/
mkdir build
cd build
cmake -DENABLE_PDF_DOCS=On ../
make
sudo make install
cd: no such file or directory: ettercap/
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at /usr/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (GTK3_GTK)                                    
  does not match the name of the calling package (GTK3).  This can lead to                                     
  problems in calling code that expects `find_package` result variables                                        
  (e.g., `_FOUND`) to follow a certain pattern.                                                                
Call Stack (most recent call first):                                                                           
  cmake/Modules/FindGTK3.cmake:546 (find_package_handle_standard_args)                                         
  cmake/Modules/EttercapLibCheck.cmake:48 (find_package)                                                       
  CMakeLists.txt:106 (include)                                                                                 
This warning is for project developers.  Use -Wno-dev to suppress it.                                          
                                                                                                               
-- CURL support requested. Will look for curl >= 7.26.0
-- GeoIP support requested. Will look for the legacy GeoIP C library
-- Checking for one of the modules 'geoip'
-- Could NOT find GEOIP (missing: GEOIP_LIBRARY GEOIP_INCLUDE_DIR) 
CMake Error at cmake/Modules/EttercapLibCheck.cmake:214 (message):
  GeoIP not found!                                                                                             
Call Stack (most recent call first):                                                                           
  CMakeLists.txt:106 (include)                                                                                 
                                                                                                               
                                                                                                               
-- Configuring incomplete, errors occurred!
See also "/home/kali/ettercap/build/CMakeFiles/CMakeOutput.log".
See also "/home/kali/ettercap/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by Azrael1980** [comment]
![изображение](https://user-images.githubusercontent.com/29340110/187465280-600ad9c8-3840-4a8c-bb45-168c1ee19dcf.png)

lol its work ) 
apt  install ettercap-text-only -y
apt install ettercap-graphical  -y
