### ISSUE TITLE
This is due to a meanwhile known issue with a newer version of libpcap

### ISSUE THREAD

**Issue by BrownRaven20000** [Ettercap/ettercap#1199]
im facing the same issue today as its my first time using ettercap and it gives me this 

sudo ettercap -T -S -i eth0 -M arp:remote /192.168.1.1// /192.168.1.107//

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

Listening on:
  eth0 -> 00:13:1A:12:GE:13
          172.17.ds.130/222.222.222
          fe80::215:5dff:fe70:ce19/64

Privileges dropped to EUID 65534 EGID 65534...

  34 plugins
  42 protocol dissectors
  57 ports monitored
28230 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
Lua: no scripts were specified, not starting up!

Scanning for merged targets (2 hosts)...

* |==================================================>| 100.00 %

0 hosts added to the hosts list...

FATAL: ARP poisoning needs a non empty hosts list.

-----------------------------------------------------------------------------

i then ran sudo ettercap -Tqslq and got this:

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

Listening on:
  eth0 -> 00:13:1A:12:GE:13
          172.17.ds.130/222.222.222
          Fh80::215:3dff:dc50:ge20/56

SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to EUID 65534 EGID 65534...

  34 plugins
  42 protocol dissectors
  57 ports monitored
28230 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
Lua: no scripts were specified, not starting up!

Randomizing 4095 hosts for scanning...
Scanning the whole netmask for 4095 hosts...
* |==================================================>| 100.00 %

1 hosts added to the hosts list...
Starting Unified sniffing...

Text only Interface activated...
Hit 'h' for inline help

Hosts list:

1)      172.17.128.1    00:13:1A:12:GE:13

Closing text interface...

Terminating ettercap...
Lua cleanup complete!
Unified sniffing was stopped.

------------------------------------------------------------------------------------------

i have no idea what im supposed to do to fix this

**Comment by koeppea** [comment]
Please describe how to re-produce. On which distribution have you experienced this?

**Comment by BrownRaven20000** [comment]
> Please describe how to re-produce. On which distribution have you experienced this?

I'm using Kali Linux on windows 11. I followed a video created by networkchuck on YouTube explaining how to use wireshark and mitm (https://youtu.be/-rSqbgI7oZM) however after typing "sudo ettercap -T -S -i eth0 -M arp:remote /routerIP// /deviceIP//" I received the error stating that the host list was empty as shown in my previous post. 

I tried sudo apt-get update, sudo apt-get upgrade, sudo apt update and sudo apt upgrade and ran the same command again and once again received the same error.

**Comment by koeppea** [comment]
The difference is, that NetworkChuck uses a native Linux on a Rasberry Pi.
How are you using Kali Linux. Using the WSL virtualization layer? Or do you use a proper hypervisor software like VMWare Workstation or VirtualBox?

**Comment by BrownRaven20000** [comment]
> The difference is, that NetworkChuck uses a native Linux on a Rasberry Pi. How are you using Kali Linux. Using the WSL virtualization layer? Or do you use a proper hypervisor software like VMWare Workstation or VirtualBox?

**Comment by BrownRaven20000** [comment]
> The difference is, that NetworkChuck uses a native Linux on a Rasberry Pi. How are you using Kali Linux. Using the WSL virtualization layer? Or do you use a proper hypervisor software like VMWare Workstation or VirtualBox?
im using WSL2 (video guide i used to set it up: https://www.youtube.com/watch?v=AfVH54edAHU)

**Comment by BrownRaven20000** [comment]
> The difference is, that NetworkChuck uses a native Linux on a Rasberry Pi. How are you using Kali Linux. Using the WSL virtualization layer? Or do you use a proper hypervisor software like VMWare Workstation or VirtualBox?

im using WSL2 (video guide i used to set it up: https://www.youtube.com/watch?v=AfVH54edAHU)

**Comment by koeppea** [comment]
With WSL2, we already got some weird ARP behaviour reported. Please use a "real" Linux installation e.g. on VirtualBox
