### ISSUE TITLE
Replace deprecated libgeoip

### ISSUE THREAD

**Issue by MatthewTingum** [Ettercap/ettercap#1202]
As of writing, [geoip-api-c](https://github.com/maxmind/geoip-api-c/tree/b539712b6bfba458c52948a99f2f612976897a41) has been deprecated.
>MaxMind will be retiring the GeoIP Legacy databases at the end of May 2022. Until then, this library will only receive critical security and bug fixes. Support for this library will end completely with the last release of the legacy GeoIP databases.
>
>We recommend that you upgrade to our GeoIP2 databases. You can read these from C using [libmaxminddb](https://github.com>/maxmind/libmaxminddb).
>
>See [our blog post](https://blog.maxmind.com/2020/06/01/retirement-of-geoip-legacy-downloadable-databases-in-may-2022/) for more >information.

**Comment by koeppea** [comment]
Thanks, I have it already on my list but haven't yet found time.

Seems I have to prioritize that now.

Thanks for the heads up.

**Comment by koeppea** [comment]
Deprecated libgeoip API replaced with libmaxminddb API in latest master
