### ISSUE TITLE
execreplace function not passing DATA.data to the STDIN of the command

### ISSUE THREAD

**Issue by dayahiman** [Ettercap/ettercap#1211]
Hi,

I am trying to send all the data to destination port to a shell script using execreplace function. Based on the its man pages, the function pass the DATA.data to STDIN of the command and use the output of the command as its output.

I want to decode that data which is a binary hex, replace some by bytes that have random values, reassemble the data and print it out.
Problem is shell script is not receiving the input DATA.data.
The pseudo code is like this:

if(dst == 123) {
execreplace("/path/to/script/decode_and_replace.sh");
}

I have also tried combination of log(), drop() and inject(). However the log file contains non-hex binary data which breaks my decoder. This might have worked if the content of the log was in HEX.

Please help.
Thanks in advance.

**Comment by dayahiman** [comment]
Hi @LocutusOfBorg,

Thanks for getting back to me.

Yes, sed works if you know what bytes to replace. 
But the problem is the bytes I want to replace are not predefined. They're random. Also you can't tell which packets they might be in. So I have to convert each DATA.data to XML format, replace the value of the target element and then reassemble the DATA.data.

**Comment by koeppea** [comment]
@dayahiman you must be careful. `DATA.data` which is used by _execreplace_ is not the same as `DECODED.data` which is used by _log_.
DATA.data contains the network headers in contrast to DECODED.data, which only contains the Layer7 payload.

Use your script and log what you get from _execreplace_ function into some files for some sample packets. I recommend one file per packet.

Inspect the content of the files using a hex-pager like `hexdump` or `hd`. Remember, it should contain the packet header bytes at the beginning.

Then test your script by feeding the dumped packet files into your script ans check if the output is what is expected (as I understood you correctly, the output will be still binary - so you're better off redirecting it again into a file and inspect it again using a hex-pager).

If you still think, _execreplace_ is still not functioning properly, please re-open this issue and provide us with an example which we're able to reproduce ourselves.

**Comment by dayahiman** [comment]
That's great feedback @koeppea. I will give it a try.

Thanks a lot.
