### ISSUE TITLE
Replacing data at a specific location within a packet

### ISSUE THREAD

**Issue by flyingcookie12** [Ettercap/ettercap#1236]
Hi there, new to ettercap filters and can't find much online regarding this.

Let's say we have a packet with the following data:
0000   28 16 a8 48 fa 76 c8 99 b2 a0 8b e3 86 dd 60 03
0010   a8 f0 05 64 06 38 26 06 47 00 00 00 00 00 00 00
0020   00 00 68 12 06 b7 **2a** 00 23 c7 51 b7 02 01

How would we target and replace the byte 2a (highlighted in bold) with a different value?

Any help would be appreciated.
Thanks

**Comment by LocutusOfBorg** [comment]
from etter.filter.examples file:
```
# some operation on the payload of the packet
if (DATA.data + 20 == 0x4142) {
   DATA.data + 20 = 0x4243;
} else {
   DATA.data = "modified";
   DATA.data + 20 = 0x4445;
}
```

**Comment by flyingcookie12** [comment]
Thanks for the info @LocutusOfBorg I implemented this and the value changed which is great. 

However, it appears that a UDP checksum is implemented as the UDP checksum value changed AFTER the packet value was replaced, therefore the packet was dropped and the change wasn't actually reflected.

Do you know how we can calculate the UDP checksum? Do we need to drop the packet? make the change and then resend it? How do we overcome a UDP checksum?

Thanks
