### ISSUE TITLE
Unified vs Bridged

### ISSUE THREAD

**Issue by flyingcookie12** [Ettercap/ettercap#1237]
Hello,

If I have 2 totally separate devices with their own interface cards, would I need to buy a switch and connect both devices to a switch in order to MITM the 2 devices? Or can this be achieved without a switch?

The end goal is to MITM the 2 devices but also modify packets with an ettercap filter.

Any help would be greatly appreciated, thanks!

**Comment by flyingcookie12** [comment]
I forgot to add that these 2 devices are communicating directly with each other

**Comment by LocutusOfBorg** [comment]
how can you be a man in the middle if you aren't phisically connected to them?
you need a switch, and if the 3 devices are connected through internet, you can use the wifi channel, or the switch that is behind your router.
But you need to be able to communicate with them, e.g. by ping
