### ISSUE TITLE
libcurl version error

### ISSUE THREAD

**Issue by Jern-Li** [Ettercap/ettercap#1241]
In `/home/Ljern/Desktop/ettercap-0.8.3.1/plug-ins/sslstrip/sslstrip.c `, there is 
```  c
#if (LIBCURL_VERSION_MAJOR < 7) || (LIBCURL_VERSION_MINOR < 26 )
#error libcurl 7.26.0 or up is needed
#endif
```
But now the newest version of `curl` is `8.4.0`, which definitely satisfies the version requirement. However, it could not pass the `if` judgement.
To solve it, try:
``` c
#if (LIBCURL_VERSION_MAJOR < 7) || (LIBCURL_VERSION_MINOR < 26 && LIBCURL_VERSION_MAJOR == 7 )
#error libcurl 7.26.0 or up is needed
#endif
```

**Comment by LocutusOfBorg** [comment]
This should be fixed on git
