### ISSUE TITLE
Filter doesnt work

### ISSUE THREAD

**Issue by matibu06** [Ettercap/ettercap#1246]
Hello, 
This is my case:
I have two machines, where im testing ettercap:
Client(attacker): 192.168.1.200
Server: 192.168.1.158

This is my filter:
```
 if (ip.src == '192.168.1.200' && ip.dst == '192.168.1.158') {
   if (ip.proto == TCP && tcp.dst == 12003) {
      if (DATA.data + 2 == "AA") {
         DATA.data + 4 = "YYZZ";
         msg("Replaced");
      }
   }
}
```
Compiled using etterfilter:
```
root@ubuntu:~/ettercap# etterfilter -o /root/ettercap/final.ef /root/ettercap/ettercap.ecf

etterfilter 0.8.3 copyright 2001-2019 Ettercap Development Team


 14 protocol tables loaded:
        DECODED DATA udp tcp esp gre icmp ipv6 ip arp wifi fddi tr eth

 13 constants loaded:
        VRRP OSPF GRE UDP TCP ESP ICMP6 ICMP PPTP PPPOE IP6 IP ARP

 Parsing source file '/root/ettercap/ettercap.ecf'  done.

 Unfolding the meta-tree  done.

 Converting labels to real offsets  done.

 Writing output to '/root/ettercap/final.ef'  done.

 -> Script encoded into 12 instructions.
```
Then I started Ettercap:
```
root@ubuntu:~/ettercap# ettercap -Tqi enp1s0 -F /root/ettercap/final.ef -M arp /192.168.1.158// /192.168.1.200//

ettercap 0.8.3 copyright 2001-2019 Ettercap Development Team

Content filters loaded from /root/ettercap/final.ef...
Listening on:
enp1s0 -> 90:1B:0E:BF:AD:7F
          192.168.1.200/255.255.255.0
          fe80::921b:eff:febf:ad7f/64

Privileges dropped to EUID 65534 EGID 65534...

  34 plugins
  42 protocol dissectors
  57 ports monitored
24609 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
Lua: no scripts were specified, not starting up!

Scanning for merged targets (2 hosts)...

* |==================================================>| 100.00 %

2 hosts added to the hosts list...

ARP poisoning victims:

 GROUP 1 : 192.168.1.158 80:00:0B:A5:1C:02

Starting Unified sniffing...


Text only Interface activated...
Hit 'h' for inline help

```
And result, on server:
```
nc -vl 12003
00AABBCCDDEE
```
On client:
```
root@ubuntu:~# nc 192.168.1.158 12003
00AABBCCDDEE
```

etterfilter printing "Replaced", but nothing is replaced. I have compiled version 0.8.3.1, but ettercap -v saying 0.8.3

**Comment by LocutusOfBorg** [comment]
Can you please try something like
DATA.data = "DEADDECAF";

**Comment by LocutusOfBorg** [comment]
or try with random function. See the examples in share directory.

**Comment by koeppea** [comment]
Something haven't worked with the ARP poisoning properly:
```

Scanning for merged targets (2 hosts)...

* |==================================================>| 100.00 %

2 hosts added to the hosts list...

ARP poisoning victims:

 GROUP 1 : 192.168.1.158 80:00:0B:A5:1C:02

Starting Unified sniffing...

```
Normally you'd see the second IP incl. MAC in GROUP 2, which isn't the case here.
I have the slight feeling, that you're actually still running on Ettercap version 0.8.3 and the compiled version 0.8.3.1 has been installed somewhere in your system where it's actually not effectively used. Or even worse, the ettercap 0.8.3.1 binary uses the 0.8.3 library.

So please read [this Wiki page](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) which gives hints to provide / analyse a problem with Ettercap.

**Comment by koeppea** [comment]
Any update?

**Comment by matibu06** [comment]
> Any update?

Hi, 
Thanks for help, 
Now i have working filter and replacing text. Difference is in my command line to start. Environment:
Attacker(VM): 192.168.1.143
Victim: 192.168.1.120
Router IP: 192.168.1.1
Target: remote host on internet
Command:
ettercap -Tqi enp0s3 -F /root/ettercap/final.ef -M arp:remote /192.168.1.120// /192.168.1.1//

And ettercap filter:
if (ip.proto == TCP) {
    if (search(DATA.data, "123")) {
        replace("123", "TEST");
        msg("Replaced");
    }
}

**Comment by koeppea** [comment]
Thanks for the update. So when I conclude, the problem was a combination of wrong IP addresses in the filter condition combined with false ARP poison targets, since the actual target isn't located in your local LAN but beyond of that. Am I summarizing this correctly - just that others read experience similar issues in future?

**Comment by matibu06** [comment]
Yes. For this filter:
```
if (ip.proto == TCP) {
      if (search(DATA.data, "123")) {
         replace("123", "TEST");
         msg("Replaced");
      }
   }
```
where:
192.168.1.120 - Victim1(sending command via nc)
192.168.1.200 or 1.2.3.4(target on internet) - Victim2(receiving command via nc)
192.168.1.143 - Attacker
192.168.1.1 - my router, default gateway
Correct command in LAN(where attacker and victims are in same LAN network):
ettercap -Tqi enp0s3 -F /root/ettercap/final.ef -M arp:remote /192.168.1.120// /192.168.1.200//

When your target is on internet(for example - 1.2.3.4), you must specify gateway as target:
ettercap -Tqi enp0s3 -F /root/ettercap/final.ef -M arp:remote /192.168.1.120// /192.168.1.1//

Of course my example with remote target changing every "123" to "TEST", regardless of the destination address(not needed for my tests)

**Comment by koeppea** [comment]
Ah this makes sense. Thanks for making this transparent.
