### ISSUE TITLE
HSTS issue

### ISSUE THREAD

**Issue by Al-Khawarizmii** [Ettercap/ettercap#1250]
Hi, I'm a novice and I've been trying to do the dns spoof for a few days now, when I use ettercap I manage to read the packages of the target machine and the dns-spoof plugin that I have set up seems to work because when I do a "traceroute" for example the dns is redirected to the expected ip, however when I open a browser with the target machine to open the site supposed to be redirected the browser (or the web server) prevents HTTP redirection, I read the article you wrote about how HSTS works. And I'd like to know if you've since found a way to circumvent that ? I've been looking for a solution for a few days but without success so far, is it still possible to perform dns spoofing on HTTPS or not at all ?

**Comment by koeppea** [comment]
I'm about to make up a new Youtube tutorial video as the second part of the SSL interception feature of ettercap where I'm going to show, how to intercept such webpages.
However it will be based on control of the victim's CA certificate trust store. W/o that control, there is still no way to circumvent this. Though there has been a talk on Defcon where they flushed out cached HSTS status from the browser making it vulnerable to omit the Strict-Transport-Security HTTP header from the initial HTTP header exchange.
