### ISSUE TITLE
Cmake trying in kali linux

### ISSUE THREAD

**Issue by mrx04programmer** [Ettercap/ettercap#1252]
it does not allow me to cmake. in kali linux, is it not possible to change CMake version?
![imagen](https://github.com/Ettercap/ettercap/assets/46001898/347dd074-ef39-4c0d-a1da-59e6f2c7ce05)

**Comment by koeppea** [comment]
It appears that you try to build ettercap from the source directory. Best is that you start from scratch and have a look at the INSTALL file first.

**Comment by koeppea** [comment]
I assume building ettercap in a dedicated build directory inside as explained in the **INSTALL** file fixed the issue. If not, consider re-opening.
