### ISSUE TITLE
Problem with the host button

### ISSUE THREAD

**Issue by juandash23** [Ettercap/ettercap#1253]
Hi, I using ettercap to be able to poison the DNS of my network, the problem is that when I want to discover the hosts the button does not appear, nor can I open it with the crl+h shortcut
![Captura de pantalla -2024-05-23 14-01-03](https://github.com/Ettercap/ettercap/assets/76464758/a4d20863-65d2-4ab1-aba5-b15184987a5c)
I am connecting via WiFi with the TP-Link TL-WN722N V4 network card, and use last version parrot os
![Captura de pantalla -2024-05-23 14-01-29](https://github.com/Ettercap/ettercap/assets/76464758/cb5220c8-9e03-4017-b468-1bd24b349e16)

**Comment by LocutusOfBorg** [comment]
did you click the three buttons on top right?

**Comment by juandash23** [comment]
> did you click the three buttons on top right?

Yes, but the host option still does not appear, I thought it was my network that had a firewall but when I scanned with nmap the connected hosts did appear

**Comment by juandash23** [comment]
> Hi, this is by design. You're running ettercap in Bridge mode, actually bridging the same physical interface, which doesn't make much sense. Bridge comes from the classic Ethernet Bridge, the ancestor of today's Ethernet switches. So you bridge between two different collision domains, meaning Ethernet segmentes, but all share the same Broadcast domain, meaning subnet.
> 
> With Bridge mode (usually when bridging between two different Ethernet adapters), Host Scanning and Host list and even poisoning MITM techniques do not make sense, as with Bridge Mode MITM, you're man-in-the-middle, by network topology. Therefore, these menu buttons are intentionally not shown.
> 
> This is actually not a defect.

hello, ohhh ok thank you very much, but what happens is that when I do it without bridget ettercap it closes

**Comment by juandash23** [comment]
Thank you very much to koeppea , I already solved the problem, the problem with it closing is in /etc/ettercap/etter.conf in this line redir_command_on/off since it does not have #

**Comment by koeppea** [comment]
For doing DNS poisoning, you don't need any firewall redirects.
