### ISSUE TITLE
Installation Error on Mac

### ISSUE THREAD

**Issue by amztc34283** [Ettercap/ettercap#1263]
I am trying to install ettercap on my macbook and got the following error while install:

`
Making all in src
  CC       libnet_asn1.lo
In file included from libnet_asn1.c:56:
./common.h:52:10: fatal error: 'assert.h' file not found
`

I think the libtool is looking for the std c++ library but could not find them because the sysroot is somehow not configured correctly, does anyone know if there is a file I could add the flag or change parameters to expose the dir of the std c++ library to gcc?

**Comment by koeppea** [comment]
Have you checked / followed the wiki article what dependencies have to be installed on Mac?

**Comment by amztc34283** [comment]
Thank you for reminding.

Here are some resources for anyone wanting to install on Mac:
1. https://github.com/Ettercap/ettercap/blob/master/INSTALL
2. https://github.com/Ettercap/ettercap/commit/40534662043b7d831d1f6c70448afa9d374a9b63
3. https://stackoverflow.com/questions/17360635/glibconfig-h-no-such-file-or-directory

Worth mention that the INSTALLATION section on README.md does not have the make after cmake.
