### ISSUE TITLE
Provide a summary of build-time features

### ISSUE THREAD

**Issue by justfalter** [Ettercap/ettercap#166]
At the end of running "cmake ..", I want to see something like the following, just prettier:

```
Features:
  Curses UI (ENABLE_CURSES): Off
  GTK2 UI (ENABLE_GTK): On
  IPv6 (ENABLE_IPV6): Off
  SSL (ENABLE_SSL): On
  Plug-ins (ENABLE_PLUGINS): On
  Use System Libraries (SYSTEM_LIBS): On
  Use System Curl (SYSTEM_CURL): On
  Use System Libnet (SYSTEM_LIBNET): Off
  Use Bundled Libraries (BUNDLED_LIBS): On
  Use Bundled Curl (BUNDLED_CURL): On
  Use Bundled Libnet (BUNDLED_LIBNET): On

Libraries:
  Libnet (1.1.6): Bundled
  Curl (7.26.0): /usr/lib/libcurl.so
  bla
  bla
```

We might be able to use cmake's FeatureSummary module (http://www.cmake.org/cmake/help/v2.8.2/cmake.html#module:FeatureSummary) to summarize what stuff is enabled/disabled.

**Comment by tfarina** [comment]
Looks like this was done by https://github.com/Ettercap/ettercap/commit/b2ebd21d27420f3c48fab775b75667b6de3f74ee

**Comment by koeppea** [comment]
Thanks for the hint. Closing this issue then.
