### ISSUE TITLE
CMake Error at CMakeLists.txt:49 (include):   include could not find load file

### ISSUE THREAD

**Issue by akast** [Ettercap/ettercap#176]
root@kali:~/Desktop/ettercap/build# cmake ..
CMake Error at CMakeLists.txt:49 (include):
  include could not find load file:

```
CMakeFiles/os_test.cmake
```

CMake Error at CMakeLists.txt:60 (include):
  include could not find load file:

```
CMakeFiles/headers_check.cmake
```

CMake Error at CMakeLists.txt:61 (include):
  include could not find load file:

```
CMakeFiles/lib_check.cmake
```

CMake Error at CMakeLists.txt:62 (include):
  include could not find load file:

```
CMakeFiles/variable_check.cmake
```

HAVING TROUBLE BUILDING ETTERCAP? 
1. Install any missing dependencies
2. run 'make clean-all'
3. run 'cmake /root/Desktop/ettercap'

-- Configuring incomplete, errors occurred!

**Comment by elahia** [comment]
Hi,

I just get some error as yours: include could not find load file: qibuild.cmak

but i did not understand your explanation! would you please guide me in more step to step way!?
thanks for your time in advance,

**Comment by LocutusOfBorg** [comment]
is this related to ettercap? we don't have any qibuild.cmake file, and your error message seems wrong (missing an e at the end)

**Comment by koeppea** [comment]
This is a really old issue. Look at the number. It not valid anymore.

**Comment by elahia** [comment]
Yes, but it really takes my time,  is not it possible to make some guides???

Cheers,
Elahe

**Comment by koeppea** [comment]
Elahe,

the issue is closed. If you have the same issue with the current version of ettercap, feel free to open a new issue providing some details what's going wrong.
Include the detailed steps from download to build.

Please understand that we cannot ressurect a 5 year old closed issue.

Regards
