### ISSUE TITLE
Invalid UTF-8 string passed to pango_layout_set_text()

### ISSUE THREAD

**Issue by fyrak1s** [Ettercap/ettercap#192]
When I start the GTK GUI by

```
ettercap -G -d
```

And do a scan for hosts, I get multiple warnings of this:

```
(ettercap.elf:13610): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
```

EDIT: Once the GUI even froze after host scan (not sure, but I guess it was connected to this).

**Comment by 141903009** [comment]
Even i am getting the same error
Can u please help me as early as possible

**Comment by 141903009** [comment]
[calci.txt](https://github.com/Ettercap/ettercap/files/3808673/calci.txt)

**Comment by 141903009** [comment]
this was my code please help me with it
