### ISSUE TITLE
Ettercap Ncurses Bug? or I missed the point.

### ISSUE THREAD

**Issue by Pandoxie** [Ettercap/ettercap#435]
Have been playing with MITM softwares for a while. After toying with MITMPROXY, the author suggested me to ettercap to know more about multi-protocol sniffing. It is really awesome and handy. But I just found some issues with the Ncurses GUI. My platform is OSx 10.9.1 Mavericks, I uses homebrew to build the sources. 

Symptom: 

After I select MITM items eg, ARP poisoning, A parameter input box comes up and I think this is the place to type in command line parameters like  arp ([remote],[oneway]). So I just typed in remote, oneway inside the box and ARP poisoning is turned on. 
![screen shot 2013-12-21 at 23 12 42](https://f.cloud.github.com/assets/4418547/1796085/5a46bdf0-6a52-11e3-9129-ad70a92b59ac.png)

I believed that worked since no error was generated, but It turned out something was wrong.  I know this because when I tried to turn on ICMP redirecting, I typed naturally (MAC/IP) into the box. But the error came up.

![screen shot 2013-12-21 at 23 18 21](https://f.cloud.github.com/assets/4418547/1796098/274072d8-6a53-11e3-9164-44629a5ab5fd.png)

The parameters I typed in did not actually get in the system somehow, as if NOTHING was inputed! I confirmed this by looking into the router's ARP table ( I am using DDWRT) and the router was also spoofed although I specified oneway! 

So, please tell me what to do the next and Thanks a ton!

BTW, the ettercap instruction about turning on https MITM was outdated. The IPFW commanded is deprecated and pfctl is the new lover. I am new to shell programming but after some observation, I came up with the following script and it worked well.

   redir_command_on = "sh /usr/local/etc/ettercap/pf.sh %iface %port %rport"
   redir_command_off = "sh /usr/local/etc/ettercap/pfunload.sh"

pf.sh--->
# !/bin/sh

cd /usr/local/etc/ettercap/
touch EtterPF.conf
touch Ettertoken.txt
isOldItem=`cat EtterPF.conf | grep "rdr pass on $1 inet proto tcp from any to any port $2 -> localhost port $3"`
if [ -z "$isOldItem" ]; then
    printf "rdr pass on $1 inet proto tcp from any to any port $2 -> localhost port $3\n" >>EtterPF.conf
else
    printf "Old Item Found, Just Reload\n" >> EtterLog.log 2>&1
fi

Token=`cat Ettertoken.txt | grep 'Token' | awk '{ print $3 }'`
if [ -n "$Token" ]; then
    printf "Revoke Old Token: $Token\n" >> EtterLog.log 2>&1
    pfctl -a sslsniff -Fa -X $Token >> EtterLog.log 2>&1
fi
pfctl -a sslsniff -E -f "EtterPF.conf" &> Ettertoken.txt
Token=`cat Ettertoken.txt | grep 'Token' | awk '{ print $3 }'`
printf "\n\nNewly Add Token: $Token\n" >> EtterLog.log 2>&1

pfunload.sh
# !/bin/sh

cd /usr/local/etc/ettercap/
Token=`cat Ettertoken.txt | grep 'Token' | awk '{ print $3 }'`
if [ -n "$Token" ]; then
    printf "Revoke Old Token: $Token\n" >> EtterLog.log 2>&1
    pfctl -a sslsniff -Fa -X $Token >> EtterLog.log 2>&1
    printf "Flushed\n" &> Ettertoken.txt
fi

I am doing the stupid if because I found redir_command_on was executed several times at program launch. In order not to mess up with the OSx's pf load, I just did it the stupid way... Enjoy.

**Comment by sgeto** [comment]
Ghostscript dependancy was removed in https://github.com/Ettercap/ettercap/pull/839

Cheers
