### ISSUE TITLE
SSLStrip plugin on OS X not loading

### ISSUE THREAD

**Issue by julian-weinert** [Ettercap/ettercap#447]
I have the current OS X version installed using mac ports.
In my etter.conf I just uncommented the "quick and dirty" redir_command_on / off and the ec_uid and ec_gid set to zero (the default value didn't work either).

When I try to load the plugin, I get the following error message:

```
Activating sslstrip plugin...
SSLStrip plugin: bind 80 on 59272
SSLStrip: redir_command_on had non-zero exit status (127): [ipfw add set 21 fwd 127.0.0.1,59272 tcp from any to any 80 in via en1]
SSLStrip: plugin load failed: Could not set up HTTP redirect
```

**Comment by kucukkanat** [comment]
ipfw command is not available in Yosemite what can I do?

**Comment by koeppea** [comment]
Hello @kucukkanat,
AFAIK Mac OSX switched from **ipfw** to **pfctl**.

Pleae pull the latest master from git and use  the *redir_command_on* and *_off* from **FreeBSD** section.

We need anyway confirmation if this works out and if not, why as we lack Mac devices for testing.
Feel free raising a dedicated issue as this one has quite a long story which ma be misleading.

**Comment by kucukkanat** [comment]
So I need to build  from source? I have installed ettercap via macports. Shall I remove the current one I have and then build from scratch?

**Comment by LocutusOfBorg** [comment]
I think so.
there are README on the git directory explaining you how to do it

**Comment by eaescob** [comment]
No need to re-build if you're just changing the redirect command. Modifying
the ettercap configuration file should do.

Emilio Escobar    / eescobar@gmail.com
- Great spirits have always encountered
  strong oppositions from mediocre minds. -- Einstein

**Comment by koeppea** [comment]
That depends if the build includes commit 929784b1c057c78a259af5e25ea3975e5b4a639e, 610db5b7038b1ddf3e2e92c914e69ac064a547f7 and e3ab8a1b39ccad9c896e4dd9443bb60c209ae771 would also be helpful.

So I reckonthese commits are included in the 0.8.2 release.

**Comment by faizzaki212** [comment]
I installed ettercap via brew using the command "brew install ettercap --with gtk+" then everything worked perfectly. When i tried to use the the sslstrip plugin, i encountered the same problem with this guy. So what I did was remove the "#" from
 #redir_command_on = "ipfw -q add set %set fwd 127.0.0.1,%rport tcp from any to any %port in via %iface" and
#redir_command_off = "ipfw -q delete set %set
after I did that i started unified sniffing and got a new error, it says "ipfw: command not found" but the ssl strip worked

**Comment by koeppea** [comment]
Correct. Mac OS X has changed to PF since quite some time. So you need to use the ‘pf’ commands instead.

**Comment by faizzaki212** [comment]
wdym use the pf commandss?

**Comment by koeppea** [comment]
Look at the *etter.conf* file:
```bash
#---------------
#    Mac Os X
#---------------

# if you use ipfw:
   #redir_command_on = "ipfw -q add set %set fwd 127.0.0.1,%rport tcp from any to any %port in via %iface"
   #redir_command_off = "ipfw -q delete set %set"

# if you use BSD PF:
   #redir_command_on = "(pfctl -sn 2> /dev/null; echo 'rdr pass on %iface inet proto tcp from any to any port %port -> localhost port %rport') | pfctl -f - 2> /dev/null"
   #redir_command_off = "pfctl -sn 2> /dev/null | grep -v %port | pfctl -f - 2> /dev/null"
```
So you're better off using the second version of *redir_command*'s.

If you're only having the **ipfw** commands in the *Mac OS X* section, you're using an older version of Ettercap: Hint: the Command in the *FreeBSD* section are identical.
If even those are not there, look at our [Wiki page](https://github.com/Ettercap/ettercap/wiki/macosx) to compile and install the latest version of Ettercap from Github.
