### ISSUE TITLE
No buffer space available

### ISSUE THREAD

**Issue by soeethu** [Ettercap/ettercap#502]
ERROR : 105, No buffer space available
[/build/kalibuild-ettercap_0.8.0-0kali1-i386-Ef5esQ/ettercap-0.8.0/src/ec_send.c:send_arp:342]

 libnet_write (-1): libnet_write_link(): only -1 bytes written (No buffer space available)

**Comment by samofta** [comment]
I am having the same problem running ettercap in Graphical mode... When I scan for hosts it just crashes and shows me the same error in the command line.

**Comment by sgeto** [comment]
You should open a new issue after trying the latest git.
