### ISSUE TITLE
Incorrect checksum computation on 64-bit systems

### ISSUE THREAD

**Issue by git-tomc** [Ettercap/ettercap#539]
On 64-bit systems,  an incorrect checksum will be computed when data length % 4 == 2 or 3. I'm attaching two patches, one for 0.8 and one for git, that corrects that problem and also corrects the aliasing problem. The code will compile cleanly for any compiler that supports c99 and greater.

**Comment by koeppea** [comment]
@LocutusOfBorg Can this being closed?
AFAIR this already gone into master right?

**Comment by LocutusOfBorg** [comment]
yes, thanks!
