### ISSUE TITLE
Broken in OS X 10.10: IPFW

### ISSUE THREAD

**Issue by joeysapp** [Ettercap/ettercap#611]
Hi!
ipfw has been completely removed as of 10.10 and pfctl is recommended as its replacement: https://developer.apple.com/library/mac/documentation/Darwin/Reference/Manpages/man8/ipfw.8.html

Capture will start, but I'm not seeing a lot of HTTP data (passwords) that I did in 10.9. After quitting the capture, this error pops up 9 times. So both quick and dirty way and the scripted way are broken for right now! Same way as Open BSD?

 Cannot remove http redirect (command: ipfw), please edit your etter.conf file and put a valid value in redir_command_on field

**Comment by mrtuborg** [comment]
Currently, ´pfctl´ part is working, as it is for FreeBSD.

**Comment by koeppea** [comment]
#959 removes the deprecated redirect commands from etter.conf.
