### ISSUE TITLE
Sniffing with ettercap: only DHCP traffic is shown

### ISSUE THREAD

**Issue by koenvanhees** [Ettercap/ettercap#612]
Dear,

I have setup a rogue access point, and i want to sniff the traffic of the tap interface in order to e.g. harvest credentials.  
I use following ettercap command:
ettercap -T -q --log-msg /tmp/ettercap.log -i at0 /// ///

When I do this, ettercap only shows DHCP traffic.  Also, running this command always resets ip_forward to 0, while for my setup in an AP it's absolutely necessary to have it enabled.  I enable it manually after executing ettercap, but maybe it's somehow the cause of what I'm seeing?
I know I can circumvent this with the switch "-u" but if I do that, even the DHCP traffic doesn't show up.

In any case, any ideas or suggestions are welcome.

Thanks in advance!

**Comment by sgeto** [comment]
I'm going to close this. It's been four years and the issue may or may not be related to ettercap. Looks like bad iptables rules to me. Feel free to reopen.
