### ISSUE TITLE
Port forwarding on Mac OS X Yosemite (10.10)

### ISSUE THREAD

**Issue by Ra7t0r** [Ettercap/ettercap#640]
Hello.
Mac os x commands in etter.conf for port forwarding, don't work on Yosemite

   redir_command_on = "ipfw add fwd 127.0.0.1,%rport tcp from any to any %port in via %iface"
   redir_command_off = "ipfw -q flush" 

The command "ipfw" is not available on Yosemite.

**Comment by frank10gm** [comment]
There is a solution that works without adding an anchor to pf.
You have to use the following simple script
```
#!/bin/sh
(pfctl -sn; echo "rdr pass on $1 inet proto tcp from any to any port $2 -> 127.0.0.1 port $3") | pfctl -f -
```
then insert it in etter.conf
```
# for Max Os X (Yosemite):
   redir_command_on = "/path/scriptfile.sh %iface %port %rport"
   redir_command_off = "pfctl -F all -f /etc/pf.conf"
```

**Comment by koeppea** [comment]
Can you please try #685 which I created based on your proposal?

**Comment by frank10gm** [comment]
It gives parse error.
I think the command is correct, but the parser doesn't accept it. Maybe we need to check how the parser works. What do you think?

**Comment by koeppea** [comment]
Can you please rebuild in debug mode and provide me the debug log? 
Am 25.06.2015 23:26 schrieb frank10gm <notifications@github.com>:It gives parse error.
I think the command is correct, but the parser doesn't accept it. Maybe we need to check how the parser works. What do you think?

**Comment by frank10gm** [comment]
ok, i'll do it. But I also checked and I'm pretty sure the problem is execve() command.
```
# NOTE: this script is executed with an execve(), so you can't use pipes or
# output redirection as if you were in a shell. We suggest you to make a script if
# you need those commands.
```

**Comment by koeppea** [comment]
I know this comment. It has gone away as it's meanwhile supported. The fact that you can quote this comment shows that you're using a version where it is'nt supported yet. Thatswhy I asked you to try the mentioned pull request  as it's based on the latest code base from Github where such scripts are supported.
