### ISSUE TITLE
Question: Plugin User Initiated Action

### ISSUE THREAD

**Issue by overmetal61** [Ettercap/ettercap#648]
I want to write a plugin that sits in a monitoring mode and either by a keypress or loading a 2nd plugin (user initiated) enters an attack mode.   What is the best way to do this?

Possible Options:
1.UI Interface -- But I don't really see what I want here.  I tend to use text interface, so I'd like to add "a" attack.
```c
EC_API_EXTERN void ui_msg(const char *fmt, ...);
EC_API_EXTERN void ui_error(const char *fmt, ...);
EC_API_EXTERN void ui_fatal_error(const char *msg);
EC_API_EXTERN void ui_input(const char *title, char *input, size_t n, void (*callback)(void));
```

2.Create a separate monitoring & attack plugin, but I need way to pass a  List Object pointer between them.  (This seems like incorrect use of session, but I think it would work)
Create a Session Object
Store Pointer in .....    `void *data;`
Retrieve Session Object from 2nd Plugin

Any advice or interfaces I'm not familiar with?

**Comment by koeppea** [comment]
Mhh maybe it helps if we would understand the background of your question. Which attack szenario are you acutally thinking about?

**Comment by overmetal61** [comment]
koeppea,

What I was trying to do:
Activate Plugin 1  -- Sits in Monitoring Mode -- Stores its data in a SLIST (Ettercap linked list)

Currently hitting "h" key bring up help (text interface), but I was hoping to add another key, that would cause it to call a hook, that would activate an attack feature.


I figured out the following solution:
        Creating a monitoring plugin "Name"
        Creating the linked list structure.
        Creating a ec_session object --> storing the pointer to linked list in EC_Session

        Creating a attack plugin
        User activated by "P"  "Name_Attack"
        Retrieving the ec_session object  (void *data;   & recasting it)
        Reading Data from Linked List
        
Thanks for you willingness to help!
