### ISSUE TITLE
packet log file (.ecp) is not being filled when log option specified at the command line

### ISSUE THREAD

**Issue by mmaxs** [Ettercap/ettercap#650]
Here is a patch:
$ TZ=UTC0 diff -Naur src/ec_parser.c.0 src/ec_parser.c
```c
--- src/ec_parser.c.0	2015-01-27 17:01:00.000000000 +0000
+++ src/ec_parser.c	2015-01-27 21:05:43.526699150 +0000
@@ -322,7 +322,8 @@
                   
          case 'L':
 		  set_loglevel_packet(optarg);
-
+                  break;
+                  
          case 'l':
 		  set_loglevel_info(optarg);
                   break;
```
Loglevel is already being set incrementally in set_loglevel().
Without break second call of the function results in log_stop() and removing registered logging hooks.

**Comment by koeppea** [comment]
@mmaxs thanks. Good catch.
Would you mind opening a pull request? Check out our Wiki if you need some inital guidance.

**Comment by LocutusOfBorg** [comment]
Yes, really a good catch! thanks

**Comment by LocutusOfBorg** [comment]
thanks!
