### ISSUE TITLE
Messed up output from etterlog dump of the .ecp files and ettercap packet visualization

### ISSUE THREAD

**Issue by mmaxs** [Ettercap/ettercap#655]
Have you noticed how ettercap displays packets on the screen or how etterlog prints out from a .ecp log file?
Try to capture some traffic from one of the network interface ($IFACE), for example:
 # ettercap -T  --visual hex -z -u --nopromisc --iface "$IFACE" --log test.log | tee "ec.out.txt"
 # etterlog --hex test.log.ecp > "el.out.txt"
and take a look on the "ec.out.txt" and "el.out.txt" files.
 There are some issues can be observed.
* Packet payloads aren't perpended by the corresponding packet headers. Output starts from several packet payloads being printed out which headers are located further as the text goes.
* etterlog output doesn't even begin with a program banner which can be found some further from the begin among the packet dumps.
* Lines with the packet header text may be interrupted by the text of the packet payload dumps.
* There is an extra null byte after each displayed packet payload in the output when the hex dump format is chosen .

I've found the cause and will push a patch soon.

**Comment by LocutusOfBorg** [comment]
thanks! following up on the pull request :)
