### ISSUE TITLE
Ettercap 0.8.1 crashes

### ISSUE THREAD

**Issue by rfg1** [Ettercap/ettercap#659]
Ettercap 0.8.1 on FreeBSD 10.1-RELEASE crashes after printing the version number. On the Ethernet interface (ale0) the commands behave as follows:
ettercap -T -i ale0
ettercap 0.8.1 (...)
Could not open device for mtu query

ettercap -T -i ale0 -M arp /192.168.0.10// /192.168.0.1//
ettercap 0.8.1 (...)
Using ettercap on the lo0 interface makes it produce the "core dumped, submit a bug report" message.
(all were started as root)
The .core file produced after running the ale0 command:
http://s000.tinyupload.com/?file_id=26280438518705069056
Thank you for assistance. Let me know if you need any extra info.

**Comment by LocutusOfBorg** [comment]
can you please try the latest git?

there is a ton of bsd bug fixes there...

**Comment by rfg1** [comment]
Indeed, it worked! So apparently the ports version is broken. I'll let them know. Thank you!

**Comment by LocutusOfBorg** [comment]
If you can test it as much as you can you will speed up the release :)

**Comment by rfg1** [comment]
I'll do that. I guess I should follow the TODO.TEST file, or are there any other things that need to be tested in the first place?

**Comment by LocutusOfBorg** [comment]
nope, just play with it :)
