### ISSUE TITLE
MITM performance issue [FreeBSD]

### ISSUE THREAD

**Issue by rfg1** [Ettercap/ettercap#660]
Ettercap 0.8.1 on FreeBSD has packet forwarding issues.
 It is able to forward packets only on rare occassions and for a very short while. 
Usually loading a website with Ettercap running on the dedicated sniffing computer takes way over 2 minutes. 
The computer is a Core2 Duo machine with 1GB of RAM with no other software (like an X server) running. Systat confirms that it's not using the resources entirely. I have confirmed that the card is running at 100Mb/s full-duplex. 
Also, running arpspoof with tcpdump and kernel forwarding is much more efficient (no noticable delay, 100% captured credentials). The ettercap's live log is filled with TCP SA packets. 

---
Stats:

 Received packets    :  6726115
 Dropped packets     :        0  0.00 %
 Forwarded               :  3361549  bytes: 201222325

 Current queue len   : 0/104
 Sampling rate       : 450

 Bottom Half received packet : pck:  6726087  byte: 499990726
 Top Half received packet    : pck:  6723168  byte:   244028
 Interesting packets         : 99.96 %

 Bottom Half packet rate : worst:     3590  adv:    40517 p/s
 Top Half packet rate    : worst:     5001  adv:   157304 p/s

 Bottom Half throughput  : worst:   483969  adv:  3011883 b/s
 Top Half throughput     : worst:        0  adv:     5709 b/s

---
 uname -a:
FreeBSD PHI-2 10.1-RELEASE-p5 FreeBSD 10.1-RELEASE-p5 #0: Tue Jan 27 08:55:07 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by koeppea** [comment]
Have you tried the latest git? It contains alot (Free)BSD fixes.
I'm running FreeBSD on a VM and Ettercap is perforimg well.

**Comment by rfg1** [comment]
Yes, I am running the latest git, from two days ago. I've just cloned it and recompiled in debug mode just to make sure, but there's no difference.

**Comment by koeppea** [comment]
Mhh I don't have a FreeBSD installed on hardware. Could you please -w the packets going through ettercap while you're experienceing this bad performance?

**Comment by koeppea** [comment]
donno if you're still up. Maybe you want to join the IRC channel #ettercap-project. I'm always in there if online.

**Comment by Chaskel** [comment]
Any chance you're seeing that on a client sniff that DNS traffic is not returning responses? I'm not sure if this is possibly related to an issue I'm seeing, but on the October 16th build I'm using on a Raspberry Pi with IP forwarding enabled (January Raspian build) if I take the default IPTABLES accept rules and then just add the one following rule to redirect to DNSMasq on the RPi, that it either slows performance or just kills it outright: iptables -t nat -A PREROUTING -p udp --dport 53 -d 75.75.75.75 -j DNAT --to-destination 192.168.0.2.

I'm doing a oneway arp using the following sudo ettercap -P "autoadd" -qTieth0 -Marp:remote /192.168.0.1// /// 

If I use arpspoof between the one client and the gateway then I do not have the problem. If I remove the IPTABLES rule I do not have the problem either.

**Comment by koeppea** [comment]
What do Want to achieve with DNS redirect? You can use dns_spoof.

Can you please provide the debug file.

IP forwarding should not being used in parallel. I'm a bit uncertain about the environment and what you are actually doing.

**Comment by rfg1** [comment]
Okay, so I've checked it, there is no problem with DNS - resloving works just fine. I tried to wget a website, it gets stuck at "Connecting to example.com|93.184.216.34...", specifying an IP address directly changes nothing.
The -w output grew to an enormous size of nearly 500MB after just a couple minutes, so I'll just put it on google drive and send you a download link if that's fine. Also, I'll be available on irc in the evening around 7PM CET.

**Comment by koeppea** [comment]
Alright. I'll be online as well then.
I think a more interactive chat will be more effective.

**Comment by Chaskel** [comment]
I'll probably move this to a different thread or hop on IRC as well as to not interrupt this thread further but it appears I pasted one of the other syntaxes I was using with ettercap. The one that I'd like to use is this one sudo ettercap -oqTieth0 -Marp:remote /192.168.0.1// /// (as I do not want ettercap to do sniffing - I believe dnsspoof requires sniffing). Am listing here for clarification purposes but this syntax has the same issue. Now handing thread back to rfg1's issue.

**Comment by rfg1** [comment]
I think something failed on irc last night. I got kicked from the server.

**Comment by koeppea** [comment]
Have you sent me the files via email? I've checked but nothing arrived yet.

**Comment by rfg1** [comment]
Yes, I did. But I guess I'll just post the link here.
https://drive.google.com/file/d/0BwAHZYmLTVgpV2dUbi1kYUFmcUk/view?usp=sharing

**Comment by rfg1** [comment]
First I want to apologize sincerely for the incredible delay, 2015 was crazy for me, but I'll post my findings in case anyone else bumps into this problem. It turns out that it had nothing to do with ettercap. By accident I discovered that other programs that relied on layer 3 routing to be enabled suffered from similar performance issues. It turned out that natd was to blame. Disabling ipfw and natd and using the pf firewall on the system made a huge difference. So if that doesn't sound completely unreasonable, I think the issue might be marked as resolved. Thank you all for all the help I received here!

**Comment by koeppea** [comment]
Thanks for this feedback. Would it be possible to describe how you accomplished disabling these things and how to spot if they are active? 
Then we could incorporate this into the appropriate section in etter.conf as hint comments.
Am 09.01.2016 15:18 schrieb rfg1 <notifications@github.com>:First I want to apologize sincerely for the incredible delay, 2015 was crazy for me, but I'll post my findings in case anyone else bumps into this problem. It turns out that it had nothing to do with ettercap. By accident I discovered that other programs that relied on layer 3 routing to be enabled suffered from similar performance issues. It turned out that natd was to blame. Disabling ipfw and natd and using the pf firewall on the system made a huge difference. So if that doesn't sound completely unreasonable, I think the issue might be marked as resolved. Thank you all for all the help I received here!

**Comment by rfg1** [comment]
=============
This will enable ipv4 spoofing - ipv6 requires additional rules for firewall and directives in rc.conf as mentioned in comments
Disabling faulty routing:
If ipfw was enabled in /etc/rc.conf with ipfw_enable="YES":
$ sudo service ipfw stop 
It will disable kernel routing and natd automatically. If there is an error stopping natd, one can try:
$ sudo service ipfw onestop 
It is also necessary to comment out/delete ipfw_enable="YES": and natd_enable="YES" (and all other natd related entries) in /etc/rc.conf.
If there is no ipfw and only natd running, try
$ sudo service natd stop
Install pf from packages:
$ sudo pkg install pf
append:
enable_pf="YES"
gateway_enable="YES"
;ipv6_gateway_enable="YES" for ipv6 routing
to /etc/rc.conf
And finally, the sample minimal config for pf that deals with routing (/etc/pf.conf):
nat on eth0 inet from 192.168.0.0/24 to any -> eth0
;           ^input interface    ^spoofed network       ^output interface 
;Keep in mind that this needs to be placed before firewall rules;
;for ipv6 use this additionally: nat on eth0 inet6 from <subnet> to any -> eth0
Finally:
$ sudo service pf start
$ sudo sysctl net.inet.ip.forwarding=1
// sudo sysctl net.inet6.ip6.forwarding=1 for ipv6 routing
enables routing (it can also be achieved with a reboot)
=======================================

I hope this helps, sorry if it seems chaotic. I came across this solution while working on a different server setting up openvpn and nginx, and after resolving it I thought about applying it to this problem.

**Comment by koeppea** [comment]
I thought current releases don't use *ipfw* at all in favor of *pf*.
Closing this issue. Thanks, especially for the finding and this detailed description.
