### ISSUE TITLE
GeoIP support?

### ISSUE THREAD

**Issue by gvanem** [Ettercap/ettercap#676]
For my own Ettercap (MSVC-bult), I've implemented **GeoIP** database-support in Ettercap; [example](http://www.watt-32.net/misc/Ettercap-Geoip.png).

Would there be interest in adding such a thing? I would like to once again contribute to Ettercap, but It involves a lot of patches. And my knowledge of **Git** is still limited.

**Comment by LocutusOfBorg** [comment]
I like it! feel free to send them privately or through your favourite method :+1:

**Comment by gvanem** [comment]
Here is a start:
* [ec_geoip.c](http://www.watt-32.net/misc/ec_geoip.c)
* [ec_geoip.h](http://www.watt-32.net/misc/ec_geoip.h)

**Comment by koeppea** [comment]
I like it as well.
How do you determine the **WITH_GEOIP** pre-processor definition?

**Comment by LocutusOfBorg** [comment]
I guess we can add it as cmake variable, based on the detection of libgeoip-dev or equivalent

**Comment by gvanem** [comment]
@koeppea How do you determine the WITH_GEOIP pre-processor definition?

In my home-brew Makefile.Windows:
```
USE_GEOIP = 1
...
ifeq ($(USE_GEOIP),1)
  CFLAGS += -DWITH_GEOIP -I$(GEOIP_ROOT)
  ifeq ($(CC),gcc)
    EX_LIBS += $(GEOIP_ROOT)/libGeoIP.a
  else
    EX_LIBS += $(GEOIP_ROOT)/GeoIP.lib
  endif
endif
```

Please don't ask how to do this in CMake :-)
![homer-simpson-1](https://cloud.githubusercontent.com/assets/945271/7422924/55c6988e-ef91-11e4-8091-b44c382f4d07.gif)

**Comment by LocutusOfBorg** [comment]
can we please followup on #678 ?

thanks so far!
