### ISSUE TITLE
Custom TTL using dns_spoof plugin

### ISSUE THREAD

**Issue by frekky** [Ettercap/ettercap#680]
Hi

Is it possible to add an option to the etter.dns file on a per-host basis for TTL?
Currently it seems the TTL value is hardcoded, but I'm not sure how to make that changeable via etter.dns or the configuration file.

Thanks

**Comment by koeppea** [comment]
Yes it's hard coded. What's the purpose. 
I can't see the benefit.

**Comment by frekky** [comment]
Being able to change the TTL could be useful in circumstances where continuous MITMing isn't feasible, but it is necessary to maintain control over a certain host, or in situations where the default TTL of 1 hour isn't ideal for the purposes of stealthiness (for example if a target host DNS cache can't be flushed manually and there isn't any way to force it to re-query before the TTL has expired).

I'm currently working on implementing this locally, so if you think it would be a (potentially) useful feature I can create a pull request. 

Thanks.

**Comment by koeppea** [comment]
Oh you didn't mean the IP header TTL....
Yes I agree, being able to adjust the TTL could be a good thing.
You can go ahead and submit a pull request which we then can talk about.

**Comment by LocutusOfBorg** [comment]
:+1:

**Comment by LocutusOfBorg** [comment]
thanks in advance

**Comment by frekky** [comment]
Created pull request https://github.com/Ettercap/ettercap/pull/681

Hope everything works ;)

**Comment by LocutusOfBorg** [comment]
closing than this one :)
