### ISSUE TITLE
Using own variables within etterfilter

### ISSUE THREAD

**Issue by PeterPwn** [Ettercap/ettercap#692]
Hi there

I have an etterfilter, looking like this:
```
if (ip.proto == TCP && tcp.dst == 123) {
  if (search(DATA.data, "\x03\x00\x25")) {
    string old_val = DATA.data + 12;
    DATA.data + 12 = "\x00";
    msg("Write command found, value changed");
  }
}
```
Obviously it throws an error, because of the string old_val.
Is there any way I can use my own variables within etterfilter?
I just need to save a value from the payload before I change it on the fly.

Oh, and yes, i´ve tried to log the payload and that works fine, but I only need that exact value at that offset.
I´ve tried
```
log(Data.data + 12, "/tmp/payload");
```
but that doesn´t work either.
Would be so awesome if you guys could help me with that :)

Cheers

**Comment by PeterPwn** [comment]
Oh, and yes, i´ve tried to log the payload and that works fine, but I only need that exact value at that offset.
I´ve tried 

log(Data.data + 12, "/tmp/payload");

but that doesn´t work either. 

Would be so awesome if you guys could help me with that :)

**Comment by rajeshkalluri009** [comment]
Hi,
Any solution to this problem?
I got stuck in the same kind of situation.

**Comment by mnciitbhu** [comment]
As a workaround, I think this should work(I haven't tried this),

1. `log(DATA.data, '/file.log');`
2. `drop();` the packet.
3. Write a script to process the packet. And execute the script using 
`execinject("/bin/sh /file.log");`.

You can read more about above functions `man 8 etterfilter`.

**Comment by rajeshkalluri009** [comment]
Hi,
Thanks for the reply.
I did not understand, how this is a solution to the problem.
As mentioned in @PeterPwn query, i want to process/ store a value using a variable.
Ex scenario like this:
var = DATA.data+1;
var1 = var+8;
DATA.data+var1=0x20

**Comment by koeppea** [comment]
Etterfilter doesn’t provide this functionality. That was the reason why the execinject function has been introduced, to hand off the complex work to external programs.
