### ISSUE TITLE
Missing Sanity Checks/Prevent segmentation violation/fault in Ettercap 0.8.2

### ISSUE THREAD

**Issue by dogbert2** [Ettercap/ettercap#693]
Hello All,

	In reviewing code in ettercap-0.8.2, I found some calls
to malloc()/calloc() in directory 'src', file 'ec_utils.c'
in functions base64decode() and base64encode() which are
missing tests for a return value of NULL, which would
indicate failure.  Additionally, calling memset() with the
address area set to NULL will cause a segmentation fault/
violation.  The patch file below should address these issues:

```diff
--- ec_utils.c.orig	2015-08-06 10:34:58.479857447 -0700
+++ ec_utils.c	2015-08-06 10:37:51.838857447 -0700
@@ -264,6 +264,10 @@
    char *dst;
 
    *outptr = (char *)malloc(decodeLen);
+   if (*outptr == NULL) {
+      fprintf(stderr, "Unable to allocate memory for base64decode()...\n");
+      return -1;
+   }
    memset(*outptr, '\0', decodeLen);
 
    dst = *outptr;
@@ -294,6 +298,11 @@
    int i_shift = 0;
    int bytes_remaining = strlen(inputbuff);
    *outptr = (char *)malloc(bytes_remaining*4/3+4);
+   if (*outptr == NULL) {
+      fprintf(stderr, "Unable to allocate memory for base64encode()...\n");
+      return -1;
+   }
+
    memset(*outptr, '\0', bytes_remaining*4/3+4); 
 
    ret = dst = *outptr;
```
	
Comments, Suggestions, Complaints, Compliemnts? :)

I am attaching the patch file to this bug report...

Bill Parker (wp02855 at gmail dot com)

**Comment by koeppea** [comment]
Thank you very much Bill. I've created pull request #694 based on your helpful observations.

**Comment by koeppea** [comment]
#694 merged. Closing as I think now it's OK.
