### ISSUE TITLE
Ettercap Drops SU Permission to Write Files

### ISSUE THREAD

**Issue by Balloon** [Ettercap/ettercap#695]
When I use Ettercap in -G mode, I don't have permission to create files in my own plugin. And I can't even save host list to files. Both cases gave me the "no permission" error. I'm already using sudo, and it looks like Ettercap drops SU later. Is there anyway to fix that?

**Comment by LocutusOfBorg** [comment]
go on ```/etc/ettercap/etter.conf
ec_uid = 65534                # nobody is the default
ec_gid = 65534                # nobody is the default
```


setting them to 0 should make it work.

or saving the files in /tmp works too.

**Comment by koeppea** [comment]
You can as well set it to your uid and give the plugin directory write permission on this directory.

**Comment by koeppea** [comment]
Of course to be save that Ettercap doesn't run with high privileges. But If you want to intercept SSL Ettercap must run with root permission anyway as @LocutusOfBorg already mentioned.

**Comment by Balloon** [comment]
Thanks guys! Saving files to /tmp works, but I still can't edit files after changing the .conf file. I think there might be something wrong when I recompile it. But anyway I'm pretty satisfied with this temporary solution.

**Comment by koeppea** [comment]
Thanks for the feedback. So closing. If you want a more sophisticated solution it should work as we have described, however pretty highlevel as you didn't provide much detail. Feel free to reopen this issue and provide a detailed description of what you exactly do, what doesn't work and what you would expect.
