### ISSUE TITLE
Ettercap 0.8.2 (graphical) crashes after selecting network interface

### ISSUE THREAD

**Issue by ZippoRays** [Ettercap/ettercap#700]
The title really says it all, I'm running Kali 2.0 and whenever I start ettercap and select the network interface, either wlan0, eth0 or whichever, Ettercap simply closes without any trace of it.

**Comment by LocutusOfBorg** [comment]
try to run ettercap-pkexec from bash, or look at the git repository for a README.BUGS file, that tells you how to produce a good bug report, thanks!

**Comment by ZippoRays** [comment]
Hey, I was too lazy to submit the log (sorry, I was in a rush) , I managed to fix the error simply by downloading the previous version from the website, and after installing it, the newer version magically worked fine :D Thanks for offering your support anyways.

**Comment by LocutusOfBorg** [comment]
closing then :)

**Comment by puranjanprithu** [comment]
> Hey, I was too lazy to submit the log (sorry, I was in a rush) , I managed to fix the error simply by downloading the previous version from the website, and after installing it, the newer version magically worked fine :D Thanks for offering your support anyways.

https://www.ettercap-project.org/downloads.html
