### ISSUE TITLE
Filters not work!

### ISSUE THREAD

**Issue by ngodai** [Ettercap/ettercap#704]
Hi Everyone!
I am new in Ettercap. I try filter packet using this script:
if (search(DECODED.data, "dantri.com.vn")) {
	msg("testttttttt...\n");
	drop();
	kill();
}
but it does nothing. I use ettecap v0.8.2 on VMWare Kali Linux. And my network uses proxy. When I access dantri.com.vn:
Content filters loaded from /usr/share/ettercap/test.ef...
Ettercap might not work correctly. /proc/sys/net/ipv6/conf/th0/use_tempaddr is not set to 0. Privileges dropped to EUID - EGID 0...

Thank you so much!

**Comment by LocutusOfBorg** [comment]
well use_tempaddr might be the problem :)

anyway, can you please try the latest git?

**Comment by ngodai** [comment]
Hi!
I changed value in use_tempaddr is 0 and it done :)

**Comment by LocutusOfBorg** [comment]
well, reading logs helps :D

**Comment by hktalent** [comment]
docker kali linux
```
Listening on:
  eth0 -> 02:42:AC:11:00:02
	  172.17.0.2/255.255.0.0



ERROR : 30, Read-only file system
[/build/ettercap-W54WVV/ettercap-0.8.2/src/os/ec_linux.c:disable_ipv6_forward:124]

 failed to open /proc/sys/net/ipv6/conf/all/forwarding
```

**Comment by koeppea** [comment]
The error Message says it. 
/proc need to be writable.

Docker container are not supported.

**Comment by AlirezaDehlaghi** [comment]
So is it possible to sniff with ettercap on docker container at all?
