### ISSUE TITLE
Ettercap bridge mode on a gateway box not forwarding traffic

### ISSUE THREAD

**Issue by dsgz1234** [Ettercap/ettercap#706]
<blockquote class="postcontent restore ">
							I'm trying to use ettercap bridge mode on a gateway computer with two Ethernet card but when I start it the inter net on my local network stop working. Thr forwarding is disabled by ettercap.<br>
I followed all the instructions on internet on setting up the Ettercap. <br>
<br>
<a href="https://forums.kali.org/attachment.php?s=672178dc9f5c87e7194b591b61b8e82a&amp;attachmentid=161&amp;d=1381983798" title="Name:  kali-gateway.jpg
Views: 2
Size:  12.1 KB">kali-gateway.jpg</a><br>
<br>
These are my steps:<br>
1- Install Kali<br>
2- Update<br>
<br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:48px;">apt-get update
apt-get install</pre>
</div>3- Setup static ip for both interfaces eth0 (this is plugged to internet) and eth1 (this is local network)<br>
Modify this file for ip addresses <br>
/etc/network/interfaces<br>
<br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:156px;">allow-hotplug eth0
	iface eth0 inet static
        address 192.168.1.86
        netmask 255.255.255.0
        gateway 192.168.1.1

allow-hotplug eth1
iface eth1 inet static
        address 192.168.2.10
        netmask 255.255.255.0
        gateway 192.168.1.1</pre>
</div>4- forward local network eth1 (192.168.2.0/24) to public internet eth0<br>
Edit the file: <br>
/etc/sysctl.conf<br>
<br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">net.ipv4.ip_forward = 1</pre>
</div>also manually activate the forwarding<br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">echo 1 &gt; /proc/sys/net/ipv4/ip_forward</pre>
</div><br>
5- firewall table redirect:<br>
<br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:168px;">iptables -P INPUT ACCEPT
iptables -F INPUT 
iptables -P OUTPUT ACCEPT
iptables -F OUTPUT 
iptables -P FORWARD DROP
iptables -F FORWARD 
iptables -t nat -F

iptables -A FORWARD -o eth0 -i eth1 -m conntrack --ctstate NEW -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -t nat -F POSTROUTING
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE</pre>
</div>Afther these setups all my computers on local network (eth1) is connected to public (eth0), from any of my local computer I'm be able to open a web page and use internet.<br>
With wireshark I can find and track the packets and everything looks correct.<br>
<br>
I use the ettercap 0.7.6 which came with kali linux.<br>
<br>
<font size="4"><b>Test A:</b></font><br>
I read somewhere that in bridge mode we don't need to activate redir_command_on in etter.conf, so my first test was just changing the: <br>
/etc/ettercap/etter.conf<br>
<br>
Change <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:48px;">ec_uid = 65534
ec_gid = 65534</pre>
</div>To<br>
 <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:48px;">ec_uid = 0
ec_gid = 0</pre>
</div>Start ettercap test:<br>
 <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">ettercap -Tq -i eth0 -B eth1 // //</pre>
</div>As soon as ettercap starts the local network disconnected from the internet.<br>
I tried to change eth0 and eth1 in the command but no difference.<br>
 <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">ettercap -Tq -i eth1 -B eth0 // //</pre>
</div>The only way of keeping the internet in our local network is to re activate ip forward in a separate terminal<br>
<br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">echo 1 &gt; /proc/sys/net/ipv4/ip_forward</pre>
</div>It's handing the forwarding responsibility back to the kernel. It's ok if you just want to sniff on the network. But in order to use filters and change the data while it's passing, it shouldn’t go trough kernel.<br>
<br>
<font size="4"><b>Test B:</b></font><br>
I did same "Test A" but this time I activate redir_command_on in etter.conf<br>
/etc/ettercap/etter.conf<br>
Change<br>
 <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:60px;"># if you use iptables:
   #redir_command_on = "iptables -t nat -A PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"
   #redir_command_off = "iptables -t nat -D PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"</pre>
</div>To<br>
 <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:60px;"># if you use iptables:
   redir_command_on = "iptables -t nat -A PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"
   redir_command_off = "iptables -t nat -D PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"</pre>
</div>And I repeat same Test A<br>
 <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">ettercap -Tq -i eth0 -B eth1 // //</pre>
</div>Or<br>
 <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">ettercap -Tq -i eth1 -B eth0 // //</pre>
</div>Same result, as soon as ettercap starts the local internet disconnected.<br>
<br>
<font size="4"><b>Test C</b></font><br>
Creating simple filter and use in ettercap bridge mode<br>
<br>
/etc/ettercap/myfilter.txt <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:72px;">if (ip.proto == TCP &amp;&amp; search(DATA.data, "ethercap") ) {   
   replace("ethercap", "ettercap");
   msg("Correctly replaced.\n");
}</pre>
</div>Convert filter to ettercap format:<br>
 <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:48px;">cd /etc/ettercap
etterfilter myfilter.txt -o myfilter.ef</pre>
</div>Another test <br>
 <br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">ettercap -Tq -F myfilter.ef -i eth1 -B eth0 // //</pre>
</div>Same thing happens, the internet stop working on local network. If I reactivate forwarding in a separate terminal window, it will start the internet on my local network and when I open a sample website with the misspelling on it I will see the "Correctly replaced." message, but since kernel is handling the forwarding the content on the website where not corrected and actual unchanged packets were transfer to my browser.<br>
I'm looking to a way to make ettercap handling forwarding without activating it on separate terminal.<br>
Any solution to make this works.<br>
<br>
<br>
My system specs:<br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">sudo cat /etc/issue</pre>
</div>Kali GNU/Linux 1.0 \n \l<br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">sudo uname -a</pre>
</div>Linux kali 3.7-trunk-686-pae #1 SMP Debian 3.7.2-0+kali8 i686 GNU/Linux<br>
<div class="bbcode_container">
	<div class="bbcode_description">Code:</div>
	<pre class="bbcode_code" style="height:36px;">cat /proc/cpuinfo</pre>
</div>processor	: 0<br>
vendor_id	: GenuineIntel<br>
cpu family	: 15<br>
model		: 2<br>
model name	: Intel(R) Pentium(R) 4 CPU 2.00GHz<br>
stepping	: 4<br>
microcode	: 0x1e<br>
cpu MHz		: 2020.043<br>
cache size	: 512 KB<br>
fdiv_bug	: no<br>
hlt_bug		: no<br>
f00f_bug	: no<br>
coma_bug	: no<br>
fpu		: yes<br>
fpu_exception	: yes<br>
cpuid level	: 2<br>
wp		: yes<br>
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pebs bts<br>
bogomips	: 4040.08<br>
clflush size	: 64<br>
cache_alignment	: 128<br>
address sizes	: 36 bits physical, 32 bits virtual<br>
power management:<br>
<br>
<br>
Any solution to make this works.<br>
<br>
Thanks in advance
						</blockquote>

**Comment by LocutusOfBorg** [comment]
First I can tell you to use the latest git, because we made *many* improvements on that area between 0.7.6 and the latest git.

Second, can you please avoid playing with iptables? the ettercap bridged mode should do everything is necessary to setup the bridge, including the iptables, disable ip forwarding and so on.

thanks

**Comment by dsgz1234** [comment]
Thanks for the help!
I have try the latest version and you can see that:
![201509](https://cloud.githubusercontent.com/assets/14330169/9933422/57186a00-5d7d-11e5-821e-9bed9382ef1f.png)
I started a nagix at 192.168.137.1:80.
I have cleaned the iptables, but there is no tcp response.

When i stop the ettercap,i can ping the ip

**Comment by dsgz1234** [comment]
void forward_bridge_sniff(struct packet_object *po)
{
   /* don't forward dropped packets */
   if (po->flags & PO_DROPPED)
      return;

   /*
    * If the filters modified the packet len
    * recalculate it (only if some L3 decoder parsed it).
    */
   if (po->fwd_packet)
      po->len = po->L2.len + po->fwd_len;
         
   /* 
    * send the packet to the other interface.
    * the socket was opened during the initialization
    * phase (parameters parsing) by bridge_init()
    */
<h1>Maybe it didn't work?</h1>
↓↓↓↓↓↓↓↓↓↓↓↓↓
   if (po->flags & PO_FROMIFACE)
      send_to_bridge(po);
   else if (po->flags & PO_FROMBRIDGE)
      send_to_L2(po);
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
}

**Comment by LocutusOfBorg** [comment]
I don't know, you might want to put some EC_DEBUG somewhere or gdb it :)

**Comment by koeppea** [comment]
Hi

What is this "*rndis0*" interface?

> Maybe it didn't work?
This is fine. What you're trying is not what the Bridge Mode is doing.
Bridging mode means that ettercap emulates a bridge (nowadays more known as switch). That means that a bridge connects two collision domains within one broadcast domain. What you're trying to do is using the bridge mode on a L3 gateway with IP masquadering (however I do not understand ATM your setup). So not connecting two collision domain but two broadcast domains. That doesn't work this way as it isn't supposed to be.

If you want ettercap only be passive on the L3 gateway you could just avoid sniffing at startup and start ettercap in unoffensive mode.

if you want ettercap being active meaning being able to modify the traffic it becomes more complicated.
Out of the blue without having tested it ever, I could imagine getting it working the following way:
Route all traffic from the inside interface from your inside interface to a loopback or tunnel interface doing the masquadering on this path. Then start ettercap using the bridge mode between the loopback or tunnel interface and the outside interface. 
But I'm not sure if this will work in the end.

**Comment by dsgz1234** [comment]
HI,
rndis0 is a usbnet interface that has 192.168.137.0/24.AS I say,if i put the ip_forward to "1",
(echo 1 > /proc/sys/net/ipv4/ip_forward)
I can use the internet at 192.168.137.1.
Then I got a LAN which has192.168.42.0/24 for my mobilephone by wifi.

You mean that I need put the WAN and the LAN into the same IP?

I try your advice :
<blockquote>
if you want ettercap being active meaning being able to modify the traffic it becomes more complicated.
Out of the blue without having tested it ever, I could imagine getting it working the following way:
Route all traffic from the inside interface to a loopback or tunnel interface doing the masquadering on this path. Then start ettercap using the bridge mode between the loopback or tunnel interface and the outside interface. 
</blockquote>
But it didn't work!

As i know,it's a bridge like i config like that without ther ettercap on my device.
The device you can think it's a gateway?

192.168.137.1 is connect to the internet.
![mx37a95](https://cloud.githubusercontent.com/assets/14330169/9949476/bc1c9a0e-5ddf-11e5-953e-f7f586dfcb90.png)
![image](https://cloud.githubusercontent.com/assets/14330169/9949490/d9866cfa-5ddf-11e5-9a92-efde1bb2bc61.png)

then i can use the internet from the device which is on wlan0.
Can it call the bridge?
Thank you!

**Comment by dsgz1234** [comment]
By the way.I want to modify the package, but first,It should be connected. :)
If I use 
<code>
sudo ettercap -Ti wlan0 -B rndis0
</code>
I can't connect to the rndis0 from wlan0.It seems have no bridge.
Thank u!

**Comment by dsgz1234** [comment]
Does ettercap on BRIDGE mode provide the NAT or ROUTER?

**Comment by koeppea** [comment]
> Can it call the bridge?

No. It's a router performing NAT.


> Does ettercap on BRIDGE mode provide the NAT or ROUTER?

Bridge mode emulates a Bridge (see https://en.wikipedia.org/wiki/Bridging_%28networking%29). Neither a Router nor a NAT.

Ettercap is a MITM tool. So redirecting traffic through the MITM host which is not the case under normal circumstances. Two main fuctionalities achieve that:
 1. The MITM method (eg. ARP poisoning)
 2. forwarding packets between the poisoned hosts (Sniffing method e.g. unified)

As networkflows in a bridged or ARP poisened MITM szenario contradicts the Kernel Routing, it has to be switched off in such cases and ettercap has to take over packet forwarding.

Your szenario is different because you run ettercap on a node where the traffic has to traverse anyway and where Kernel Routing is valid. So ettercap must be run in unoffensive mode not being active but just listening to the traffic.

The masquerade doesn't make thing easier.

Ettercap is designed to run in front of your Linux Router as a dedicated machine. Not on your Linux Router.

**Comment by dsgz1234** [comment]
It's clear!Thank you very much!
