### ISSUE TITLE
MITM: server certificate issues

### ISSUE THREAD

**Issue by vovanec** [Ettercap/ettercap#707]
I'm using ettercap-0.8.2 on Kali-2.0. After MITM is enabled(remote arp) I'm trying to do some browsing on attacked machine using Firefox 40.0.3. I'm noticing that I cannot access ANY HTTPs site because of server certificate error. There are various errors depending on a web site I'm trying to reach:

Example 1: An error occurred during a connection to marketplace.firefox.com. Peer's certificate has an invalid signature. (Error code: sec_error_bad_signature) 

Example 2: Your certificate contains the same serial number as another certificate issued by the certificate authority. Please get a new certificate containing a unique serial number. (Error code: sec_error_reused_issuer_and_serial) 

There seems to be no any way to deal with those errors(like add exception etc) and browse further. 

Thanks,
--Vovan

**Comment by koeppea** [comment]
Please try the latest master from github.
Especially your second issue has been addressed just some days ago.
For your first issue it could be the case, that there is no (or not yet) solution.
If the *.firefox.com is built-in of the HSTS hosts cache of the browser, there is no way to circumvent this (see https://blog.mozilla.org/security/2012/11/01/preloading-hsts/). If it's not hardcoded and relies on the Strict-Transport-Security HTTPS header, there is a potential way to circumvent this. We're at the moment in progress to work on that issue as well. But at the moment, ettercap with enabled SSL interception cannot be used for HSTS protected SSL hosts.

**Comment by vovanec** [comment]
Ah, I see, thanks for the kind explanation! In fact I'm just playing with ettercap and I've been much more successful when switched to older Firefox version. For now, that's good enough for me as see how the tool works. Please feel free to close the issue.
