### ISSUE TITLE
incorrect number of token (///) in target !!

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [Ettercap/ettercap#708]
I was trying to run this command:
```
ettercap -T -i eth0 -M arp:remote /192.168.1.1/ /192.168.1.9/
```
But I had the error in the title. So I went to the man page and copied this command from the examples:
```
ettercap -T -M arp:remote /192.168.1.1/ /192.168.1.2-10/
```
And it shows the same error. So the examples themselves are not working, there's something obviously wrong. Using **Kali linux 32-bit** and **ettercap 8.2**.

**Comment by koeppea** [comment]
You are very close. Compare the token /// in the error message and your token: //. 
Your version of ettercap is just IPv6 enabled. Hence the target definition gets one more part for the IPv6 address.
If you reread the man page and not just copy & paste the examples, then you should recognise the note about the target notation implication in regard to IPv6.

**Comment by github-account-because-they-want-it** [comment]
Thank you. This command now woks:
```
ettercap -T -i eth0 -M arp:remote /192.168.1.1// /192.168.1.9//
```
I should probably nag about making the software more tolerant in this case, but it's a hacking software and bits like these are intended to fend off noobs. So keep it please.

**Comment by koeppea** [comment]
Very much appreciated.
Thank you.

**Comment by Nicryc** [comment]
Sorry to up an old topic but is it possible to disable IPv6 for ettercap and use IPv4 instead ?

**Comment by koeppea** [comment]
Maybe I don't get the point but IPv6 can be disabled completely by setting Cmake flag ENABLE_IPV6 to Off and recompile ettercap.

**Comment by blackcatlover** [comment]
@koeppea i am using vmware 12 to run kali linux 32bit, ettercap version 0.8.2   i want to run the mitm attack with nossl. so i type "ettercap -T -i -S eth0 -M arp:remote /192.168.1.1// /192.168.1.9//". But error happens, TARGET (eth0) contains invalid chars!.

HELP ME PLS

**Comment by sgeto** [comment]
@blackcatlover 
`ettercap -T -i  eth0 -S -M arp:remote /192.168.1.1// /192.168.1.9//`

**Comment by blackcatlover** [comment]
@sgeto i type it, and then i run another terminal "driftnet -i eth0" the victim is not facing the "no internet connection" error anymore, but the driftnet is still not receiving any images

**Comment by sgeto** [comment]
Sorry, I don't use driftnet.
Maybe you can't see them because the images are transferred over a secure channel/protocol or maybe driftnet just sucks.
nossl is not exactly up-to-date either

**Comment by blackcatlover** [comment]
@sgeto so what do u suggest me to do if i want to do a mitm attack to receive images of victim browsing? i face the ssl certification, and victim browser lost connection when i run the attack.

**Comment by sgeto** [comment]
wish it was that easy.
there aren't many _stealthy_ way left to sniff ssl traffic these if that's what you're after.
the few there require certain know-how and dedication.
if you don't care about whether you victim notices the interception, you might want to have a look at the `sslstip` plugin.

**Comment by HUC-jingzi** [comment]
我看了一篇文章说不指定对象，它就会劫持全局，命令为：
ettercap -i eth0 -T -M arp:remote /10.0.0.1/ //  
//所指对象为空   但是这样会导致说令牌数量不对。

**Comment by HUC-jingzi** [comment]
我看了上一篇文章说不指定对象，它就会劫持全局，命令为：
ettercap -i eth0 -T -M arp：remote /10.0.0.1/ //
//所指对象为空但是这样会导致说令牌数量不对。

**Comment by koeppea** [comment]
@HUC-jingzi Sorry my Chinese (Google Translate) is not that good.
However when IPv6 support is included at compile time, you have to use this command:
```
ettercap -i eth0 -T -M arp:remote /10.0.0.1// ///
```
If you still have issues, feel free to open a new issue (in English please).

**Comment by HUC-jingzi** [comment]
> @ HUC-jingzi对不起，我的中文（Google Translate）不好。
> 但是，在编译时包含IPv6支持时，您必须使用以下命令：
> 
> ```
> ettercap -i eth0 -T -M arp:remote /10.0.0.1// ///
> ```
> 
> 如果仍然有问题，请随时打开一个新的问题（请用英语）。

Thank you very much for your answers! With your help, it succeeded. Praise you 6666 in Chinese (very good. Very powerful)！！Thinks  very much

**Comment by TheKevinWang** [comment]
This is by far the shittiest usability I've ever seen in a cli program lol. Why can't y'all just use flags like everyone else instead of this shitty / notation? 
> You are very close. Compare the token /// in the error message and your token: //. Your version of ettercap is just IPv6 enabled. Hence the target definition gets one more part for the IPv6 address. If you reread the man page and not just copy & paste the examples, then you should recognise the note about the target notation implication in regard to IPv6.

**Comment by koeppea** [comment]
Why can't you not make a constructive concrete suggestion or even 
better, submit a enhancement - it's Open Source.

Am 23.03.23 um 23:30 schrieb TheKevinWang:
