### ISSUE TITLE
Error, ettercap/MITM/arp poisoning doesn't sniffing any router.

### ISSUE THREAD

**Issue by VirgulaHacker** [Ettercap/ettercap#711]
Hello,
I have a problem with ettercap...
On my router I want to sniff the information on different device connect to the router but it doesn't work...
I open ettercap graphical and i follow this step to sniff:
sniff->unified sniffing (on wlan0)
MITM-> Arp poisoning (sniff remote connection)

But it doesn't work.
The log is here below:
p.s I have hide my wlan0 address for privacy...
```
Listening on:
 wlan0 -> 00:C0:CA:81:9E:44
          192.168.1.102/255.255.255.0
          fe80::2c0:caff:fe81:9e44/64
 
SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to UID 0 GID 65534...
 
  33 plugins
  42 protocol dissectors
  57 ports monitored
19839 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
Lua: no scripts were specified, not starting up!
Starting Unified sniffing...
 
 
ARP poisoning victims:
 
 GROUP 1 : ANY (all the hosts in the list)
 
 GROUP 2 : ANY (all the hosts in the list)
```

What can I do to resolve this problem?
Thanks!

**Comment by koeppea** [comment]
Hi,
you mean you have hidden the MAC address 00:C0:CA:81:9E:44 of your wireless card?! :santa: 
What exactly doesn't work? 
Do you mean that the whole packet forwarding isn't working as long as ettercap runs? 
Do I understand it correctly, that ettercap runs on the router itself?

**Comment by VirgulaHacker** [comment]
When I launch, arp poisoning attack with ettercap on my router, it doesn't sniffs any http access of any page on any connected device on my router. So, what can I do to resolve this problem? That is due by thing?
Thanks and Sorry for my bad english but I'm italian.

**Comment by koeppea** [comment]
Can you create a packet capture during this situation?

**Comment by VirgulaHacker** [comment]
I haven't tried and I don't know what I have to do to create capture packet. Can you help me about the creation of a packet?
Thanks.

**Comment by koeppea** [comment]
Sorry I can't help you on that.
There is enough material in the web that covers such things.

Closing the issue for now. Feel free to reopen it once you can provide a packet capture file recorded while the issue has been reproduced. Then we can continue.

Thanks for your understanding.

**Comment by Virgula0** [comment]
Hi, i don't already understand what's happened and why ettercap didn't work, but I have reinstalled the distro of linux and of course now, it works normally.

Thanks.

**Comment by VirgulaHacker** [comment]
Hi, i don't already understand what's happened and why ettercap didn't work, but I have reinstalled the distro of linux and of course now, it works normally.

Thanks.
