### ISSUE TITLE
Connections Error

### ISSUE THREAD

**Issue by silverslayer** [Ettercap/ettercap#712]
When I open the connection tab the program closes and give this error:

BUG at [/build/buildd/ettercap-0.8.0/src/interfaces/gtk/ec_gtk_view_connections.c:gtkui_connections_add:404]

 i!=1

**Comment by koeppea** [comment]
Hi,

which version? Have you tried the latest code base from github?
If the error persists in the latest codebase, please follow the
instructions in README.BUGS.

Cheers

**Comment by LocutusOfBorg** [comment]
that line 404 with a BUG macro is only available in v0.8.0
   BUG_IF(i!=1);

**Comment by LocutusOfBorg** [comment]
so I see twice outdated, do you run ubuntu trusty?

**Comment by a211212abc** [comment]
I was also given the same error when I executed "sudo ettercap -G" and then tried to open the connection tab on my Mac OS. 
I had followed the README.OSXLION file, but the error was still there.

**Comment by koeppea** [comment]
Again, please make sure you use the latest code from github or at least version 0.8.2 which has tons of bugfixes for all the new stuff that has been introduced in version 0.8.0. As @LocutusOfBorg already mentioned, the claimed line doesn't exsist in the current code base anymore.

A little confirmation on the outcome would be appreciated.

**Comment by sgeto** [comment]
We're done here.
