### ISSUE TITLE
Replacement filter don't work

### ISSUE THREAD

**Issue by LeaklessGfy** [Ettercap/ettercap#715]
Hello guys,

I have a dumb filter and it should replace : "src=" to "adb=" (just to test if replacement is ok)
So my script is : 

```
if (ip.proto == TCP) {
replace("src=", "adb=");
msg("should be ok");
}
```

I know you guys will say : but in your if you should put : `tcp.src == 80`.

But when I do that, the condition is never trigger.

Any ideas ? I'm on version 0.8.2 on kali linux. Thanks

**Comment by koeppea** [comment]
Hi,
do you suspect this string occuring in the HTTP request or response?

**Comment by LeaklessGfy** [comment]
In the request, no of course but in the response: yup! 

The context :
I tried this filter on my network. With my laptop I perform a man in the middle against my PC. Then with my PC I open a web page containing img (and a img have src= attribute) but no change is applied on the content of the response. And img still got src= but no adb= (and of course the msg is display in ettercap).

So my question is : is it normal ? Is my router blocking it ? Is ettercap able to do that ?

(Sorry for my english I'm not English so maybe there's a lot of mistakes in my sentences)

**Comment by koeppea** [comment]
Make sure you really see the connection content in both direction.
It may be that your router isn't that trivial to poison, hence the answers from the webserver might still go directly to the victim, not passing ettercap.

Please try poisoning via cable not wireless.

**Comment by LeaklessGfy** [comment]
Okay I see the point. How can I check if I see the connection content in both direction ?
I assume that it's in wireshark but do you have a example of paquet ? 

But I think you're right and my router is not that trivial because when with my PC I want to go on Facebook or Google, page are blocked with a message like : "error with certificate, you can't go any further"

I will try tonight via cable and I keep you updated !

**Comment by koeppea** [comment]
Use the connections View in Ettercap. Double-click the connection you wan to modify. You see by default two vertical panes containing the payload of both directions.
There may be even flood scenarios where you will see content in both directions in Ettercap but the victim machine has got the same content in parallel from the router directly as it's somewhat flooded the packets. This strongly depends on the network equipment used.

**Comment by littleguga** [comment]
@LeaklessGfy so what's happened?

**Comment by LeaklessGfy** [comment]
@littleguga Seems not to work with ettercap ... or I mean work only with same length characters and not always.

Bettercap seems more up to date for Mitm but no GUI.

**Comment by koeppea** [comment]
Let us please know your experience with Bettercap. 
I'm really curious?

**Comment by LeaklessGfy** [comment]
Ettercap put the basis and is really easy to use I mean the GUI makes things easier.
But with some of my collegues Bettercap seems more powerfull.

Why ? 
First, because of those certificates : https://www.bettercap.org/blog/howto-use-bettercap-https-proxy/
And last because the integration with beef works pretty well : https://www.bettercap.org/blog/howto-bettercap-and-beef-framework/

The documentation is pretty cool. More stable too and more features comes every weeks.

**Comment by koeppea** [comment]
Sorry but for your first link I get a 404?
I'd really like being interessted to improve or even set a new direction.
