### ISSUE TITLE
Make Fails-Ettercap

### ISSUE THREAD

**Issue by xpertHands** [Ettercap/ettercap#716]
The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for sys/poll.h
-- Looking for sys/poll.h - found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sys/utsname.h
-- Looking for sys/utsname.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for arpa/nameser.h
-- Looking for arpa/nameser.h - found
-- Looking for ltdl.h
-- Looking for ltdl.h - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for libgen.h
-- Looking for libgen.h - found
-- Looking for wsyncup in /usr/lib/x86_64-linux-gnu/libcurses.so
-- Looking for wsyncup in /usr/lib/x86_64-linux-gnu/libcurses.so - found
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncurses.so
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncurses.so - found
-- Found Curses: /opt/lib/libncurses.so  
-- No GTK_BUILD_TYPE defined, default is GTK2
-- Found GTK2_GTK: /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so  
-- Found OpenSSL: /usr/local/lib/libssl.a;/usr/local/lib/libcrypto.a (found version "1.1.0") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for iconv
-- Looking for iconv - found
-- CURL support requested. Will look for curl >= 7.26.0
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (Required is at least version "7.26.0") 
-- Looking for poll
-- Looking for poll - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for select
-- Looking for select - found
-- Looking for scandir
-- Looking for scandir - found
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strlcat in bsd
-- Looking for strlcat in bsd - not found
-- Looking for strlcpy in bsd
-- Looking for strlcpy in bsd - not found
-- Looking for strsep
-- Looking for strsep - found
-- Looking for strcasestr
-- Looking for strcasestr - found
-- Looking for memmem
-- Looking for memmem - found
-- Looking for basename
-- Looking for basename - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for inet_aton
-- Looking for inet_aton - found
-- Found LIBNET: /usr/lib/x86_64-linux-gnu/libnet.so  
-- Found PCRE: /usr/lib/x86_64-linux-gnu/libpcre.so  
-- Performing Test HAVE_MUTEX_RECURSIVE_NP
-- Performing Test HAVE_MUTEX_RECURSIVE_NP - Success
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.5.39") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Desktop/aa/ettercap
root@xpertHands-PC:~/Desktop/aa/ettercap# make
Scanning dependencies of target ec_interfaces
[  0%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o
[  1%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text.c.o
[  1%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_conn.c.o
[  1%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_display.c.o
[  2%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_plugin.c.o
[  2%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/text/ec_text_profile.c.o
[  3%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/daemon/ec_daemon.c.o
[  3%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg.c.o
[  3%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_compound.c.o
[  4%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_debug.c.o
[  4%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_dialog.c.o
[  4%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_dynlist.c.o
[  5%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_error.c.o
[  5%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_file.c.o
[  6%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_input.c.o
[  6%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_list.c.o
[  6%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_menu.c.o
[  7%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_panel.c.o
[  7%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_percentage.c.o
[  7%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_scroll.c.o
[  8%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/widgets/wdg_window.c.o
[  8%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses.c.o
[  9%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_filters.c.o
[  9%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_help.c.o
[  9%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_hosts.c.o
[ 10%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_live.c.o
[ 10%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_logging.c.o
[ 10%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_mitm.c.o
[ 11%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_offline.c.o
[ 11%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_plugins.c.o
[ 11%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_start.c.o
[ 12%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_targets.c.o
[ 12%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_view.c.o
[ 13%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_view_connections.c.o
[ 13%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/curses/ec_curses_view_profiles.c.o
[ 13%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk.c.o
[ 14%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_conf.c.o
[ 14%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_filters.c.o
[ 14%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_help.c.o
[ 15%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_hosts.c.o
[ 15%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_live.c.o
[ 16%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_logging.c.o
[ 16%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_menus.c.o
[ 16%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_mitm.c.o
[ 17%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_offline.c.o
[ 17%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_plugins.c.o
[ 17%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_start.c.o
[ 18%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_targets.c.o
[ 18%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_view.c.o
[ 19%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_view_connections.c.o
[ 19%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/gtk/ec_gtk_view_profiles.c.o
[ 19%] Linking C static library libec_interfaces.a
[ 19%] Built target ec_interfaces
Scanning dependencies of target libnet
[ 19%] Built target libnet
Scanning dependencies of target lib_ettercap
[ 19%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_mem.c.o
[ 20%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_capture.c.o
[ 20%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_checksum.c.o
[ 20%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_conf.c.o
[ 21%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_connbuf.c.o
[ 21%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_conntrack.c.o
[ 21%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_debug.c.o
[ 22%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_decode.c.o
[ 22%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_dispatcher.c.o
[ 22%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_dissect.c.o
[ 23%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_encryption_ccmp.c.o
[ 23%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_encryption_tkip.c.o
[ 24%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_encryption.c.o
[ 24%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_error.c.o
[ 24%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_exit.c.o
[ 25%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_file.c.o
[ 25%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_filter.c.o
[ 25%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_fingerprint.c.o
[ 26%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_format.c.o
[ 26%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_globals.c.o
[ 27%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_hash.c.o
[ 27%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_hook.c.o
[ 27%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_inet.c.o
[ 28%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_inject.c.o
[ 28%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_log.c.o
[ 28%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_manuf.c.o
[ 29%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_mitm.c.o
[ 29%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_network.c.o
[ 30%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_packet.c.o
[ 30%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_passive.c.o
[ 30%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_plugins.c.o
[ 31%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_poll.c.o
[ 31%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_profiles.c.o
[ 31%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_resolv.c.o
[ 32%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_scan.c.o
[ 32%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_send.c.o
[ 33%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_services.c.o
[ 33%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_session.c.o
[ 33%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_set.c.o
[ 34%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_signals.c.o
[ 34%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sleep.c.o
[ 34%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sniff_bridge.c.o
[ 35%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sniff.c.o
[ 35%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sniff_unified.c.o
[ 35%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_socket.c.o
[ 36%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o
/root/Desktop/aa/src/ec_sslwrap.c: In function ‘sslw_create_selfsigned’:
/root/Desktop/aa/src/ec_sslwrap.c:1106:13: error: dereferencing pointer to incomplete type
          ext->value->data[7] = 0xe7;
             ^
/root/Desktop/aa/src/ec_sslwrap.c:1107:13: error: dereferencing pointer to incomplete type
          ext->value->data[8] = 0x7e;
             ^
src/CMakeFiles/lib_ettercap.dir/build.make:1142: recipe for target 'src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o' failed
make[2]: **\* [src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o] Error 1
CMakeFiles/Makefile2:287: recipe for target 'src/CMakeFiles/lib_ettercap.dir/all' failed
make[1]: **\* [src/CMakeFiles/lib_ettercap.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by LocutusOfBorg** [comment]
OR And Openssl versions?

**Comment by LocutusOfBorg** [comment]
Os type I mean (typo)

**Comment by xpertHands** [comment]
OS- Kali Sana
OpenSSL ver:OpenSSL 1.1.0



root@xpertHands-PC:~# cat /etc/issue
Kali GNU/Linux 2.0 \n \l
root@xpertHands-PC:~# openssl version -a
OpenSSL 1.1.0-pre3-dev  xx XXX xxxx
built on: reproducible build, date unspecified
platform: linux-x86_64
compiler: gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -pthread -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -Wall -O3 -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/openssl"

**Comment by koeppea** [comment]
Could you please try my openssl-depricates branch of my fork of ettercap?
It's somewhat quick&dirty workaround rather than a solution. But maybe it helps your out for now.

**Comment by koeppea** [comment]
this is already solved
