### ISSUE TITLE
Proper way to shutdown ettercap?

### ISSUE THREAD

**Issue by skycoder-official** [Ettercap/ettercap#717]
Every time I use ettercap in the command line (linux) and I press Ctrl + C I get this message: 
User requested a CTRL+C... (deprecated, next time use proper shutdown)

So my question: What is the proper way to shut down ettercap?

**Comment by koeppea** [comment]
Just pressig "q".
Pressing "h" prints the command shortcuts possible.

**Comment by skycoder-official** [comment]
@koeppea  Thanks a lot man!
