### ISSUE TITLE
Ettercap etter.conf file not found

### ISSUE THREAD

**Issue by uditunpluged** [Ettercap/ettercap#720]
Hi! I have installed ettercap on my mac running OS X ElCapitan using brew install ettercap --with GTK
The program is running successfully but I am unable to edit the etter.conf file.

The file is missing or somewhere in dark. Please help me in order to find this etter.conf file.

**Comment by koeppea** [comment]
Seems the configuration step didn't went well.
The location of the "etc" directory is specified with cmake.
The determined location can be found in the build directory in the
CMakeCache.txt file.
This can be edited before building.
But I don't know how it's being done with brew on a MacOSX

Alternatively you can explicitely specify it using --config parameter
when calling the ettercap binary.

**Comment by Excelsor** [comment]
Hahahahah It's not missing in the dark, it's just Alone in the Dark....

cd /usr/local/etc/ettercap
sudo nano etter.conf

Enjoy, @Excelsor

**Comment by LocutusOfBorg** [comment]
lets close it :)

**Comment by koeppea** [comment]
I confirm. With my last (and at the same timer first) test on a MacBook, I experienced absolutely no such issue. Even though my **etter.conf** was located in _/etc/ettercap/_ AFAIK.

**Comment by faizzaki212** [comment]
i dont know what to do with the ettercap.conf file, can someone help?

**Comment by koeppea** [comment]
> can someone help?

yes
 1. the file is called **etter.conf** - *not ettercap.conf*
 2. type `man etter.conf` in a terminal or use the help menu which provides the same content.

This should give you a good start.

**Comment by faizzaki212** [comment]
thx man but i still don't understand, what should i do if i want to redirect a specific website to another?

**Comment by faizzaki212** [comment]
i tried to redirect gmail.com to my laptop's apache server, then ettercap says gmail.com spoofed to 192.168.1.190 but on my victim's browser it says "Safari cannot open the page because it could not connect to the server." but the server works when i entered 192.168.1.190 in safari.

**Comment by koeppea** [comment]
Check out our wiki page about HSTS. This explains the issue.
