### ISSUE TITLE
OS X Segmentation Fault...

### ISSUE THREAD

**Issue by donald122** [Ettercap/ettercap#722]
OS X 10.11.14
Ettercap 0.8.2

Port forwarding works using pfctl. However after a few moment Segmentation Fault....
Will not happen if comment out pfctl option in etter.conf

**Comment by koeppea** [comment]
Which pfctl commands you've enabled exactly?
Can you reproduce with the latest codebase from Github?

**Comment by spyder-7** [comment]
Same here.

Running a very simple command 
"ettercap -Tq --mitm arp:remtote --interface eth0 /192.168.1.6,192.168.1.22// /192.168.1.1//"

after few seconds program ettercap simply quits saying:
Ooops ! This shouldn't happen...
Segmentation Fault...

Using Kali 2.0 With 0.8.2 ettercap

**Comment by koeppea** [comment]
@donald122 and @spyder-7 please retry using the latest code base from github.
If the issue still persists: recompile ettercap in Debug mode and provide the debug information (see the various README files).
