### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by hyp3rlinx** [Ettercap/ettercap#723]
please will appropriate person contact me for details...
apparitionsec@gmail.com

**Comment by koeppea** [comment]
any update on that? Has someone contacted you?

**Comment by LocutusOfBorg** [comment]
I didn't. There is no need to discuss in private. Is the bug so serious?

**Comment by hyp3rlinx** [comment]
No its not, just more of FYI... sorry for delay have not checked email..
seems be basic insecure DLL load in windows version I noticed. 

DLL is "quserex.dll"  open an .eci file from share and associated with
ettercap it will run that DLL.

On 2016-04-30 19:19, Gianfranco Costamagna wrote:

> I didn't. There is no need to discuss in private. Is the bug so serious? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1]
https://github.com/Ettercap/ettercap/issues/723#issuecomment-215988405

**Comment by LocutusOfBorg** [comment]
mmm where does the quserex.dll come from?

if the dll is broken, why could/should ettercap fix the issue?

**Comment by anthonyguertin** [comment]
It's not a matter of fixing it; It is, however, important to be secure.

**Comment by LocutusOfBorg** [comment]
How can we be secure wrt third party libraries we can't control?
