### ISSUE TITLE
ettercap-0.8.2/src/ec_threads.c:206]: (style) 2 * Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [Ettercap/ettercap#727]
1.

ettercap-0.8.2/src/ec_threads.c:206]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

Source code is

 if ((e = pthread_create(&id, &attr, function, args) != 0))

Maybe better code

 if ((e = pthread_create(&id, &attr, function, args)) != 0)

2.

ettercap-0.8.2/src/ec_threads.c:209]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

   if ((e = pthread_create(&id, NULL, function, args) != 0))

Duplicate.

**Comment by LocutusOfBorg** [comment]
Hi, you are correct, would you mind opening a pull request?

**Comment by dcb314** [comment]
>would you mind opening a pull request?

No thanks. I am not quite sure what a pull request is, but
it sounds dangerously like submitting a patch.

**Comment by LocutusOfBorg** [comment]
please review https://github.com/Ettercap/ettercap/pull/730 thanks
(BTW if you send me your details and mail I can give you appropriate credits)
