### ISSUE TITLE
Etterfilter: Var??

### ISSUE THREAD

**Issue by GabrielTK** [Ettercap/ettercap#728]
Good Evening,
I`m creating a filter where i need to store a url (string) in a variable or read it from a parameter. Is there any way of doing this??

Thank you,
Gabriel

**Comment by eaescob** [comment]
Can you please elaborate a little bit more? Trying to understand what the use case is.

**Comment by hanmaru123** [comment]
sorry for asking, where should i store the filter script ?

**Comment by mnciitbhu** [comment]
@hanmaru123 anywhere you like, but you have to specify the path using `-F /path/to/filter` in Text mode and using UI in GUI mode.

**Comment by GabrielTK** [comment]
@eaescob Sorry for the delay. Like:
var someVariable = 'abcd'
Or [ettercap and it's other launch arguments]  --someVariable=abcd

**Comment by sgeto** [comment]
Are you asking how to dynamically control the content of a filter through options passed to ettercap?

**Comment by Nature1iq** [comment]
I need someone to teach please I want to learn how to use software tools please 🙏🙏🙏

**Comment by LocutusOfBorg** [comment]
Hello, please look for the documentation and don't ask for support on unrelated tickets.

**Comment by LocutusOfBorg** [comment]
there is a lot of documentation on manpages, on youtube and other channels, including the various README*
on the top source directory
https://github.com/Ettercap/ettercap
