### ISSUE TITLE
Does Ettercap support sniff and MITM attack for fiber(FDDI) ?

### ISSUE THREAD

**Issue by ngodai** [Ettercap/ettercap#729]
Hi!
Ettercap is a very useful software. I have a question, can you please answer it?
I see here have said ettercap support fiber (FDDI protocol):
https://github.com/Ettercap/ettercap/blob/323313a222bcb447b8839d955075073f526c4cfe/include/ec_proto.h
But I don't have condition to try it. Anyone tried this protocol can tell me it work stability?
And If I want to try it, what devices are needed(fiber card?...)
Sorry about my English! 
Thank you!

**Comment by LocutusOfBorg** [comment]
We never had bug reports about FDDI protocol, yes you need a fiber and a NIC supporting it.
(I can't test such environment)

**Comment by ngodai** [comment]
Thank you so much!

On Mon, May 23, 2016 at 5:24 PM, Gianfranco Costamagna <
notifications@github.com> wrote:

> Closed #729 <https://github.com/Ettercap/ettercap/issues/729>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Ettercap/ettercap/issues/729#event-668759340>
>



-- 
*===========================================*
*Ngô Cao Đại*
*Network Security Engineer*
*company: MVS*
*Web: 1link.vn <http://1link.vn>*
*E-mail: chec.fet@gmail.com <E-mail%3Achec.fet@gmail.com>*
*Phone Number :01689925829*

**Comment by ngodai** [comment]
I have another question, can you answer me, please!
Can I install Ettercap on a server and place it at ISP have speed
10Gbps(fiber) and I only MITM attack, not Sniff.  Speed  network has been
diminished or not?
Assuming servers that support 10Gbps fiber card, RAM <128G, and 2 CPU Intel
Xeon Core i5 or i7.
Thank you so much!

On Mon, May 23, 2016 at 5:30 PM, Dai Ngo <chec.fet@gmail.com> wrote:

> Thank you so much!
>
> On Mon, May 23, 2016 at 5:24 PM, Gianfranco Costamagna <
> notifications@github.com> wrote:
>
>> Closed #729 <https://github.com/Ettercap/ettercap/issues/729>.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Ettercap/ettercap/issues/729#event-668759340>
>>
>
>
>
> --
> *===========================================*
> *Ngô Cao Đại*
> *Network Security Engineer*
> *company: MVS*
> *Web: 1link.vn <http://1link.vn>*
> *E-mail: chec.fet@gmail.com <E-mail%3Achec.fet@gmail.com>*
> *Phone Number :01689925829*
>



-- 
*===========================================*
*Ngô Cao Đại*
*Network Security Engineer*
*company: MVS*
*Web: 1link.vn <http://1link.vn>*
*E-mail: chec.fet@gmail.com <E-mail%3Achec.fet@gmail.com>*
*Phone Number :01689925829*

**Comment by koeppea** [comment]
Ettercap is designed to do MITM attacks. The supported platforms are documented in README.PLATFORMS. 
Ettercap processes packet forwarding (due to it's nature), process oriented, hence more CPU power per core, the better. So a i5 with higher frequency would be better than a i7 with less frequency.
