### ISSUE TITLE
missing declaration for symbol 'HOOK_PACKET_ESP'

### ISSUE THREAD

**Issue by chenjiaqi** [Ettercap/ettercap#732]
hello,
        when I try to run some lua script examples in "/usr/local/share/ettercap/lua/scripts", it comes a error like 
"...ar/ettercap/HEAD/share/ettercap/lua/core/hook_points.lua:149: missing declaration for symbol 'HOOK_PACKET_ESP'
stack traceback:
	[C]: in function 'require'
	test1.lua:2: in main chunk "
What should i do with this? Thankyou.

**Comment by LocutusOfBorg** [comment]
can you please try pull #732? thanks

**Comment by koeppea** [comment]
You mean #733?

**Comment by LocutusOfBorg** [comment]
yes indeed :)

**Comment by LocutusOfBorg** [comment]
@chenjiaqi please don't close and just tell us if it works or not, thanks

**Comment by xlife8** [comment]
Have you found a solution for the problem?I have the same problem.Could you tell me how to solve?
