### ISSUE TITLE
ettercap 0.8.0 keeps showing DHCP: [XX:XX:XX:XX:XX:XX] REQUEST XXX.XXX.X.X

### ISSUE THREAD

**Issue by One-SNapp** [Ettercap/ettercap#734]
#I am using ettercap 0.8.0 (graphical version) on ubuntu 14.4. I tried to run ettercaps arp sniffing and the program keeps echoing  DHCP: [XX:XX:XX:XX:XX:XX] REQUEST XXX.XXX.X.X.

![ettercapbug](https://cloud.githubusercontent.com/assets/19677379/15803449/1f16c03c-2a93-11e6-89b1-2948f9bc0269.png)

I dont believe its supposed to do this. Is it a bug?

--Note, i got ettercap from the ubuntu software center.

**Comment by koeppea** [comment]
Hi,

this is supposed to be. Ettercap sees a DHCP packet and just displays
the information ettercap sees and which could potentially usefull in the
message pane.

This isn't a bug.

**Comment by koeppea** [comment]
currently not.
