### ISSUE TITLE
ERROR 12 Cannot allocate memory!

### ISSUE THREAD

**Issue by ngodai** [Ettercap/ettercap#735]
Hi,
I'm using Ettercap 0.8.2 on Kali 2.0 32bit. I try to change all images of website by using script. If I use Ettercap Graphic, it works very well. But when I use command line:
ettercap -TSq -F changeimage.ef -M arp /192.168.X.1(gateway)// /192.168.X.2// 
MITM and sniff ran, but script not work. Then I change command line
ettercap -TSq -F changeimage.ef -M arp /// /192.168.X.2//
Script ran. but affter a few minutes it has an error:
ERROR : 12, Cannot allocate memory
[/build/ettercap-z9buAO/ettercap-0.8.2/src/ec_threads.c:ec_thread_new_detached:210]
 not enough resources to create a new thread in this process: Operation not permitted
Please help! Thank you!

**Comment by LocutusOfBorg** [comment]
can you please try the latest git? that bug should be fixed

**Comment by ngodai** [comment]
Thank you so much! it worked very well!

**Comment by LocutusOfBorg** [comment]
:) thanks for confirming!

**Comment by ilhamtaufiq08** [comment]
how to fix this ettercap git ? i cant find for this tutorial

**Comment by koeppea** [comment]
@ilhamtaufiq08 @LocutusOfBorg just suggested to try the same using the latest code base from github as the reported bug is a known and meanwhile an already fixed one.
