### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ingratosocial** [Ettercap/ettercap#736]
when i try to compile a filter with
`$etterfilter -o pwd.filter pwned.ef`
or 
`$etterfilter pwd.filter -o pwned.ef`
I always get:
`etterfilter 0.8.2 copyright 2001-2015 Ettercap Development Team
Segmentation fault (core dumped)`
i have ubuntu 16.04 xenial, 64 Bits.

**Comment by LocutusOfBorg** [comment]
can you please try the latest git? and also to send the core-dump

**Comment by ingratosocial** [comment]
it work for me! :) Thx!
