### ISSUE TITLE
Etterfilter exec() function not running 

### ISSUE THREAD

**Issue by ryanleh** [Ettercap/ettercap#738]
I have an etterfilter with form

if (search(DATA.data = "(hex string)" && ip.src == "(some ip)")) 
{
msg("test message");
exec("touch /tmp/command_worked");
}

The message prints as expected but the command does not execute.

**Comment by LocutusOfBorg** [comment]
can you please try the latest git? I remember we had some fixes there.

**Comment by ryanleh** [comment]
Ok I did. Ettercap is version 0.8.2 and the issue still persists.

**Comment by ryanleh** [comment]
I tried log(DATA.data, "/tmp/logfile.log"); also and I received the error "filter engine: cannot open file /tmp/logfile.log" even after creating the file in the directory and running ettercap as sudo.

**Comment by ryanleh** [comment]
I'm running this in 4.3.0-kali1-amd64 btw

**Comment by LocutusOfBorg** [comment]
0.8.2 is *not* the git master :)

**Comment by koeppea** [comment]
Your syntax is just wrong. Cf. the **etterfilter** man-page:
```
       search(where, what)
              this  function searches the string 'what' in the buffer 'where'.
              The buffer can be either DATA.data or DECODED.data.  The  former
              is  the payload at layer DATA (ontop TCP or UDP) as it is trans‐
              mitted on the wire, the latter is the payload  decoded/decrypted
              by dissectors.
              So,  if you want to search in an SSH connection, it is better to
              use 'DECODED.data' since 'data' will be encrypted.
              The string 'what' can be binary. You have to escape it.

              example:
              search(DATA.data, "\x41\x42\x43")
```

**Comment by koeppea** [comment]
Probably you intended to do something like:
```
if (search(DATA.data, "\xab\xcd") && ip.src == '192.168.0.1')
{
msg("test message");
exec("/usr/bin/touch /tmp/command_worked");
}
```

Tested this in my lab. 
The second issue is that **exec** really executes a binary. It's not a full-blown shell maintaining a *$PATH* variable searching for the executable command.

**Comment by charlie-12138** [comment]
> I tried log(DATA.data, "/tmp/logfile.log"); also and I received the error "filter engine: cannot open file /tmp/logfile.log" even after creating the file in the directory and running ettercap as sudo.

how to solve

**Comment by koeppea** [comment]
@charlie-12138 please try the latest version 0.8.3.1 or the latest code from Github.
If the issue still persists, please open a new issue.
