### ISSUE TITLE
Ettercap on home brew OS X 

### ISSUE THREAD

**Issue by r4sl** [Ettercap/ettercap#743]
I begin to use ettercap, (graphical mode) start unified sniffing then get these errors:
(<unknown>:45134): Gtk-CRITICAL **: gtk_image_get_pixbuf: assertion 'image->storage_type == GTK_IMAGE_PIXBUF || image->storage_type == GTK_IMAGE_EMPTY' failed ERROR : 1, Operation not permitted [/tmp/ettercap-20160720-794-12euz0t/ettercap-0.8.2/src/os/ec_darwin.c:disable_ipv6_forward:94] sysctl() | net.inet6.ip6.forwarding
And crash.

**Comment by koeppea** [comment]
Have you started ettercap with root privileges?

please inspect README.BUGS and README.OSXLION?

of course we should have a README.OSXDARWIN but lacking test users
owning a current Mac denies that ATM.

**Comment by r4sl** [comment]
I started ettercap withought system integrity protection on, but not in root.

**Comment by koeppea** [comment]
Can you retry starting ettercap as root?

**Comment by r4sl** [comment]
Ok will do

**Comment by koeppea** [comment]
Any result?

**Comment by hqt** [comment]
Nice. I meet same problem and run under root solved my problem

**Comment by koeppea** [comment]
So this is probably the reason for the failure.
Closing now. @r4sl Reopen if you like.

**Comment by r4sl** [comment]
Haha, Im sorry for not responding, simply not used this email adress in a while. I'm sure the fix should work, but I've migrated already! Currently using arch linux, and it works fine!

**Comment by Tup0lev** [comment]
No No No I ran ettercap with sudo and I have no SIP but I still get that error.

**Comment by LocutusOfBorg** [comment]
do you use the latest git HEAD?
