### ISSUE TITLE
Question about arp:remote

### ISSUE THREAD

**Issue by phackt** [Ettercap/ettercap#750]
Hello, i just read the doc about -M arp:remote option but i do not really figure out how it works. I mean without this option i'm intercepting all the traffic between TARGET 1 and TARGET 2. What are we sniffing more when we are specifying this option arp:remote? In my example TARGET 1 is a PC and TARGET 2 the gateway. In pratice i can see the all the sniffed traffic with this option, but why i can not have the same traffic capture with just -M arp?

Thanks in advance,
Phackt.

**Comment by koeppea** [comment]
The difference is that w/o "remote", ettercap poisons only one-way. It spoofs only target1 pretending to be target2. Target2 remains unpoisoned.
With "remote", target2 will be poisoned as well.

**Comment by phackt** [comment]
Thanks Alexander!

**Comment by phackt** [comment]
A last thing, do you know if, once an attack is launched in text mode -T, if there is a way to hot load a plugin or unload a plugin?

Thanks a lot,

**Comment by mafiya69** [comment]
@phackt  press `p` and then type the name of plugin.

**Comment by phackt** [comment]
Thanks Govind i will check that.
