### ISSUE TITLE
SEND L3 ERROR: 28 byte packet (0800:01) destined to 192.168.29.134 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (No route to host)

### ISSUE THREAD

**Issue by hktalent** [Ettercap/ettercap#753]
1 、 mac os 10.11.6
2、ettercap 0.8.2
net Work: wifi
wifi: Hon Hai Precision Ind. Co.,Ltd.
3、cmd
QQ1160:~ xiatian$ sudo sysctl -w net.inet.ip.forwarding=1
net.inet.ip.forwarding: 1 -> 1
QQ1160:~ xiatian$ sudo ettercap -i en0 -TqM ARP:REMOTE // //
* |==================================================>| 100.00 %
***
 GROUP 1 : ANY (all the hosts in the list)
 GROUP 2 : ANY (all the hosts in the list)
Starting Unified sniffing...

Text only Interface activated...
Hit 'h' for inline help

DHCP: [192.168.28.1] ACK : 192.168.29.211 255.255.254.0 GW 192.168.28.1 DNS 61.139.2.69 
SEND L3 ERROR: 28 byte packet (0800:01) destined to 192.168.29.134 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 28 byte packet (0800:01) destined to 192.168.29.134 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 28 byte packet (0800:01) destined to 192.168.29.134 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 28 byte packet (0800:01) destined to 192.168.29.134 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 28 byte packet (0800:01) destined to 192.168.29.131 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (No route to host)rded (libnet_write_raw_ipv4(): -1 bytes written (No route to host)
)

User requested a CTRL+C... (deprecated, next time use proper shutdown)

ERROR : 50, Network is down
[/tmp/ettercap20151127-37296-1j73pe3/ettercap-0.8.2/src/ec_send.c:send_arp:319]

 libnet_write (-1): libnet_write_link(): -1 bytes written (Network is down)

**Comment by mafiya69** [comment]
Seems like host is down, `ping` and check.

**Comment by hktalent** [comment]
kali linux wifi is ok,but mac os wifi in company ~~ no ok
thanks

**Comment by rifanajah** [comment]
i have same problem but, i use linux mint 18 mate
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ffb2:f2af was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 64 byte packet (86dd:3a) destined to ff02::1:ff6a:8078 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 64 byte packet (86dd:3a) destined to ff02::1:ff1a:2bc1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff1a:16ca was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff71:35a was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 56 byte packet (86dd:3a) destined to ff02::2 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 64 byte packet (86dd:3a) destined to ff02::1:ffd6:35e8 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 76 byte packet (86dd:3a) destined to ff02::16 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 76 byte packet (86dd:3a) destined to ff02::16 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff4c:3d82 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 56 byte packet (86dd:3a) destined to ff02::2 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 56 byte packet (86dd:3a) destined to ff02::2 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 64 byte packet (86dd:3a) destined to ff02::1:ff49:85ef was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 56 byte packet (86dd:3a) destined to ff02::2 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 56 byte packet (86dd:3a) destined to ff02::2 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff51:3999 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (Cannot assign requested address)
)

**Comment by rifanajah** [comment]
when i ping is fine

**Comment by koeppea** [comment]
@rifanajah: Can you please open a new issue and describe how to reproduce?
