### ISSUE TITLE
bug in the plugin sslstrip

### ISSUE THREAD

**Issue by KevinWL** [Ettercap/ettercap#754]
hello,
   When i used the plugin sslstrip ,it caused segmentfault usually. Then i found the bug in sslstrip.c

r = strstr((const char*)po->DATA.data, "\r\n");
/*I added */
 if(!r)
 {
 ¦   return ;
 }
/*I added */
r += 2; //Skip \r\n
 char *h = strdup(r);

**Comment by koeppea** [comment]
I seems that you're not using the latest code base.
The snipplet looks differently in the current code base:
```c

   char *r = (char*)po->DATA.data;

   //Skip the first line of request
   if ((r = strstr((const char*)po->DATA.data, "\r\n")) == NULL)
      return; // This doesn't seem to look as a HTTP header

   r += 2; //Skip \r\n

   char *h = strdup(r);
```

So you see, this case is already handled in the latest code base.
Please test again using the latest code from github and feel free to reopen the issue if the issue still occurs.
