### ISSUE TITLE
SEND L3 ERROR

### ISSUE THREAD

**Issue by KevinWL** [Ettercap/ettercap#755]
hi,
My system is openwrt,and i used iptables to redirect,and i seted ec_uid = 0 ec_gid=0 in etter.conf
but there are lots of  error infomation like "SEND L3 ERROR: 40 byte packet (0800:06) destined to 120.25.209.186 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted))"

how can i do to avoid this error? thanks

**Comment by LocutusOfBorg** [comment]
ca you please try the latest git code?
