### ISSUE TITLE
Ettercap not getting any data on Kali

### ISSUE THREAD

**Issue by Seero42** [Ettercap/ettercap#756]
Hi, I'm running Kali GNU/Linux rolling version installed on HDD and I'm trying to use ettercap. But when I start sniffing and arp poisoning a target in my network ettercap doesn't get any data from login to any kind of page. This is the lspci -v of my network controller:
`03:00.0 Network controller: Qualcomm Atheros AR9287 Wireless Network Adapter (PCI-Express) (rev01)
	Subsystem: Foxconn International, Inc. T77H167.00
	Flags: bus master, fast devsel, latency 0, IRQ 17
	Memory at da400000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: [40] Power Management version 3
	Capabilities: [50] MSI: Enable- Count=1/1 Maskable- 64bit-
	Capabilities: [60] Express Legacy Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Virtual Channel
	Capabilities: [160] Device Serial Number 00-15-17-ff-ff-24-14-12
	Capabilities: [170] Power Budgeting <?>
	Kernel driver in use: ath9k
	Kernel modules: ath9k`
I've tried searching in this forum and through google too, but nothing that I've found seemed to solve the problem. Can anyone help me?

**Comment by LocutusOfBorg** [comment]
did you start the sniffing and the attack?
which version? did you try latest git?

**Comment by Seero42** [comment]
Yes, I've started both the sniffing and the attack. The version is 0.8.2. About git, I don't know what that is, can you tell me what should I do?

**Comment by LocutusOfBorg** [comment]
https://github.com/Ettercap/ettercap/blob/master/README.GIT
and the other README.* in that directory

**Comment by Seero42** [comment]
I've followed the steps after installing cmake but still when i put cmake .. it tells me command not found

**Comment by LocutusOfBorg** [comment]
apt-get install cmake?
apt-get build-dep ettercap might be even better

**Comment by Seero42** [comment]
Ok, it worked, but when I put cmake .. it gives me another error message:
`~/ettercap/build# cmake ..
-- The C compiler identification is GNU 6.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for sys/poll.h
-- Looking for sys/poll.h - found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sys/utsname.h
-- Looking for sys/utsname.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for arpa/nameser.h
-- Looking for arpa/nameser.h - found
-- Looking for ltdl.h
-- Looking for ltdl.h - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for libgen.h
-- Looking for libgen.h - found
CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.6/Modules/FindCurses.cmake:206 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/Modules/EttercapLibCheck.cmake:12 (find_package)
  CMakeLists.txt:102 (include)


-- Configuring incomplete, errors occurred!
See also "/root/ettercap/build/CMakeFiles/CMakeOutput.log".
See also "/root/ettercap/build/CMakeFiles/CMakeError.log".
`
What do I do now?

**Comment by LocutusOfBorg** [comment]
apt-get build-dep ettercap,
or follow the docs.

**Comment by Seero42** [comment]
This is the response to apt-get build-dep ettercap:
`Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
`
What does it mean?

**Comment by LocutusOfBorg** [comment]
https://github.com/Ettercap/ettercap/blob/master/README
there is the apt line

**Comment by Seero42** [comment]
Ok, I did all the procedure and then started ettercap: initially it worked, it sniffed one password from a non-https site, but after that it just stopped working. Any clue?

**Comment by LocutusOfBorg** [comment]
not without any information. Start from command line, follow the README.BUGS instructions

**Comment by Seero42** [comment]
Those are information to make a bug report, which one of the two should I follow?

**Comment by LocutusOfBorg** [comment]
https://github.com/Ettercap/ettercap/blob/master/README.BUGS
not sure if ettercap is crashing or whatever else, please run from command line and see

**Comment by Seero42** [comment]
I ran it on command line and I don't think it's crashing, it just doesn't show the passwords, indeed all the sites visited and google research are shown before and after the logging test.

**Comment by LocutusOfBorg** [comment]
not sure, do you use arp:remote?
I think you might be missing some keywords in the etter.fields file.
(like some post using non-standard password names for their field)
