### ISSUE TITLE
Man page suggestions 

### ISSUE THREAD

**Issue by FIOpwK** [Ettercap/ettercap#764]
Under Description >>Unified  paragraph 2 line 1 Sentence 2 states "This is done to prevent to forward a packet twice" 

Cleaner sentence can state "This is done to prevent [a forward to] a packet twice" 

Trivial yes, but we love our man pages 8-) and ettercap.

**Comment by LocutusOfBorg** [comment]
Hi, do you mind submitting a pull request? thanks

**Comment by LocutusOfBorg** [comment]
``` ./man/ettercap.8.in ``` seems the file to change

**Comment by LocutusOfBorg** [comment]
isn't better
"this is done to prevent a forward of a package twice"?

**Comment by FIOpwK** [comment]
Yes that's also clean

**Comment by LocutusOfBorg** [comment]
pull request please?

**Comment by FIOpwK** [comment]
Keep getting permission denied error 403

**Comment by LocutusOfBorg** [comment]
did you fork the project?

**Comment by FIOpwK** [comment]
Forked and cloning now
