### ISSUE TITLE
ettercap: symbol lookup error: ettercap: undefined symbol: disable_ipv6_forward

### ISSUE THREAD

**Issue by alienwaresoldier** [Ettercap/ettercap#767]
When I open up ettercap -G in the terminal and start sniff with wlan0 i,the ettercap gui disapeared and I get this error in the terminal:

root@kali:~# ettercap -G

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

ettercap: symbol lookup error: ettercap: undefined symbol: disable_ipv6_forward
root@kali:~#

**Comment by alienwaresoldier** [comment]
SOLVED:) :) :)

**Comment by LocutusOfBorg** [comment]
how?
