### ISSUE TITLE
Searching hosts issue?

### ISSUE THREAD

**Issue by JK3N** [Ettercap/ettercap#768]
I'm using parrotsec, and when i run ettercap GUI, it won't find my local machine during a host scan...thus can't set for target 1. Maybe this is a simple issue? I didn't see anybody else having it?
Finds most if not all the other devices on my network.

**Comment by koeppea** [comment]
What do you mean with "local machine"? The host that runs ettercap?

**Comment by JK3N** [comment]
Correct...i see most if not all the same network devices...just not my actual machine i'm using Ettercap on.

**Comment by sgeto** [comment]
When you do a host scan, Ettercap logically omits your own IP

**Comment by koeppea** [comment]
Correct.

**Comment by JK3N** [comment]
Ah i see...i watched a video that said to choose own IP for target 1, and target IP for target 2 when starting a MITM attack, hence the question. Appreciate it.

**Comment by sgeto** [comment]
Sue the author! Kidding.
