### ISSUE TITLE
Ettercap error while scanning hosts with wlan0

### ISSUE THREAD

**Issue by srumaih** [Ettercap/ettercap#770]
Hi Everyone , 

I am new to ettercap , after I finish the installation of Kali items and while trying to use ettercap with the below command 
sudo ettercap - wlan0 -C
when I do a hosts scan the ettercap crashes with this error 
ERROR : 22, Invalid argument
[/build/ettercap-JElruw/ettercap-0.8.2/src/ec_send.c:send_arp:319]
libnet_Write (-1): libenet_write_link(): only -1 bytes written (Invalid argument)

Can anyone help me please with some details .

Thanks ,
Sadeq

**Comment by LocutusOfBorg** [comment]
did you mean "ettercap -i wlan0 -C"?

**Comment by srumaih** [comment]
Yes

**Comment by LocutusOfBorg** [comment]
please try to build the latest git version, and tell us if the problem persists (there are build information on the root of the source tree)

**Comment by srumaih** [comment]
Thanks for the update .

**Comment by srumaih** [comment]
I am note sure how can I get the latest git version .
Can you please give me the steps?

**Comment by srumaih** [comment]
if you mean :- apt-get update .
I already apply this with no luck .

**Comment by LocutusOfBorg** [comment]
git clone, or just click "download" on the download link
https://github.com/Ettercap/ettercap

**Comment by srumaih** [comment]
I downloaded the zip file .

**Comment by sgeto** [comment]
If you're on Debian or any Debian based system, extract the zip and find the file "readme.md".
It should explain everything.

**Comment by srumaih** [comment]
I could not find the readme.md !

**Comment by srumaih** [comment]
I am getting the below error while trying cmake .. 
root@kali:~/Downloads/ettercap-master/build# cmake ..
-- The C compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for sys/poll.h
-- Looking for sys/poll.h - found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sys/utsname.h
-- Looking for sys/utsname.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for arpa/nameser.h
-- Looking for arpa/nameser.h - found
-- Looking for ltdl.h
-- Looking for ltdl.h - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for libgen.h
-- Looking for libgen.h - found
CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.6/Modules/FindCurses.cmake:206 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/Modules/EttercapLibCheck.cmake:12 (find_package)
  CMakeLists.txt:102 (include)


-- Configuring incomplete, errors occurred!
See also "/root/Downloads/ettercap-master/build/CMakeFiles/CMakeOutput.log".
See also "/root/Downloads/ettercap-master/build/CMakeFiles/CMakeError.log".

**Comment by LocutusOfBorg** [comment]
apt-get build-dep ettercap

**Comment by srumaih** [comment]
Thanks the apt-get build-dep ettercap success.
But still i faceing the same error while searching hosts with wlan0 . :(

**Comment by sgeto** [comment]
`sudo ettercap - wlan0 -C`

Is this the command?

**Comment by srumaih** [comment]
The command is sudo ettercap -i wlan0 -C

**Comment by srumaih** [comment]
I tried this as well 

root@kali:~/Desktop# sudo ettercap -T

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

Listening on:
 wlan0 -> B8:27:EB:06:88:DE
	  192.168.1.118/255.255.255.0
	  fe80::b2cd:876b:6114:d872/64
	  2001:16a2:8bf3:a300:544c:b90a:3f7b:39b2/64

SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to EUID 65534 EGID 65534...

  33 plugins
  42 protocol dissectors
  57 ports monitored
20388 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
Lua: no scripts were specified, not starting up!

Randomizing 255 hosts for scanning...
Scanning the whole netmask for 255 hosts...

ERROR : 22, Invalid argument
[/build/ettercap-JElruw/ettercap-0.8.2/src/ec_send.c:send_arp:319]

 libnet_write (-1): libnet_write_link(): only -1 bytes written (Invalid argument)

**Comment by sgeto** [comment]
We probably should have told you to build a debug version...
Can you do it again, but a debug version?

**Comment by srumaih** [comment]
I mentioned i am new :) 

Can you please advise the command to debug version?

**Comment by sgeto** [comment]
well, to narrow the issue even more I would also suggest you avoid system libraries

`cmake -DSYSTEM_LIBS=Off -DCMAKE_BUILD_TYPE=debug ../`

then recreate the issue. The session will produce a text file called "ettercap-0.8.2_debug.log" in the root directory (or wherever the binaries are located)
Attache it here. 
Also: No need for sudo on Kali. Leave it out:
`ettercap - wlan0 -C`

**Comment by sgeto** [comment]
seems like it worked for you. Close the issue?

**Comment by srumaih** [comment]
not yet .. I got busy .
I will try it tonight and update the thread .

**Comment by sgeto** [comment]
well, I guess we're done here.
