### ISSUE TITLE
OSPF->224.0.0.5:0->AUTH: No Auth

### ISSUE THREAD

**Issue by davidbrainlittle** [Ettercap/ettercap#773]
This message kept coming out when I was scanning a network. When this occured, poisoning plugins(like arp) were unavailable.
This only appeared in one specific network. I'm unable to provide furthur information since I was doing a blackbox test.

**Comment by LocutusOfBorg** [comment]
seems that an OSPF routing protocol was alive on that network.
look at ``` src/dissectors/ec_ospf.c ```

Likely, you have OSPF routing protocol alive, and for this reason the network seems to be level3. You should try to poison OSPF routes if you want to do MITM attacks (and act as a router)
