### ISSUE TITLE
ettercap: symbol lookup error: ettercap: undefined symbol: disable_ipv6_forward

### ISSUE THREAD

**Issue by xforjustice** [Ettercap/ettercap#778]
Hi,
Everytime I try to run ettercap on ubuntu mate and run unified sniffing, ettercap crashes and I get this error

ettercap: symbol lookup error: ettercap: undefined symbol: disable_ipv6_forward

I am trying to run ettercap on Ubuntu 16.04 LTS xenial

Please help ?

Thank you,

**Comment by LocutusOfBorg** [comment]
strange, is it the official ubuntu/ettercap?

**Comment by LocutusOfBorg** [comment]
please use the git HEAD

**Comment by koeppea** [comment]
Could it be that the Ubuntu built was built with v6 support but the actual machine had (why on earth) deactivated it completely?
Do you see any output when issuing the following command: 
```
netstat -ei | grep inet6
```
If v6 is enabled, you should at least see an address starting with fe80.

**Comment by xforjustice** [comment]
It is the official ubuntu/ettercap was downloaded and installed through apt-get. I didn't use git and build it from source. This is the output of the netstat command:
          netstat -ei|grep inet6

          inet6 addr: ::1/128 Scope:Host
          inet6 addr: fe80::250:56ff:fec0:1/64 Scope:Link
          inet6 addr: fe80::250:56ff:fec0:8/64 Scope:Link
          inet6 addr: fe80::5285:19ee:c566:ce60/64 Scope:Link
Thank you,

**Comment by xforjustice** [comment]
Hi,
I just pulled the source from github and rebuilt it. It works flawlessly now. Nevertheless, I still can't figure out why the ettercap version installed through ubuntu repository has the issue submitted earlier.

Thank you for your help.

**Comment by LocutusOfBorg** [comment]
so, is the issue fixed by the latest git?

**Comment by xforjustice** [comment]
Yes. Latest git fixed the issue.
