### ISSUE TITLE
ettercap  issues  errror 19

### ISSUE THREAD

**Issue by foctionss** [Ettercap/ettercap#785]
I use  duel boot  OS, kali linux, and  win:D
 I TYPE   ettercap -Tqi -wlan0 -M  arp:remote /// ///
 But    it  shows up error  below ...

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

ERROR : 19, No such device
[/build/ettercap-TeeKKK/ettercap-0.8.2/src/ec_network.c:source_init:178]

 pcap_open_live: -wlan0: No such device exists (SIOCGIFHWADDR: No such device) 
How can i fix it ?

Please help

**Comment by LocutusOfBorg** [comment]
please post the result of
"ifconfig -a"

**Comment by LocutusOfBorg** [comment]
please post the result of
```ifconfig -a```

**Comment by sgeto** [comment]
You have a typo. Remove the hyphen before wlan0:

ettercap -Tqi wlan0 -M arp:remote /// ///

**Comment by foctionss** [comment]
here is my  ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.65  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::3d72:bb4f:1876:b8f4  prefixlen 64  scopeid 0x20<link>
        ether 08:9e:01:ee:ae:7d  txqueuelen 1000  (Ethernet)
        RX packets 2234  bytes 2466425 (2.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1630  bytes 232379 (226.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 24  bytes 1272 (1.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24  bytes 1272 (1.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.67  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::a6db:30ff:fe6e:d1b7  prefixlen 64  scopeid 0x20<link>
        ether a4:db:30:6e:d1:b7  txqueuelen 1000  (Ethernet)
        RX packets 250  bytes 97995 (95.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 39  bytes 3776 (3.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by foctionss** [comment]
sgeto  i tryed it  but  didn t  worked,

with   ettercap -G   its   loks like   working  fine but still  not  capturing   all  http passwords

**Comment by koeppea** [comment]
Not -i -wlan0. 
-i wlan0. !
The error message is correct. You typed the name of your adapter wrong.

**Comment by foctionss** [comment]
Wow, thank  you a lot :P,!
