### ISSUE TITLE
Running plugin only once

### ISSUE THREAD

**Issue by henryhui1242** [Ettercap/ettercap#790]
Hi,

I am trying to create a plug-in on which it only execute once and stop, then I can call it again and it will stop again after it run. 

I have used `hook_add(HOOK_PROTO_HTTP, &function);` 
And in the function I have tried using `int plugin_fini(char *name)` and calling the finish function in my plug-in but it didn't work. What should I do?

**Comment by LocutusOfBorg** [comment]
plugins are inteded to run until you deactive them (by double clicking on them).
However, I tried to edit dummy plugin to call the fini function inside its run
```diff
    USER_MSG("DUMMY: plugin running...\n");
-
+   (void) dummy_fini(dummy);

```
and it seems to be called correctly, unfortunately the interface still shows the "*" character, because the ui is not aware of other ways to terminate a plugin.
I don't think this is an use - case worth a custom implementation, what do you think?

**Comment by henryhui1242** [comment]
I tried to called the finish function in the plugin but it freezes the ettercap (I use ettercap in text user interface). Do I need to call any other function after I called the finish function as I have added a hook?

**Comment by LocutusOfBorg** [comment]
```diff
diff --git a/plug-ins/dummy/dummy.c b/plug-ins/dummy/dummy.c
index 675fade..14f15ba 100644
--- a/plug-ins/dummy/dummy.c
+++ b/plug-ins/dummy/dummy.c
@@ -91,7 +91,7 @@ static int dummy_init(void *dummy)
    (void) dummy;
 
    USER_MSG("DUMMY: plugin running...\n");
-
+   (void) dummy_fini(dummy);
    /* return PLUGIN_FINISHED if the plugin has terminated
     * its execution.
     * return PLUGIN_RUNNING if it has spawned a thread or it

```

please try the dummy plugin, it works in text only mode too.
maybe your plugin has some bugs? I suggest you to start from the dummy.c file and add code

**Comment by henryhui1242** [comment]
I have tried to work from the dummy. I have just added a hook by `hook_add(HOOK_PROTO_HTTP,&myfunc)` in the init function, `hook_del(HOOK_PROTO_HTTP,&myfunc)` in the fini function and I have tried to call the fini function in myfunc. That is what I have done.
I have then tried to run it and the ettercap eventually freezes. Have I done anything wrong?

Besides, when I trying to rebuild my plugin it, it just suddenly stop showing up in the plug-in list in ettercap (I used the exact same way to rebuild everytime and it worked before) but the ec_myplugin.so also show up with other plugin. Any idea why it happens?

**Comment by LocutusOfBorg** [comment]
```diff
--- a/plug-ins/dummy/dummy.c
+++ b/plug-ins/dummy/dummy.c
@@ -23,6 +23,7 @@
 
 #include <ec.h>                        /* required for global variables */
 #include <ec_plugins.h>                /* required for plugin ops */
+#include <ec_hook.h>
 
 #include <stdlib.h>
 #include <string.h>
@@ -39,6 +40,9 @@ int plugin_load(void *);
 static int dummy_init(void *);
 static int dummy_fini(void *);
 
+static void myfunc(struct packet_object *po) {
+ USER_MSG("myfunc called");
+}
 
 /* plugin operations */
 
@@ -98,6 +102,8 @@ static int dummy_init(void *dummy)
     * is hooked to an ettercap hookpoint and
     * it needs to be deactivated with the fini method.
     */
+   hook_add(HOOK_PROTO_HTTP,&myfunc);
+
    return PLUGIN_RUNNING;
 }
 
@@ -114,6 +120,7 @@ static int dummy_fini(void *dummy)
     * previously.
     */
    USER_MSG("DUMMY: plugin finalization\n");
+   hook_del(HOOK_PROTO_HTTP,&myfunc);
    return PLUGIN_FINISHED;
 }
```

this works correctly, it is called at each http message received, and prints the stuff. Maybe you are receiving too many http messages and your function is too heavy to process them?
you don't have to call fini in myfunc, it is automatically called I think, when the function exits.

please show some code if you want more help, I can't really reproduce that "bug"
