### ISSUE TITLE
ARP poison on Apple

### ISSUE THREAD

**Issue by myrinx** [Ettercap/ettercap#799]
It seems poisoning is not successful. The machines are being added to the groups, but than the get a new IP from the DHCP server and it happens again,over and over until the pool is exhausted.

Any clue where this issue might lie? It's on both iPad and iPhone (recent iOS)

**Comment by sgeto** [comment]
Can you post the commands you used? I feel like you're confusing arp poisoning with DHCP spoofing.

**Comment by myrinx** [comment]
I'm not confusing :) The DHCP server of the router was issuing the IPs, not ettercap.

I'm using this:
"ettercap -TqmQ -i eth0 -M arp /192.168.192.1-254/ /192.168.192.1-254/ -P autoadd -P repoison_arp"

Apple devices show up in the list, but aren't poisoned. The pull a new IP from the DHCP and ettercap tries again. This goes on and on until the IP pool of the router is depleted.

**Comment by sgeto** [comment]
> Apple devices show up in the list, but aren't poisoned.

well if they are in the list, the they are being poisoned. what other reason would they have to request a new IP? if this is meant to be some kind of countermeasure to fight the poisoning, then it's a pretty weird one to say the least.

> pull a new IP from the DHCP
new IP? how low is the lease time for devices to even get new IPs this fast?

Your command line syntax is weird by the way. try this:

`ettercap -TQm ~/ettercap_log.txt -i eth0 -M arp // // -P autoadd -P repoison_arp
`
Let it run for a bit. Then remove all the "private" stuff and post the log file (`ettercap_log.txt` located in your home directory) here.

Good luck

**Comment by sayan-sibyl** [comment]
myrinx how did got ettercap running in your mac and how did u cloned the latest build

**Comment by LocutusOfBorg** [comment]
closing, feel free to reopen in case you still have the issue
