### ISSUE TITLE
[windows] Operating system not supported?

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [Ettercap/ettercap#800]
OS: **Windows 10**
Ettercap version: **0.8.2**

Problem: while trying to compile and build from source files: 

```
> cmake ../
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error at cmake/Modules/EttercapOSTest.cmake:25 (message):
  Operating system not supported
Call Stack (most recent call first):
  CMakeLists.txt:84 (include)


-- Configuring incomplete, errors occurred!
See also "C:/PentestBox/bin/Sniffing/ettercap/build/CMakeFiles/CMakeOutput.log".
```

**Comment by LocutusOfBorg** [comment]
personally I don't see much added value in supporting windows OS, and we "support" only mingw and cygwin.
If you want to change that code and see if you can make it build, I'll be glad to support you (but please use the latest git master code)

**Comment by Ghostboy-287** [comment]
i'm not an expert but i ll try, 
i ll inform you if i ll success :)
have a good night/day

**Comment by xuxuedong** [comment]
hey Ghostboy-287, i have the same question, hope you can work it out!!!

**Comment by readyforchaos** [comment]
Still no support available for Windows OS in 2020, sadly.

**Comment by koeppea** [comment]
Unfortunately not lacking Windows developers.

One of the major issues is the lack of a NAT-capable host-based firewall 
that is controllable via CLI.

**Comment by koeppea** [comment]
Closing since we're lacking Windows developers.
