### ISSUE TITLE
Lua: no scripts were specified, not starting up!

### ISSUE THREAD

**Issue by Recheio** [Ettercap/ettercap#801]
Hello,
When i try sniffing i got an error.

_Sniff > Unified sniffing... > wlan0_

Listening on:
 wlan0 -> 00:00:00:00:00:00 
	  000.000.0.000/000.000.000.0
	  0000::0000:0000:0000:0000/00

Privileges dropped to EUID 0 EGID 0...

  33 plugins
  42 protocol dissectors
  57 ports monitored
20388 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
**Lua: no scripts were specified, not starting up!**
Starting Unified sniffing...

I edit my MAC, IPv4 and IPv6.
I have tried everything i could find in forums and some sites.
Can someone help me?

Thanks,
   Recheio.

**Comment by koeppea** [comment]
It just means that the Lua engine isn't starting. 
Sniffing is starting anyway. Look at the line below.

**Comment by Recheio** [comment]
Can i use it this way? It doesn't affect the results?

**Comment by LocutusOfBorg** [comment]
it shouldn't affect your results, unless you wrote custom lua scripts

**Comment by Recheio** [comment]
Thank you koeppea and LocutusOfBorg, i just get in University and i'm new at Linux and some other things. Thanks and sorry about my english.

**Comment by koeppea** [comment]
So closing.
