### ISSUE TITLE
compile and run in folder

### ISSUE THREAD

**Issue by vendforce** [Ettercap/ettercap#805]
Can you compile the lastest git version and run in folder without installing

cd ettercap
mkdir make
cd make
cmake ..
make
cd ../src
./ettercap -T -w dump -M ARP /192.168.1.1/ // 

{ ec_conf.c:load_conf:292 } 
error : Cannot open etter.conf

I'm guessing I need to export path in bashrc ? will that work

**Comment by LocutusOfBorg** [comment]
no, after make you just need ./ettercap, not cd ../src
./src/ettercap
