### ISSUE TITLE
ettercap: unrecognized option `--lua-script'

### ISSUE THREAD

**Issue by Soulghost** [Ettercap/ettercap#806]
Hello, I use the ettercap 0.8.2, when I try to load a filter writen in lua using --lua-script ig.lua，the console tell me that "ettercap: unrecognized option `--lua-script'", my system is macOS 10.12.5, so is this system's ettercap cannot use lua to load a filter?

**Comment by mafiya69** [comment]
You need to recompile the code with Lua Support ON. [See this line](https://github.com/Ettercap/ettercap/blob/master/CMakeLists.txt#L16)
