### ISSUE TITLE
What does this signify? (SSL dissection needs a valid 'redir_command_on' script in the etter.conf file Privileges dropped to EUID 65534 EGID 65534...)

### ISSUE THREAD

**Issue by sayan-sibyl** [Ettercap/ettercap#809]
What does this signify? SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to EUID 65534 EGID 65534...

**Comment by koeppea** [comment]
It just tells you that you need to uncommend the *redir_comman_{on,off}* configuration lines.
They differ depending on the OS ettercap is running on.
In order to get these commands to work, ettercap need to run as root for which EUID and EGID need to be **0**. The second line informs you about this.

If that doesn't answer your question feel free to reopen.

**Comment by sayan-sibyl** [comment]
Can u be a little more elaborate?

**Comment by LocutusOfBorg** [comment]
You need to change iptables for redirection being performed

**Comment by sayan-sibyl** [comment]
can u direct me step by step? As I am new to all this!

**Comment by LocutusOfBorg** [comment]
https://www.google.it/search?client=ubuntu&channel=fs&q=how+to+redirect+traffic+with+iptables&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=N0ZVWZaYNfG5ygX5i5eADA

**Comment by LocutusOfBorg** [comment]
https://sites.google.com/site/clickdeathsquad/Home/cds-sslstripping and lot of google

**Comment by sayan-sibyl** [comment]
What if I start arp poisoning just to surf at full bandwidth,then can I ignore this warning

**Comment by LocutusOfBorg** [comment]
I don't remember what happens if you try https websites, but probably you can do it

**Comment by sayan-sibyl** [comment]
hmmm

**Comment by sayan-sibyl** [comment]
n sometimes the program hack while stopping mitm attacks so I simply force quit the terminal app and Ettercap to end the process so my question does that leaves the process of ARP poisoning on and the victims don't reappear

**Comment by LocutusOfBorg** [comment]
no, killing it stops the poisoning, but force killing makes people have internet issues because they will still try to reach your laptop

**Comment by sayan-sibyl** [comment]
so what do I do now?

**Comment by sayan-sibyl** [comment]
So what should I do now?

**Comment by sayan-sibyl** [comment]
?

**Comment by LocutusOfBorg** [comment]
I don't even know what you want to do.

**Comment by sayan-sibyl** [comment]
Go this site http://picateshackz.com/2015/05/man-in-middle-attack-using-ettercap-in.html
These steps are for kali linux and I am on macOS so how to execute these steps in mac?

**Comment by sayan-sibyl** [comment]
I also tried to open the /etc/ettercap/etter.conf file via terminal using (open -a TextEdit ) command as I don't have any other editor but terminal says file not found and I have a ettercap folder only in /usr/local/cellar/ettercap/0.8.2_1 ,I don't have any other ettercap folder in my mac nor in /etc neither anywhere else
![screen shot 2017-07-20 at 11 57 15 pm](https://user-images.githubusercontent.com/29756523/28432857-2f5068ce-6da7-11e7-9107-9b1dbd67ab7e.png)

**Comment by LocutusOfBorg** [comment]
if you compile ettercap in debug mode you can see in the log where it tried to start it
