### ISSUE TITLE
Can I delete the ettercap folder which I downloaded from the downloads page in Ettercap's official website

### ISSUE THREAD

**Issue by sayan-sibyl** [Ettercap/ettercap#810]
Can I delete the ettercap folder which I downloaded from the downloads page in Ettercap's official website after the installation is complete
![screen shot 2017-07-13 at 9 17 53 pm](https://user-images.githubusercontent.com/29756523/28175041-c1fd19d4-6810-11e7-8208-7259738fb91c.png)

**Comment by koeppea** [comment]
After make install yes as long as you don't plan to make use of the uninstall target.
