### ISSUE TITLE
sometimes program/ettercap hangs

### ISSUE THREAD

**Issue by sayan-sibyl** [Ettercap/ettercap#812]
sometimes the program/ettercap hangs while stopping mitm attacks so I simply force quit the terminal app and Ettercap to end the process so my question does that leaves the process of ARP poisoning on and the victims don't reappear

Please help and what should I do now that I have force killed ettercap and the victims are still looking for my laptop? as I am the MITM attacker!

**Comment by LocutusOfBorg** [comment]
Did you wait enough time? Are you using gtk/curses or terminal based one?
can you please try the latest git?

**Comment by sayan-sibyl** [comment]
Are you using gtk/curses or terminal based one?
ans:- gtk one

**Comment by LocutusOfBorg** [comment]
please explain exactly what you do to get the hang, and please try with a git-built version

**Comment by LocutusOfBorg** [comment]
(on the git repo there are instructions to report bugs and to compile from git)

**Comment by sayan-sibyl** [comment]
so it happened like this I started unified sniffing then stopped it then scanned for hosts added two targets and then started arp poisoning (poison only one way) then after my work was done I mean just to surf the internet at max bandwith I turned off mitm attacks and just then the program I mean the UI of ettercap hanged there was this spinning wheel of death on the screen of my mac

**Comment by LocutusOfBorg** [comment]
ok, so please try the latest repo, and provide informations, such as OS ARCH ETTERCAP VERSION and so on
