### ISSUE TITLE
GTK* failed to intialize

### ISSUE THREAD

**Issue by flix59** [Ettercap/ettercap#815]
When i start ettercap without sudo i can't sniff if i start it with sudo or in root i get that error:
"ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

No protocol specified

GTK+ failed to initialize. Is X running?"
i hope someone can help me i think i searched in every thread already.

**Comment by mafiya69** [comment]
which os, dm/wm are you using?

**Comment by flix59** [comment]
i am using fedora linux,
and used ettercap -G

**Comment by koeppea** [comment]
I think the DISPLAY variable isn't set and most probably not authorized to use the X-Session.
As non-root:
```
xauth extract $DISPLAY - | sudo -i xauth merge -
```

**Comment by flix59** [comment]
i get the error:
"xauth:  file /home/felix/.Xauthority does not exist
xauth: (argv):1:  bad display name "-" in "extract" command
No matches found, authority file ":0" not written" 
so i tried xauth list to see which there are and i got basicaly the same error:
"xauth:  file /home/felix/.Xauthority does not exist"

**Comment by koeppea** [comment]
Just because I had the same issue with my FreeBSD VM:
![grafik](https://user-images.githubusercontent.com/4201853/29795581-22b53da0-8c4d-11e7-8b74-dac265004283.png)

Root-Shell = csh
If Root-Shell == bash, then `export DISPLAY=:0.0`

**Comment by kholia** [comment]
Here is what worked for me on Fedora 25,

``` bash

$ xhost local:root

$ sudo ettercap -G
```

**Comment by KalpitSuthar** [comment]
Thank u @kholia
