### ISSUE TITLE
I didn't  find the etter.dns file  on MacOSX

### ISSUE THREAD

**Issue by cssxn** [Ettercap/ettercap#819]
I was using brew command to install ettercap

**Comment by sayan-sibyl** [comment]
how did u setup ettercap in mac pls tell me for the last two months I am trying to install ettercap in mac

**Comment by koeppea** [comment]
Guys if you think you're online at the same time, our IRC channel #ettercap-project on Freenode may be more efficient.
I try to be there as most as I can even though free time is quite challenging for me at the moment.

**Comment by LocutusOfBorg** [comment]
please use strace to see where ettercap is searching it, and put it there.
btw this is probably something that brew team has to solve
