### ISSUE TITLE
Sniffing during a Mitm not working

### ISSUE THREAD

**Issue by KJ202** [Ettercap/ettercap#822]
Hello,

I'm trying to sniff the traffic doing an ARP poisoning Mitm. 
The Mitm works well as I can see all the packet in Wireshark. However, Ettercap doesn't show me any HTTP request when I connect to some sites (and not HTTPS I check for that). It doesn't sniff anything actually.
To give the context, I'm doing this in my local network in a Kali distri running on a VM configured in bridged mode. I use the graphical interface of Ettercap and I set up "Unified sniffing". 

Is there something I'm missing ?

**Comment by sgeto** [comment]
Can you give more information?
Among other things:
What's your network topology?
Is sniffing/promiscuous mode enabled?
Can you see your target's ip in the "Host List"?
Are you seeing the HTTP POST requests in wireshark?
What wireshark? The one in kali or the one on your host OS?
VMware/virtualbox? HyperV :-P?
Network adapter settings?
Host OS?

**Comment by KJ202** [comment]
Hello, 
Thank you four your answer. 
Actually the problem was solved this morning. 
The reason : I activated ip_forwarding ont the VM but not on my computer. 

Thanks again.

Best regards.

**Comment by m3sz** [comment]
KJ202,

What did you do exactly to forwards the ports on your computer?

**Comment by sgeto** [comment]
@m3sz
Please see ettercap's documentation or open a new issue if the problem persists.
