### ISSUE TITLE
DNS Spoofing DOSes Victim

### ISSUE THREAD

**Issue by matan-arkin** [Ettercap/ettercap#824]
I'm trying to do a simple DNS spoof on my local home Wi-Fi. To execute the attack, I'm using a Kali virtual machine, from Oracle VM Virtual Box.

Under settings in Virtual Box -> Network tab, I have "Enable Network Adapter" checked and "Attached to" set to "Bridged Adapter".

I'm following [this tutorial](https://www.youtube.com/watch?v=Y3j-rlA0CbE&t=566s). Tried both the GUI and command line versions of Ettercap, but both seem to create the same result: the victim is DOSed and seems to have no internet connection.

Sniffing doesn't shed much light on the mystery: Wireshark doesn't pick up any packets with the victim's IP. And still, I'm able to ping back and forth between the attacker and victim no problem.

Any idea why this isn't working and how to make it work?

Would very much appreciate any help, or just your thoughts.

Thanks!

**Comment by sgeto** [comment]
Run `arp -a` on the victims machine. Among other things, should display two IP adresses with your (the attacker) MAC adress. Your real IP + Your MAC and the gateway IP (or whatever you are pretending to be) + your MAC.

If that's true then use `nslookup` + the hostname you're spoofing. It should resolve to your real (local) IP adress.

**Comment by koeppea** [comment]
Firstly we don't know which version of ettercap you're running.
The best is, to run the latest codebase from github.
Secondly, some technical information and some debug logfile would be helpful.

For me it sounds like doing ARP poisoning w/o Sniffing (forwarding) started.

**Comment by LocutusOfBorg** [comment]
I agree, adding sniffing should do the trick
