### ISSUE TITLE
iNVALID ENTRY IN ETTER.CONF LINE: 50

### ISSUE THREAD

**Issue by talal2** [Ettercap/ettercap#831]
Hi !

When i write in terminal -> ettercap -G, i got this error: http://prntscr.com/glcld7

This is my etter.conf file: https://ghostbin.com/paste/9y6ws

                       Thanks in advance ;) :)

**Comment by koeppea** [comment]
It seems your system has a old version of libettercap hanging around, which the current ettercap binary is linking against.

I suggest to completely purge any ettercap installation, possibly also manually purge orphaned library files:
```
find /usr -name 'libettercap*' | rm -v
```
and reinstall. 
If you then still have the same issue, you need to build ettercap from Github Source in Debug mode and reproduce the issue. 

HTH
