### ISSUE TITLE
arp_poisoning_confirm seems poisoning both targets even in oneway mode

### ISSUE THREAD

**Issue by Cai41** [Ettercap/ettercap#836]
While I am using "arp: oneway target1 target2", I found sometimes target2 will also be poisoned. At the beginning, ettercap will only repeatedly send arp reply to poison target1, but when target2 sends arp request about target1, ettercap will also send one poisoned reply to target2 pretending target1, no matter whether "oneway" is specified. I looked at the source code and think it might because of arp_poisoning_confirm  function.
Is it supposed to behave this way? Since I thought "oneway" is specified, no matter what ettercap shouldn't poison target2.

**Comment by koeppea** [comment]
Oh yes. You're right. the arp_poisonin_confirm function doesn't honor the oneway option.
Do you want to volunteer creating a pull request correcting this? Or shall I create one?

**Comment by eaescob** [comment]
@Cai41 do you mind testing with the proposed PR?

**Comment by LocutusOfBorg** [comment]
closing in the meanwhile...
