### ISSUE TITLE
filters don't work

### ISSUE THREAD

**Issue by spellr** [Ettercap/ettercap#84]
I cant use ettercap filters. I'm writing even the most simple filter I can think of:

if (ip.proto == TCP){
    msg("Ran Filter\n");
}

But even that doesn't work. When I compile it using etterfilter and run:

sudo ettercap -F /tmp/filter.ef -T -M arp -i wlan1 /192.168.1.6/ //

the msg is not printed. With the packet visualization I do see TCP packets, but the filter seem to just not working even though ettercap says "Content filters loaded from /tmp/filter.ef".

To solve this I've tried enabling ip_forward, and I've tried deleting the "#" sign in /etc/etter.conf so it will use iptables for it's redir_command (lines 168-169)

I'm using ettercap NG-0.7.4.2 on Ubuntu 12.10

**Comment by Silur** [comment]
same problem with 0.8.2

**Comment by koeppea** [comment]
This is a quite old issue.
Please try if it's still the case when using the latest codebase from github.
If it is still the case please open a new issue and provide the information as described in **README.BUGS**
