### ISSUE TITLE
Why do these weird link local addresses appear while scanning for Hosts in 'Ettercap' ? 

### ISSUE THREAD

**Issue by ayan-das1234** [Ettercap/ettercap#841]
Whenever I scan for hosts in 'ettercap' I get weird link local addresses like this: fe80::8616:f9ff:fe51:4a:0b and whenever I try to change them to IPv4 address by selecting 64 prefix the online IP converter sites return that this is an invalid IP address

![screen shot 2017-10-11 at 9 03 10 pm](https://user-images.githubusercontent.com/31272145/31451204-2461bf54-aec9-11e7-8ca0-8717f9e73ce2.png)

**Comment by sayan-sibyl** [comment]
I also get these link-local addresses!

**Comment by koeppea** [comment]
To me they don't look weird.
They're (as you already mentioned) link-local IPv6 addresses.
Of course, IPv6 has no much in common with IPv4, hence the tools for IPv4 mostly doesn't work for IPv6.
So in general, I can't see any issue here. Looks all good to me.
Maybe you describe your problem more precisely.

**Comment by sayan-sibyl** [comment]
Do you know how to convert this link local addresses to IPv4 addresses in order to mess with the network settings since macOS considers link-local addresses as invalid

**Comment by LocutusOfBorg** [comment]
I don't think you can "convert" them to ipv4 addresses, different protocols, different everything.
(fe80 is local)

**Comment by koeppea** [comment]
IPv6 addresses cannot be converted to IPv4 addresses. They're completely separated.
If don't see any IPv4 addresses, there may be no IPv4 enabled hosts on your network.
Have you redone the test with a ettercap installation build from latest Github source?
Maybe you wan to check out our Wiki regarding this topic.
