### ISSUE TITLE
Reading .eci file 

### ISSUE THREAD

**Issue by yasharvindsingh** [Ettercap/ettercap#846]
Every time i try to read the log file saved in /tmp/logfile.eci it gives me segmentation fault but when i check for its contents in a normal text editor its there all in binary format.

**Comment by koeppea** [comment]
Please try the latest code from Github. Especially segfault bugs in etterlog have just recently been fixed.

**Comment by sgeto** [comment]
@yasharvindsingh I am closing this, Feel free to reopen if your issue is still unresolved.
