### ISSUE TITLE
Ettercap not run in ubuntu 17.10 

### ISSUE THREAD

**Issue by fathurwl** [Ettercap/ettercap#849]
i trying install ettercap, from my ubuntu machine.
i use ubuntu 17.10,

I did not find any problems on the bettercap installation

but if i run ettercap with root access,  i found problem, 

┌─[✗]─[tur@snsv]─[~]
└──╼ $sudo ettercap -G

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

No protocol specified

GTK+ failed to initialize. Is X running?

how do i fix it bro ?

**Comment by LocutusOfBorg** [comment]
works for me, please use ettercap-pkexec.

**Comment by Monkleys** [comment]
I have the same issue, even when running ettercap-pkexec
On Ubuntu 17.10

**Comment by koeppea** [comment]
Thanks @Monkleys 
I've created a Wiki page for this re-occurring issue.
Please review: [Wiki: X DISPLAY issue with sudo](https://github.com/Ettercap/ettercap/wiki/X-DISPLAY-issue-with-sudo)

**Comment by LocutusOfBorg** [comment]
We switched away from wayland in 18.04, we should probably look how Fedora is running or patching ettercap to work with wayland.
Splitting graphical (non root) to core (root) should be the "right thing to do"
