### ISSUE TITLE
Ettercap filter writing hexa values into captured packets | Kerberos replay attack

### ISSUE THREAD

**Issue by Newn00b** [Ettercap/ettercap#85]
Hello, 

I'm working on a filter that would catch all the AS-REQ that a client would send to its KDC in order to downgrade the cipher negocation.

I first tried to replay the packet on the fly but, as far as know/understood, it seems that the function pcre_regex() can indeed substitute on value to another BUT the replaced payload is written in ASCII in the data part.
To downgrade kerberosv5 cipher negociation from aes to des, you need to spoof a AS-REQ (MitM required :) ) and replay it with some hexa values changed (values of the cipher).

Here's the regex i wrote down that should downgrade all the client proposal cipher to des (0x03):

 if (pcre_regex(DECODED.data, "\x12.{2}\x11.{2}\x17.{2}\x18.{2}\xff\x79.{2}\x03")) 

which actually matches the values i want. So this regex is able to detect when an AS-REQ is coming from a client that's about to negociate it's cipher algo with the server. Replacing these values to "\x03" actually write in ASCII in the DATA part "\x03".

Question is : Is there any way i can write a filter that could actually replace these matching regex values to mine ? in this case \x03. It seems weird ettercap filters are able to view the hexa part of a packet but is not able to write into it...

I tried to log() the incoming client packet, modify it with hexedit, and used drop() and replay() function to drop the actual client request and replay my forged packet but i obviously have time skew issues... Not even talking about TCP sessions that aren't the same. 

Best way remains to replay the packet on the fly but I still didn't figured out how i could achieve this, assuming ettercap filter can handle this :)

Any help would be much appreciated :)

Thanks !

**Comment by kholia** [comment]
https://github.com/Ettercap/ettercap/pull/826 (Implement etype downgrade attack on Kerberos V5) solves this issue.

**Comment by sgeto** [comment]
All good then.
