### ISSUE TITLE
GTK error on mac os 

### ISSUE THREAD

**Issue by alexmozzhakov** [Ettercap/ettercap#850]
An error stays:
`Gtk-CRITICAL **: gtk_image_get_pixbuf: assertion 'image->storage_type == GTK_IMAGE_PIXBUF || image->storage_type == GTK_IMAGE_EMPTY' failed
`
https://github.com/Ettercap/ettercap/blob/ffb742e7a69bfc6fa71cac6bcd43cdf227eb2136/src/interfaces/gtk/ec_gtk.c#L917-L926
I wonder what this check is about, because ettercap.png and ettercap.svg end up being in the same "share" folder. That's why my proposal is to remove ettercap.svg, simplify this code and change to ([gdk_pixbuf_new_from_file](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-File-Loading.html#gdk-pixbuf-new-from-file))

**Comment by LocutusOfBorg** [comment]
Can you please send a pull request?
BTW the use case is to try to load the system available icon, and fallback into a local one in case of custom built ettercap program.

e.g. when you run it with ./ettercap -G

**Comment by alexmozzhakov** [comment]
@LocutusOfBorg, I will send pull request in a few hours.
