### ISSUE TITLE
 PROBLEM WITH ETTERCAP

### ISSUE THREAD

**Issue by sh4dyXX** [Ettercap/ettercap#853]
SEND L3 ERROR: 1378 byte packet (0800:11) destined to 172.217.30.3 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (Message too long)
)
SEND L3 ERROR: 1400 byte packet (0800:06) destined to 192.168.0.101 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (Message too long)
)
SEND L3 ERROR: 1400 byte packet (0800:06) destined to 192.168.0.101 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (Message too long)
)
SEND L3 ERROR: 1400 byte packet (0800:06) destined to 192.168.0.101 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (Message too long)
)
SEND L3 ERROR: 1400 byte packet (0800:06) destined to 192.168.0.101 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (Message too long)
)
SEND L3 ERROR: 1400 byte packet (0800:06) destined to 192.168.0.101 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (Message too long)
)
SEND L3 ERROR: 1400 byte packet (0800:06) destined to 192.168.0.101 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (Message too long)
)
SEND L3 ERROR: 1378 byte packet (0800:11) destined to 172.217.30.3 was not forwarded (libnet_write_raw_ipv4(): -1 bytes written (Message too long)

How can I solve it?

**Comment by koeppea** [comment]
Hi,

this can have plenty reasons.
But you didn't told anything beside the error messages, so they're completely out of context.
Generally we recommend the following:

1. purge an older (packaged) version of ettercap and libettercap from the system to avoid linking issues
2. clone the latest master from Github (many bugs have been fixed even compared to the latest released verion)
3. read the **README** and **INSTALL** file. There you find everything you need to compile the source code
4. compile in Debug mode: `cmake -DCMAKE_BUILD_TYPE=Debug ..` (executed in *build* directory)
5. read the **README.BUGS** for instructions to properly gather information that help to understand the issue and envirnonment. Include the _ettercap-0.8.2_debug.log_
6. reproduce the issue

**Comment by sgeto** [comment]
Yet another ghost issue...
