### ISSUE TITLE
GUI Crashes with new OSX

### ISSUE THREAD

**Issue by InkedCurtis** [Ettercap/ettercap#856]
Hey, I recently installed MacOS High Sierra and since updating it's gone from working perfect to not working at all, It crashes with the following error:

```ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

2017-12-13 00:23:52.038 ettercap[53857:572889] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

(<unknown>:53857): Gtk-CRITICAL **: gtk_image_get_pixbuf: assertion 'image->storage_type == GTK_IMAGE_PIXBUF || image->storage_type == GTK_IMAGE_EMPTY' failed
ERROR : 6, Device not configured
[/tmp/ettercap-20170725-19172-1x0hcjp/ettercap-0.8.2/src/ec_capture.c:capture:91]

 Error while capturing: The interface went down 

ERROR : 6, Device not configured
[/tmp/ettercap-20170725-19172-1x0hcjp/ettercap-0.8.2/src/ec_send.c:send_arp:319]

 libnet_write (-1): libnet_write_link(): -1 bytes written (Device not configured)
```

To produce this error & for the GUI to crash, all I did was running `sudo ettercap -G` and from the GUI I did the following:

- Sniff > Unified Sniffing 
- en06 (my wireless card)
- Hosts > Scan For Hosts
- Hosts List (removed all unnecessary hosts)
- MITM > ARP Poisoning > Sniff Remote Connections

The GUI then freezes and throws that error shown above.

**Comment by koeppea** [comment]
Have you build it from GitHub or brew?
Please refer to our Wiki. I spent a separate article for using the latest code base, natively compiled on Mac OS X.

So I ask you to try to reproduce with ettercap built from source.

**Comment by sgeto** [comment]
No reply...

**Comment by InkedCurtis** [comment]
I can confirm this is still the case, although it only applies when I do something like enter text into the filter field

**Comment by hviniciusg** [comment]
Same problem... when i try to enter some text, gui freezes

**Comment by koeppea** [comment]
Can you check out the wiki? 
I’ve described how to build ettercap using Mac ports instead of home brew.
This way the issue doesn’t occur however looking not that nice as with brew.
