### ISSUE TITLE
Ettercap sniffer has stopped working

### ISSUE THREAD

**Issue by Modronic** [Ettercap/ettercap#86]
When i choose my network adapter under "Unified Sniffing" i get the message on the title .. Please help i searched for hours but couldn't find the reason also my drivers and wincap is up to date, Thnx

**Comment by Willim777** [comment]
hi

**Comment by Willim777** [comment]
Im using windows 10 and still im getting that error il tryed to upgrade down grade im not sure  what to try anymore ? coz cain aint workin for me? cant see any facebook info or anthing lil thatn please help would be  wellcome thanks ")
