### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by hogun97** [Ettercap/ettercap#863]
[root@ip-172-31-5-173 ~]# wget https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz
[root@ip-172-31-5-173 ~]# tar -zxvf cmake-3.6.2.tar.gz
[root@ip-172-31-5-173 ~]# cd cmake-3.6.2
[root@ip-172-31-5-173 cmake-3.6.2]# sudo ./bootstrap --prefix=/usr/local
[root@ip-172-31-5-173 cmake-3.6.2]# sudo make
[root@ip-172-31-5-173 cmake-3.6.2]# sudo make install
[root@ip-172-31-5-173 cmake-3.6.2]# vi ~/.bash_profile
PATH=/usr/local/bin:$PATH:$HOME/bin
[root@ip-172-31-5-173 ~]# cmake --version
cmake version 3.6.2

I used these command lines to intall CMake and then used:

cmake -DWITH_BOOST=/usr/local/boost_1_59_0 

to use boost using CMake.  However, it shows the following error:

CMake Error at CMakeLists.txt:52 (include):
   include could not find load file:
      /home/rocket/Source/Checks/cm_c11_thread_local.cmake 

and five more that seem to be similar errors.
*rocket is a user directory

What exactly does this error mean and how do I go about solving it? Thanks

**Comment by sgeto** [comment]
ahm...

Is this related to ettercap?

**Comment by LocutusOfBorg** [comment]
please report to cmake users, or install cmake with the facilities provided for your OS
