### ISSUE TITLE
Make failed 

### ISSUE THREAD

**Issue by Jallot** [Ettercap/ettercap#864]
zerogoki@zerohost:~/progs/ettercap-0.8.2/build$ make

Scanning dependencies of target libnet
[  0%] Built target libnet
Scanning dependencies of target lib_ettercap
[  0%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_mem.c.o
[  1%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_capture.c.o
[  1%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_checksum.c.o
[  2%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_conf.c.o
[  2%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_connbuf.c.o
[  2%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_conntrack.c.o
[  3%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_debug.c.o
[  3%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_decode.c.o
[  3%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_dispatcher.c.o
[  4%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_dissect.c.o
[  4%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_encryption_ccmp.c.o
[  5%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_encryption_tkip.c.o
[  5%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_encryption.c.o
[  5%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_error.c.o
[  6%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_exit.c.o
[  6%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_file.c.o
[  6%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_filter.c.o
[  7%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_fingerprint.c.o
[  7%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_format.c.o
[  8%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_globals.c.o
[  8%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_hash.c.o
[  8%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_hook.c.o
[  9%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_inet.c.o
[  9%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_inject.c.o
[  9%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_log.c.o
[ 10%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_manuf.c.o
[ 10%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_mitm.c.o
[ 11%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_network.c.o
[ 11%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_packet.c.o
[ 11%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_passive.c.o
[ 12%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_plugins.c.o
[ 12%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_poll.c.o
[ 12%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_profiles.c.o
[ 13%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_resolv.c.o
[ 13%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_scan.c.o
[ 14%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_send.c.o
[ 14%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_services.c.o
[ 14%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_session.c.o
[ 15%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_set.c.o
[ 15%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_signals.c.o
[ 15%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sleep.c.o
[ 16%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sniff_bridge.c.o
[ 16%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sniff.c.o
[ 17%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sniff_unified.c.o
[ 17%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_socket.c.o
[ 17%] Building C object src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o
/home/zerogoki/progs/ettercap-0.8.2/src/ec_sslwrap.c: In function ‘sslw_create_selfsigned’:
/home/zerogoki/progs/ettercap-0.8.2/src/ec_sslwrap.c:978:13: error: dereferencing pointer to incomplete type ‘X509_EXTENSION {aka struct X509_extension_st}’
          ext->value->data[7] = 0xe7;
             ^~
src/CMakeFiles/lib_ettercap.dir/build.make:1142: recipe for target 'src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o' failed
make[2]: *** [src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o] Error 1
CMakeFiles/Makefile2:249: recipe for target 'src/CMakeFiles/lib_ettercap.dir/all' failed
make[1]: *** [src/CMakeFiles/lib_ettercap.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by Jallot** [comment]
I've installed all dependencies but it still doesn't compile

**Comment by alexmozzhakov** [comment]
Can you provide some more information about your system configuration?

**Comment by Jallot** [comment]
Linux zerohost 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**Comment by sgeto** [comment]
I am afraid that's not enough information.
Try again?

**Comment by koeppea** [comment]
> I've installed all dependencies but it still doesn't compile

No you didn't. The missing dependency is packaged as _libssl-dev_.

Read the **README**
```
apt-get install debhelper bison check cmake flex ghostscript libbsd-dev libcurl4-openssl-dev libgtk2.0-dev \
 libltdl-dev libluajit-5.1-dev libncurses5-dev libnet1-dev libpcap-dev libpcre3-dev libssl-dev libgtk-3-dev

```
