### ISSUE TITLE
only one group is poisioned

### ISSUE THREAD

**Issue by fangdong116** [Ettercap/ettercap#874]
I have this command; but why only one group is poisioned; thank you for help.

[root@xk-pt-nginx-cwz-01 ettercapFilter]# ettercap -T -M arp:remote /192.168.1.43/ /192.168.1.97/

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

Listening on:
  eth1 -> 52:54:00:3C:2C:E0
          192.168.1.120/255.255.255.0
          fe80::5054:ff:fe3c:2ce0/64

SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to EUID 65534 EGID 65534...

  32 plugins
  42 protocol dissectors
  57 ports monitored
20388 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services

Scanning for merged targets (2 hosts)...

* |==================================================>| 100.00 %

4 hosts added to the hosts list...

ARP poisoning victims:

 GROUP 1 : 192.168.1.43 52:54:00:9C:BC:6B

Starting Unified sniffing...

Text only Interface activated...
Hit 'h' for inline help

**Comment by koeppea** [comment]
Can you please build ettercap from the latest source on GitHub in Debug mode. Then retry and if the issue persists, please provide the ettercap_debug log file.

**Comment by koeppea** [comment]
@fangdong116 Any update?

**Comment by fangdong116** [comment]
sorry, but it is difficult for me to reinstall the ettercap. My friend helped me bulid the  source code and installed it, but it is difficult for me. I am not familar with Linux.

**Comment by sgeto** [comment]
If you're not familiar with linux, then how can you tell/know that only one group is being poisoned?

**Comment by koeppea** [comment]
Poisoning both groups works when we try to reproduce the issue. So it's for us not reproducable.
I've to assume that your TARGET2 is not responding to PING and ARP, hence invisible for ettercap.
Without the debug logfile, we can't really help you.
Maybe your friend can help you.
You can also try to reach somebody out in our IRC channel to interactively help you with building ettercap from latest source in Debug mode.
