### ISSUE TITLE
Etterfilter output as core Dump

### ISSUE THREAD

**Issue by vpsquare** [Ettercap/ettercap#881]
When I run the etterfilter command 

                              etterfilter dos.elt -o dos.ef

The output obtained is a core dump.

       Segmentation fault (core dumped)

Is this a known issue?

**Comment by koeppea** [comment]
Hi, yes it’s a known issue and will be fixed in the next release.
PR #880 is aiming to fix this and already works for Linux where ettercap is build with gcc.

Hence closing this issue.

**Comment by sabahsuhail** [comment]
Hi I am also facing this issue got output Segmentation fault (core dumped). Could you please guide how to solve it

**Comment by koeppea** [comment]
You have to upgrade to the most recent version 0.8.3.1

**Comment by sabahsuhail** [comment]
> You have to upgrade to the most recent version 0.8.3.1

I am using ettercap with mininet on my VirtualBox (ubuntu 18.04). I try to uninstall the older version but reinstalling results in 0.8.2 
Can you kindly please suggest some solution

**Comment by LocutusOfBorg** [comment]
@sabahsuhail this ppa [1] automatically builds and creates deb files for stable Ubuntu releases automatically when a new commit reaches this git (master branch).

[1] https://code.launchpad.net/~costamagnagianfranco/+archive/ubuntu/ettercap-stable-backports

**Comment by sabahsuhail** [comment]
> @sabahsuhail this ppa [1] automatically builds and creates deb files for stable Ubuntu releases automatically when a new commit reaches this git (master branch).
> 
> [1] https://code.launchpad.net/~costamagnagianfranco/+archive/ubuntu/ettercap-stable-backports

I didn't understand. I would really appreciate if you can guide me more on that. I have to uninstall and then reinstall ettercap graphical?

**Comment by LocutusOfBorg** [comment]
You can update your system with unsupported packages from this untrusted PPA by adding ppa:costamagnagianfranco/ettercap-stable-backports to your system's Software Sources. (Read about installing)

sudo add-apt-repository ppa:costamagnagianfranco/ettercap-stable-backports
sudo apt-get update
        

its written how to add it.
