### ISSUE TITLE
Errors in generators

### ISSUE THREAD

**Issue by parampopat** [Ettercap/ettercap#882]
I get these while using Visual Studio 14 2015

CMake Error at CMakeLists.txt:11 (include):
  include could not find load file:

    cmake_utils/set_compiler_specific_options.cmake

CMake Error at CMakeLists.txt:18 (include):
  include could not find load file:

    cmake_utils/release_build_by_default

CMake Error at CMakeLists.txt:19 (include):
  include could not find load file:

    cmake_utils/use_cpp_11.cmake

CMake Error at CMakeLists.txt:401 (include):
  include could not find load file:

    cmake_utils/check_if_neon_available.cmake

CMake Error at CMakeLists.txt:748 (enable_cpp11_for_target):
  Unknown CMake command "enable_cpp11_for_target".

**Comment by sgeto** [comment]
Are you sure you're building ettercap? 😆

**Comment by koeppea** [comment]
Yeah I think you mix something up here. Ettercap doesn’t have auch files.
