### ISSUE TITLE
Ettercap will not install

### ISSUE THREAD

**Issue by amateur02** [Ettercap/ettercap#887]
Hello! I tried to install Ettercap, as described in the YouTube video, on my OS X El Capitan. I tried it several times with no success. At the end of the configuration it tells me configuration incomplete. It shows cmake: 137, cmake: 378 and cmake: 92 (please see picture Install Version 1). I also tried to install it with: brew install --HEAD ettercap --with-gtk+. It also failed. This time it showed " [47%] Built target lib_ettercap make: *** [all] Error 2 (please see picture Install Version 2). I'm not really a computer savvy. So, if you could provide some help, it would be highly appreciated. If you need more information, or anything for me to do, please let me know. The only thing is, unfortunately, you need to tell me step by step. Sorry...but I'm still learning.

![install version 1](https://user-images.githubusercontent.com/37872064/38033242-e5f579f8-329f-11e8-8f35-7801d47ea6ab.png)

![install version 2](https://user-images.githubusercontent.com/37872064/38033250-eb0dabc2-329f-11e8-816c-28978bc899df.png)

[CMakeError.log](https://github.com/Ettercap/ettercap/files/1856241/CMakeError.log)
[CMakeOutput.log](https://github.com/Ettercap/ettercap/files/1856242/CMakeOutput.log)

**Comment by sgeto** [comment]
Now that's what I call a bug report!
Nicely done.

Anyways, there is this special character that looks like a tilted single quote. On a US keyboard, it shares a button with the tilde (~) .
Use them to surround the brew command instead of (').
I would show you the character, but I'm writing this from an iPhone I'm stuck with ever since I've managed to break my real phone.

**Comment by koeppea** [comment]
@amateur02 you typed 
```
cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_IPV6=ON -DOPENSSL_ROOT_DIR='brew --prefix openssl' ..
```
The right call would be using back-ticks instead of single-quotes:
```
cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_IPV6=ON -DOPENSSL_ROOT_DIR=`brew --prefix openssl` ..
```

The commands are additonally provided in our Wiki.

**Comment by amateur02** [comment]
Hey guys!
Thank you for the swift response. I will try it as soon as possible. Going to let you know about the
result. Any idea why the second version with brew install --HEAD ettercap --with-gtk+ also did not
work? Would be less chance to make mistakes.

**Comment by koeppea** [comment]
We're no managing the brew formulas. Therefore we cannot tell for **brew**.

**Comment by amateur02** [comment]
Hello!
Again, thanks for the swift response. We are almost there, thanks to you. I tried it once again, this time with back-ticks. The installation went thru, I could get it started and it seems to do something, but my graphic user interface has some bugs as you can see on the attached pictures. 
Is there anything I could do to fix it? I will also attach the debug file, maybe you can make any sense of
it.
![bildschirmfoto 2018-03-30 um 15 42 09](https://user-images.githubusercontent.com/37872064/38143038-11803c70-343f-11e8-93ee-7cc700adb6cb.png)
![bildschirmfoto 2018-03-30 um 15 43 13](https://user-images.githubusercontent.com/37872064/38143042-16c23008-343f-11e8-80b9-11e76e177dd0.png)
[ettercap-0.8.2_debug.log](https://github.com/Ettercap/ettercap/files/1863965/ettercap-0.8.2_debug.log)

**Comment by koeppea** [comment]
You need to install **adwaita-icon-theme** using *brew*.
I'll amend the Video and Wiki description.

**Comment by amateur02** [comment]
Done! Now it looks like something (see picture)!! You are awesome!
Thanks for guiding me thru this installation. That's what I call a good support!!!

![bildschirmfoto 2018-03-31 um 13 36 36](https://user-images.githubusercontent.com/37872064/38162869-712fef1c-34e9-11e8-897b-2ad9b92b4819.png)

**Comment by koeppea** [comment]
You're welcome.
