### ISSUE TITLE
DNS Sppof websites with SSL/HTTPS

### ISSUE THREAD

**Issue by talal2** [Ettercap/ettercap#890]
Hi !

When i spoof websits WITHOUT HTTPS, It works !
But websites with HTTPS, like facebook/youtube, Attack dsnt work 

                            Any solution ?

**Comment by koeppea** [comment]
DNS spoofing works independently from any application protocol.

Since this kind of question comes up more often I’ll dedicate a wiki page answering that.

**Comment by koeppea** [comment]
I'm afraid I've to close this as there is no solution. At least not know to me.
Further info to be found on the newly created informational [Wiki page](https://github.com/Ettercap/ettercap/wiki/HTTPS-and-HSTS).
