### ISSUE TITLE
CMAKE_C_FLAGS_RELEASE ignored

### ISSUE THREAD

**Issue by juanitotc** [Ettercap/ettercap#894]
I'm trying to compile ettercap-0.8.2 with "-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-flto -fuse-linker-plugin -mtune=generic -Os -pipe"",  but CMAKE_C_FLAGS_RELEASE remains set to "-O2 -w -D_FORTIFY_SOURCE=2".

This looks to be fixed on purpose, it there a reason for it?

**Comment by sgeto** [comment]
Yes we noticed that. It's very inconvenient indeed. There may have been a need for that in the past.
https://github.com/Ettercap/ettercap/pull/891 is commited to fix this.
Please be patient.
In the meantime, you may patch this yourself by opening CMakeLists.txt and remove this line:

`set(CMAKE_C_FLAGS_RELEASE "-O2 -w -D_FORTIFY_SOURCE=2" CACHE STRING "" FORCE)`

See https://github.com/Ettercap/ettercap/pull/891/commits/45b22471ac03031562c868d52ed2fd8c2ad7aec9

**Comment by koeppea** [comment]
Closing due to fixed in #891
