### ISSUE TITLE
Building against ncursesw

### ISSUE THREAD

**Issue by juanitotc** [Ettercap/ettercap#895]
When trying to build ettercap-0.8.2 against ncursesw, "make" fails with:

[ 65%] Linking C executable ettercap
cd /usr/src/ettercap-0.8.2/build/src && /tmp/tcloop/cmake/usr/local/bin/cmake -E cmake_link_script CMakeFiles/ettercap.dir/link.txt --verbose=1
/usr/local/bin/cc -O2 -w -D_FORTIFY_SOURCE=2  -rdynamic CMakeFiles/ettercap.dir/ec_parser.c.o CMakeFiles/ettercap.dir/ec_main.c.o  -o ettercap -Wl,-rpath,/usr/src/ettercap-0.8.2/build/src:/usr/local/lib: interfaces/libec_interfaces.a libettercap.so.0.0.0 /usr/local/lib/libncursesw.so /usr/local/lib/libformw.so /usr/local/lib/libmenuw.so /usr/local/lib/libpanelw.so /usr/local/lib/libfreetype.so /usr/local/lib/libglib-2.0.so /usr/local/lib/libgobject-2.0.so /usr/local/lib/libgdk_pixbuf-2.0.so /usr/local/lib/libgdk-3.so /usr/local/lib/libgtk-3.so /usr/local/lib/libcairo.so /usr/local/lib/libpango-1.0.so /usr/local/lib/libatk-1.0.so -lgthread-2.0 /usr/local/lib/libssl.so /usr/local/lib/libcrypto.so -lz -lpthread -ldl /usr/local/lib/libpcap.so /usr/local/lib/libnet.so -lresolv /usr/local/lib/libpcre.so 
interfaces/libec_interfaces.a(wdg_file.c.o): In function `wdg_file_driver.isra.0':
wdg_file.c:(.text+0x1d5): undefined reference to `menu_driver'
wdg_file.c:(.text+0x1e0): undefined reference to `current_item'
wdg_file.c:(.text+0x1e8): undefined reference to `item_opts'
...

if I manually enter the command below at this point, "make" suceeds without further error.

/usr/local/bin/cc -O2 -w -D_FORTIFY_SOURCE=2  -rdynamic CMakeFiles/ettercap.dir/ec_parser.c.o
 CMakeFiles/ettercap.dir/ec_main.c.o  -o ettercap -Wl,-rpath,/usr/src/ettercap-0.8.2/build/src:/usr/local/lib: interfaces/libec_interfaces.
a libettercap.so.0.0.0 -L/usr/local/lib -lncursesw -lmenuw -lformw -lpanelw /usr/local/lib/libfreetype.so /usr/local/lib/libglib-2.0.so /us
r/local/lib/libgobject-2.0.so /usr/local/lib/libgdk_pixbuf-2.0.so /usr/local/lib/libgdk-3.so /usr/local/lib/libgtk-3.so /usr/local/lib/libc
airo.so /usr/local/lib/libpango-1.0.so /usr/local/lib/libatk-1.0.so -lgthread-2.0 /usr/local/lib/libssl.so /usr/local/lib/libcrypto.so -lz 
-lpthread -ldl /usr/local/lib/libpcap.so /usr/local/lib/libnet.so -lresolv /usr/local/lib/libpcre.so

**Comment by sgeto** [comment]
According to [FindCurses.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindCurses.cmake#L30):

> # Set ``CURSES_NEED_NCURSES`` to ``TRUE`` before the
> # ``find_package(Curses)`` call if NCurses functionality is required.

That behavior is unfortunately broken upstream. So it seems at least...
https://github.com/Ettercap/ettercap/pull/891 is commited to fix this.
Please be patient. You may report this error to cmake's devs as well.
See https://github.com/Ettercap/ettercap/pull/891/commits/0a9129c6a1e43298c7ef4175b8ce2451dafa03a8

**Comment by koeppea** [comment]
Closing due to addressed in #891
