### ISSUE TITLE
Ettercap, how to stop security warnings on non-spoofed sites.

### ISSUE THREAD

**Issue by Niall7459** [Ettercap/ettercap#896]
I am using ettercap, all works well.
When I enter "microsoft.com" It resolves to my custom web server, as expected.
When I enter other sites such as "sdassociation.org" or "google.com" I get security warnings for the ssl certificates

Im wondering if I am not touching these sites how come security warnings are thrown up.

My hosts file:`

microsoft.com      A   192.168.111.103
*.microsoft.com    A   192.168.111.103
www.microsoft.com  PTR 107.170.40.56      # Wildcards in PTR are not allowed
`

Sites that I am not spoofing throw up security issues. Is this a general limitaiton or have I configured something wrong.

**Comment by sgeto** [comment]
You must be touching these sites in some way. Else you wouldn't see a warning.
How does the warning look like?
You may also want to have a look at [this](https://github.com/Ettercap/ettercap/wiki/HTTPS-and-HSTS).

**Comment by koeppea** [comment]
Closing due to no reaction.
