### ISSUE TITLE
Typo in Ettercap Man page

### ISSUE THREAD

**Issue by seanlangley** [Ettercap/ettercap#900]
MacOS man page, under the MITM option, line 211: 
 -M, --mitm <METHOD:ARGS>
              MITM attack
              This  option will activate the man in the middle attack. The mimt attack is totally independent from the sniffing.

-- mimt should be replaced with mitm

**Comment by sgeto** [comment]
thanks. we'll see into that.

To quote from our README;

> Aoccdrnig to rscheearch at an Elingsh uinervtisy, it deosn't mttaer in waht
> oredr the ltteers in a wrod are, the olny iprmoetnt tihng is taht the frist
> and lsat ltteer are in the rghit pclae. The rset can be a toatl mses  and
> you can sitll raed it wouthit a porbelm. Tihs is bcuseae we do not raed
> ervey lteter by it slef but the wrod as a wlohe and the biran fguiers it
> out aynawy.
> 
> ... so please excuse us for every typo in the documentation, man pages or 
> code, btw fixes and patches are welcome.

**Comment by koeppea** [comment]
Maybe it's a old version you're referring to?
I can find it in the latest man pages:
```
$ grep mimt man/*
$
```
So closing this issue.
