### ISSUE TITLE
make:*** No targets specified and no makefile found. stop.

### ISSUE THREAD

**Issue by sharnaaysha** [Ettercap/ettercap#901]
I wanted to install the latest Ettercap on Kali linux . So I followed these steps 
```
1.apt-get install debhelper cmake bison flex libgtk2.0-dev libltdl3-dev libncurses-dev libncurses5-dev libnet1-dev libpcap-dev libpcre3-dev libssl-dev ghostscript python-gtk2-dev libpcap0.8-dev
2.git clone https://github.com/Ettercap/ettercap.git
3.cd ettercap
4.mkdir build
5.cd build
6.cmake ../
7.make
8.make install
9.cd ../../
10.rm -rf ettercap/
```
but step no. 7 make not execute it says make:*** No targets specified and no makefile found. stop 
![ettercap](https://user-images.githubusercontent.com/40449982/43121970-773e1bc4-8f5a-11e8-807c-fa46c57974dc.PNG)
Here is the output

**Comment by koeppea** [comment]
You just need to read the output. 
libgtk+-3.0-dev (or so) seem to be missing.

**Comment by koeppea** [comment]
Closing since the package is also mentioned in the _README_ but not in your **apt-get** command:
```
$ grep -n libgtk README
83:apt-get install debhelper bison check cmake flex ghostscript libbsd-dev libcurl4-openssl-dev libgtk2.0-dev \
84: libltdl-dev libluajit-5.1-dev libncurses5-dev libnet1-dev libpcap-dev libpcre3-dev libssl-dev libgtk-3-dev
$
```
