### ISSUE TITLE
Bridge mode filtering not working (bug or not meant to be)

### ISSUE THREAD

**Issue by cabelito** [Ettercap/ettercap#902]
Hello there,
after I've read all the issues, including (Manipulate HTTP responses #627)
I've read that in this issue - guy is being in Bridge mode and trying to alter/filter/manipulate packets.
I am trying to do the same in bridge mode. I have machine with 2 unconfigured NICs as a bridge betwen victim and gateway 
(victim) 192.168.0.100 -------------- [ BRIDGE transparent no IP ] -------------- 192.168.0.1 (gateway)
I've created a filter - very basic and I am sure it is working - if there is any packet on port 80 , just msg(packet) and drop(); also made another one with changing IMG SRC .
When running in BRIDGE mode ran with
ettercap -Tq -F /tmp/filter.ef -i eth0 -B eth1 
I can see the MSG part from the filter, but the packets are not dropped, not injected, not replaced

I've made same configuration but without the bridge being in the middle
(victim) 192.168.0.100 ----------------[switch]------------- 192.168.0.1(gateway)
(ettercap) 192.168.0.55 ------------------+

running the same filters but with 
/usr/local/bin/ettercap -Tq -F /accounting/filter.ef -i eth0 -M ARP /192.168.0.100/ //

and it works. So I can imagine the packet injecting/altering/dropping is only possible when using -M (MITM) 
but in the man pages it is stated that -B BRIDGE mode is capable of dropping/manipulating packets
also in the post mentioned above it is also stated that this is possible ?
Am I doing something wrong ? Is it just not meant to be or ?

Using latest Ettercap 0.8.2 with debian and installed by apt-get

**Comment by koeppea** [comment]
Hi @cabelito 

I've set up a test environment.
However, I couldn't reproduce the issue. See the screenshot:
![filter-bridge-mode](https://user-images.githubusercontent.com/4201853/43417888-993b3b6c-943c-11e8-992a-5873e1742b42.png)
The _testfilter.ecf_ has the following content:
```
if (tcp.src == 80 || tcp.dst == 80) {
	msg("HTTP Packet dropped\n");
	drop();
}

```
Maybe you try to uninstall the Ettercap package provided by your distribution and get the latest version from github compiled?
Free free to reopen if you till experience the same using the latest code.
