### ISSUE TITLE
Logging option -m not working (Invalid log file)

### ISSUE THREAD

**Issue by cabelito** [Ettercap/ettercap#903]
Hello,
I am using ettercap and I am currently using -L option for logging 
`/usr/local/bin/ettercap -D -u -z -i br0 -L /tmp/logfile `
which creates 2 files /tmp/logfile.eci (info) and /tmp/logfile.ecp (messages).
If start ettercap with -l option instead of -L it works just fine by logging only info messages to file .eci, however if I start ettercap with -m option 
`/usr/local/bin/ettercap -Tq -u -z -i br0 -m /tmp/testing.ecp` 
or
`/usr/local/bin/ettercap -D -u -z -i br0 -m /tmp/testing.ecp`
(to log only messages) ettercap starts with no error, but when trying to read /tmp/testing.ecp with etterlog here is the output:

`etterlog /tmp/testing.ecp `
`etterlog 0.8.2 copyright 2001-2015 Ettercap Development Team`
`Invalid log file`

**Comment by sgeto** [comment]
Unlike -L, the -m option creates a clear text log file. It's like redirecting stdout/stderr to a file.
It's not meant to be opened by etterlog. Try opening `/tmp/testing.ecp` with a text editor instead.
