### ISSUE TITLE
Error using regex in filter

### ISSUE THREAD

**Issue by TotoMerumeni** [Ettercap/ettercap#909]
Hello, I'm using the current script for filter the incoming packet and change the content of web pages' body tag with the "replaced" text. But the "pcre_refex" function seems not to work with regex (like the normal " replace" one).
Like specified in the MAN of etterfilter I've installed libpcre3 and libpcre3-dev (apt-get install libpcre3 libpcre3-dev) but I'm it's always not working.

Ettercap version: 0.8.2

Code:
if (ip.proto == TCP && tcp.dst == 80) {
   if (search(DATA.data, "Accept-Encoding")) {
      replace("Accept-Encoding", "Accept-Rubbish!"); 
      msg("zapped Accept-Encoding!\n");
   }
}

if (ip.proto == TCP && tcp.dst == 80) {	
  pcre_regex(DATA.data, "<BODY((.|[\n\r])*)<\/BODY>", "replaced");
  pcre_regex(DATA.data, "<body((.|[\n\r])*)<\/body>", "replaced");
}

**Comment by sgeto** [comment]
Try:

`pcre_regex(DATA.data, "<body((.*|[\r\n]))</body>", "replaced");`

**Comment by TotoMerumeni** [comment]
@sgeto No your regex is wrong. I've tried mine on online simulator and they work well. I think it's a function problem that is not working.

**Comment by koeppea** [comment]
@TotoMerumeni your second condition applies for packets towards a webserver. HTML content is normally only coming from the webserver.
so your condition must compare port 80 on the source port (`tcp.src`) instead of the destination port.

Accept-Encoding in contrast occurs in the HTTP request, hence the replace function matches.

**Comment by koeppea** [comment]
I think your lack of reaction means the issue is solved.
If not, feel free to reopen.
