### ISSUE TITLE
execinject shell command problem with null character 

### ISSUE THREAD

**Issue by vtech451** [Ettercap/ettercap#917]
I wrote bellow shell command but problem is it ignores null character. I want to use this shell output with execinject().  Can you please help me out.
```bash
#!/bin/bash
file="/media/sf_kali/abc.log"
if [ ! -f "$file" ]
then
    echo "$0: File '${file}' log file not found."
fi
value=$(</$file)

echo "$value"
```

**Comment by koeppea** [comment]
@vtech451 any update? Or have you got the issue solved otherwise?

**Comment by koeppea** [comment]
Closing as no response. Feel free to reopen if required.
