### ISSUE TITLE
I can't find the etter.dns file on MacOSX

### ISSUE THREAD

**Issue by iOSPrincekin** [Ettercap/ettercap#918]
Hello:
       I use the dns_snoof plugin in ettercap on macosx, but I can't find the etter.dns file on macosx, I don't know why , can you give me some tips? thanks a lot!

**Comment by koeppea** [comment]
Should be in /etc/ettercap/

**Comment by sgeto** [comment]
Try /usr/etc/ettercap and /usr/local/etc/ettercap as well.

**Comment by iOSPrincekin** [comment]
I find it in  /usr/local/etc/ettercap, thanks a lot!

**Comment by koeppea** [comment]
Closing so.
