### ISSUE TITLE
how instead all the host to the target host when use dns_snoof? 

### ISSUE THREAD

**Issue by iOSPrincekin** [Ettercap/ettercap#919]
Hi:
    I use the dns_snoof plugin in the ettercap, so I add some ruler to the etter.dns in the /usr/local/etc/ettercap/ directory  : 

*.*.*            A 192.168.11.103
*.*.*             PTR 192.168.11.103

and when I go to the www.baidu.com in iphone browser, it works fine for me, but the other URL not work,   I don't know the syntax about    ‘*.*.*            A 192.168.11.103’ , so if I want to instead all the URL which visited in my iphone, which ruler should I add in  etter.dns,is there any document or knowledge about the syntax which about    ‘*.*.*            A 192.168.11.103’, I want to study it, so I can wirte suitable syntax.  thanks a lot!

**Comment by koeppea** [comment]
What is '..*'?
If you want to match all queries just use * not ..*.
Also don't forget about AAAA records.

**Comment by koeppea** [comment]
Any answer? if yes feel free to reopen. Otherwise, I consider this to be resolved.
