### ISSUE TITLE
Problem when running  arp:remote

### ISSUE THREAD

**Issue by hsayedsayed** [Ettercap/ettercap#925]
When you run it   "On Bridge"

echo 1 > / proc / sys / net / ipv4 / ip_forword

ettercap -Tq -M arp: remote -i eth0 /192.168.1.1// /192.168.1.13

Knowing that I am changing the settings of /etc/etter/etter.conf

The problem here is that there is no Internet in the 192.168.1.13 device after the attack was executed

**Comment by koeppea** [comment]
What do you mean with "On Bridge"?
Because Bridge-Mode required the `-B` parameter.

**Comment by hsayedsayed** [comment]
eth0

**Comment by hsayedsayed** [comment]
Even if it working at the speed of the Internet is very slow in the target

It also affects on the clients in the same network in terms of slow internet and occasionally stopping

**Comment by koeppea** [comment]
When you run in bridge mode, ARP poisoning is not required/ working because you’d be in the middle already.

However the bad performance issue in bridge mode has already been identified and is fixed in latest master (Git).

If the issue still persists we need more debugging info to go forward.

**Comment by hsayedsayed** [comment]
Sorry for more questions .. and Thank you very much for your response
I may be wrong in the commands
So, What commands are used for using ettercap on lan for sniffing

**Comment by koeppea** [comment]
It depends on your individual situation.
Cannot be answered generically.

**Comment by hsayedsayed** [comment]
When you use the -S option, it works correctly, but the problem here when i used sslstrip does not change https to http

> echo 1 > / proc / sys / net / ipv4 / ip_forword

> ettercap -Tq -M arp: remote -i eth0 -S /192.168.1.1// /192.168.1.13//

works correctly.

when use with it sslstrip
> iptables -t nat -A PREROUTING -P tcp --destination-port 80 -j REDIRECT --to-port 10000
> sslstrip

where is the problem ?

**Comment by koeppea** [comment]
Ah now we're getting closer.
**Ettercap** and **sslstrip** is not supported.
Ettercap has its own ssltrip plugin.
To get that activated, you need to set the `ec_uid` and `ec_gid` to **0** and uncomment the `iptables` commands at the end of the _etter.conf_.
Then you start Ettercap with the `-Psslstrip` parameter to load the plugin. It automatically installs the redirect rule.

**Comment by hsayedsayed** [comment]
Thank you very much for your efforts
