### ISSUE TITLE
choose  Hosts->Scan for hosts ,press the Enter key, the program crashes

### ISSUE THREAD

**Issue by miyarChen** [Ettercap/ettercap#928]
In the MAC OS, choose the menu：Hosts-> Scan for hosts    C-s, press the Enter key，the program exits, and report an error
![image](https://user-images.githubusercontent.com/22127999/53619281-bc2e7e00-3c29-11e9-966a-03b8a40f560f.png)

![image](https://user-images.githubusercontent.com/22127999/53619220-7c679680-3c29-11e9-967e-c6705f525848.png)

**Comment by koeppea** [comment]
Have you seen our macosx Wiki page? It's describing how to build Ettercap from latest GitHub source on MacOS. Also with setting **-DCMAKE_BUILD_TYPE=Debug**.

**Comment by koeppea** [comment]
@miyarChen could you please respond to my last comment.

**Comment by miyarChen** [comment]
@koeppea thank you for reminding me. According to the wiki, this problem has been solved.

**Comment by koeppea** [comment]
So does that mean, you've managed compiling ettercap from source
following the wiki and now ettercap isn't crashing anymore?

**Comment by miyarChen** [comment]
Ettercap is  no problem currently

**Comment by koeppea** [comment]
Closing then.
