### ISSUE TITLE
DOS plugin

### ISSUE THREAD

**Issue by Mfrashidi** [Ettercap/ettercap#932]
Hi there
I had used DNS plugin to test something and I set my phone ip to see how it work but after I finished my work I can't access the internet through my mobile phone. I changed my DHCP ip to a static one and it works but I want to know how I should access the internet with that ip?
thanks

**Comment by koeppea** [comment]
Sorry I don't understand. Could you please provide more details what you've done and what you're trying to achieve?

**Comment by LocutusOfBorg** [comment]
Usually this works as soon as you stop poisoning the network with the fake DNS. Just restore the previous working DNS to go back on the internet.
