### ISSUE TITLE
Ettercap not finding gateway IP address (0.8.2)

### ISSUE THREAD

**Issue by hailnolly** [Ettercap/ettercap#933]
I'm running Ettercap 0.8.2 and the application can only find two hosts on my small network I'm building for a lab:

- DNS-EHP-001 (192.168.1.1)
- WEB-EHP-001 (192.168.1.2)

It's not finding/displaying in the "host list":

- W10-EHP-001 (192.168.1.3)
- Default gateway (192.168.1.254)

All services are switched on and can be reached using nslookup.

Please can anybody help?

**Comment by koeppea** [comment]
Try to tweak the arp_storm_delay in etter.conf to make the ARP Scan less aggressive.

**Comment by koeppea** [comment]
Closing. Feel free to reopen if this didn't help.
