### ISSUE TITLE
Payload postion

### ISSUE THREAD

**Issue by luismartinsez** [Ettercap/ettercap#952]
Hi Alexander,

Hope all well with you

Could you help me to find the position of the following please?

![image](https://user-images.githubusercontent.com/48541300/60766065-88330000-a0d6-11e9-8f4e-baa9c449e707.png)

I want to change the payload Bit 0 to 1, Bit 1 to 1, Bit 2 to 1 etc.

Tried passing the attached filter, but it doesn't change anything.

[jul7.zip](https://github.com/Ettercap/ettercap/files/3365427/jul7.zip)

Can you please look into this? Uploaded pcap & filter

Thanks

**Comment by koeppea** [comment]
The following filter works for me (I've omitted the IP address condition as I have different IPs in my lab):
```
  if (tcp.src == 502) { 
    msg("Coming from Server Port 502\n");
    if (DATA.data + 2 == "\x00\x00") { 
      msg("Protocol Identifier == 0\n");
      if (DATA.data + 7 == "\x02" || DATA.data + 7 == "\x82") {
        msg("Function Code: Read Discrete Inputs\n");
        DATA.data + 9 = 7;
      }
    }
  }
```
Testing gives me the following result (left before the filter applied - right after the filter applied):
![image](https://user-images.githubusercontent.com/4201853/60928651-80c64f00-a2ae-11e9-91de-0e3f6eed4a70.png)

But please note that **etterfilter** does not support a binary operator `|=` to preserve the other bits that may be set.
This way you set the first (least significant) three bits and reset the rest to 0!
Note that 7 equals to binary 00000111. Offsets only act on byte (not bit) -level.
