### ISSUE TITLE
make error on mac

### ISSUE THREAD

**Issue by KnightSec-Official** [Ettercap/ettercap#957]
i got an error while im trying to 'make'... im in the build folder... i did everything right... ettercape worked for me some days ago... idk why is giving me this error.....

```
[  0%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o
In file included from /var/root/ettercap/src/ec_interfaces.c:31:
In file included from /var/root/ettercap/src/interfaces/gtk3/ec_gtk3.h:4:
In file included from /usr/local/include/gtk-3.0/gtk/gtk.h:30:
In file included from /usr/local/include/gtk-3.0/gdk/gdk.h:32:
In file included from /usr/local/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30:
/usr/local/include/gtk-3.0/gdk/gdktypes.h:35:10: fatal error: 'pango/pango.h'
      file not found
#include <pango/pango.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o] Error 1
make[1]: *** [src/interfaces/CMakeFiles/ec_interfaces.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by KnightSec-Official** [comment]
i git cloned the ettercap into /var/root... im on mac os high sierra... ettercap worked for me some time ago... idk what happened

**Comment by sgeto** [comment]
> i git cloned the ettercap into /var/root

Shouldn't matter

>  im on mac os high sierra

Sorry to hear that.

> idk what happened

You're missing the Pango library. You probably need the GTK3 development files if you never build ettercap before, Try [homebrew](https://formulae.brew.sh/formula/gtk+3).

**Comment by zezekaka** [comment]
My problem is the same, but with hb.h, idk what dependency is that. Were is the error log:

`[  0%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o
In file included from /Users/josemartins/explot_test/ettercap/src/ec_interfaces.c:31:
In file included from /Users/josemartins/explot_test/ettercap/src/interfaces/gtk3/ec_gtk3.h:4:
In file included from /usr/local/include/gtk-3.0/gtk/gtk.h:30:
In file included from /usr/local/include/gtk-3.0/gdk/gdk.h:32:
In file included from /usr/local/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30:
In file included from /usr/local/include/gtk-3.0/gdk/gdktypes.h:35:
In file included from /usr/local/include/pango-1.0/pango/pango.h:25:
In file included from /usr/local/include/pango-1.0/pango/pango-attributes.h:25:
In file included from /usr/local/include/pango-1.0/pango/pango-font.h:25:
/usr/local/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: 'hb.h'
      file not found
#include <hb.h>
         ^~~~~~
1 error generated.
make[2]: *** [src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o] Error 1
make[1]: *** [src/interfaces/CMakeFiles/ec_interfaces.dir/all] Error 2
make: *** [all] Error 2`

_PS: Idk if this is the right way to post this issue, please forgive me_

**Comment by koeppea** [comment]
It's all about unresolved dependencies.
If you use homebrew try `brew install harfbuzz`.
Then try if the build error disappears. Or others come up.
Follow up until all dependencies are met and built completes.

**Comment by koeppea** [comment]
@KnightSec-Official Can you please check if #969 fixes the issue for you?

**Comment by Kindhearted57** [comment]
> It's all about unresolved dependencies.
> If you use homebrew try `brew install harfbuzz`.
> Then try if the build error disappears. Or others come up.
> Follow up until all dependencies are met and built completes.
Still isn't working.......

**Comment by Kindhearted57** [comment]
> It's all about unresolved dependencies.
> If you use homebrew try `brew install harfbuzz`.
> Then try if the build error disappears. Or others come up.
> Follow up until all dependencies are met and built completes.

Still isn't working...Got the same error as before.

**Comment by koeppea** [comment]
I’ve created pull request #969 and was able to fix OS X builds on Travis.

Can you try out if this pull request fixes it also for you?
