### ISSUE TITLE
Ettercap CLI

### ISSUE THREAD

**Issue by luismartinsez** [Ettercap/ettercap#958]
I am trying run the following the to load a filter in CLI mode, but it does't do anything.

sudo ettercap -T -q -i enp0s25 -F Modbus2.ef -M ARP:remote /192.168.0.65// /192.168.0.66// /192.168.0.67//

However:
Filter Modbus2.ef works on Graphic mode.
It also works when I provide a single target : - sudo ettercap -T -q -i enp0s25 -F Modbus2.ef -M ARP:remote /192.168.0.65//

Am I doing something wrong? How do we provide multiple targets in CLI mode?

**Comment by koeppea** [comment]
in your 1st command, you've provided 3 TARGET tokens. But the parameters are 
`ettercap [options] TARGET1 TARGET2`
**TARGET** has the format `[MAC]/[IPv4]/[IPv6]`. IP addresses can be specified in ranges or enumerations. You'd consult the _ettercap_ manpage, which expains the possibilities of the **TARGET** specification.

Getting the TARGET specification right should solve the issue?

**Comment by luismartinsez** [comment]
That worked, thank you :-)
