### ISSUE TITLE
ettercap does not detect harfbuzz include path

### ISSUE THREAD

**Issue by jelly** [Ettercap/ettercap#966]
Pango now depends on /usr/include/harfbuzz/hb.h which breaks the build of ettercap on Arch. Some changes in the cmake file are required.

```
Scanning dependencies of target ec_interfaces
[  0%] Building C object src/interfaces/CMakeFiles/ec_interfaces.dir/__/ec_interfaces.c.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/gtk-3.0/gdk/gdktypes.h:35,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /build/ettercap/src/ettercap-0.8.3-gtk/src/interfaces/gtk3/ec_gtk3.h:4,
                 from /build/ettercap/src/ettercap-0.8.3-gtk/src/ec_interfaces.c:31:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
```

Maybe this can be seen as an inspiration.

https://cgit.kde.org/kde-gtk-config.git/commit/cmake/modules/FindGTK3.cmake?id=cf8db4ebe5ef5e54517604cd9330535983e4dff0

**Comment by koeppea** [comment]
Thanks. This will definitely help.

**Comment by koeppea** [comment]
Same issue as in #957. Travis build is currently also failing due to this changed dependency. Pull request #969 is supposed to fix that but not yet finished.

**Comment by koeppea** [comment]
@jelly can you please try if #969 fixes that for you?

**Comment by koeppea** [comment]
@jelly any update? Have you had a chance to try the proposed fix for the harfbuzz issue?

**Comment by koeppea** [comment]
PR #969 should solve the build issue. Closing.
