### ISSUE TITLE
dns_spoof error - etter.conf redir_command not working in Mojave

### ISSUE THREAD

**Issue by prykon** [Ettercap/ettercap#970]
Hi there! I'm currently using ettercap v.0.8.3 and none of the 3 scripts for macOS Mojave

- ipfw has been deprecated
- BSD PF resolves in segmentation fault on sniffing
- BSD PF for IPv6 doesn't resolve in segmentation fault but even though it "catches the dns" and says it spoofs it, it doesn't and microsoft.com (for instance) loads correctly.

*note:* 
ec_uid = 0
ec_gid = 0

Any insight on what the proper script for mojave might be?
Thanks!

**Comment by koeppea** [comment]
Hi,

please read [our Wiki page](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) how to support troubleshooting issues with Ettercap. Especially the note about the _core_ file generated during a segmentation fault.

**Comment by koeppea** [comment]
@prykon any update?

**Comment by prykon** [comment]
Wasn't able to get the core file generated. I switched over to bettercap. This issue might work differently now that OSX updated from Mojave to Catalina.

**Comment by koeppea** [comment]
Closing then.
