### ISSUE TITLE
"Birthday" easter egg breaks scripts

### ISSUE THREAD

**Issue by Zezombye** [Ettercap/ettercap#975]
I am running this command in my script: `ettercap -T -s 's(300)olqq'` (from the man page)

Due to the need to press the enter key, I have to send the enter key via stdin in my script, else ettercap just hangs forever.

This obviously is easily worked around but it could've been a problem if I wasn't debugging the script this very day.

**Comment by koeppea** [comment]
What is you proposal? You want to hand in a pull-request as a suggestion?

**Comment by Zezombye** [comment]
A solution could be to remove the need to press the enter key.
