### ISSUE TITLE
Possible to redirect to sub pages of target IP?

### ISSUE THREAD

**Issue by maximus1127** [Ettercap/ettercap#978]
So I have successfully redirected a user to the ip address of a different site. is there a way to redirect to a sub page of that spoofed ip? For example: right now, I can redirect someone to github.com, but can I redirect them to github.com/ettercap/ettercap? If so, how can I do that?

**Comment by koeppea** [comment]
Either by the spoofed webserver configuration itself (Apache Rewrite) or with a Ettercap filter. I think with the first approach, there are less traps on the way.
Closing though since it's not a issue of Ettercap.
