### ISSUE TITLE
WIll not find any scanned hosts

### ISSUE THREAD

**Issue by masonBackus** [Ettercap/ettercap#980]
new to Ettercap gui. Edited the config file, changed the ec_uid = 0 and left ec_gid = 65534.
uncommented out for Linux users the 2 lines of code for ip tables on redirect and saved using nano.
found the /proc/sys/net/ipv6/conf/eth0/use_tempaddr file and changed it from 2 to 0 as requested
by ettercap gui. saved that file using nano. did not reboot. went back into Ettercap and it still did not detect any hosts on my eth0 interface when after scanning hosts -- there's 7 devices on eth0 and none were found. What am I doing incorrectly? Also when selecting wlan0 interface, Ettercap closes.

**Comment by koeppea** [comment]
You're using Kali?
Please read our [Wiki article](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information)

**Comment by koeppea** [comment]
I'm pretty sure this has been fixed with #977. So in our Wiki you find how to compile Ettercap from latest code base on Github. Closing.

**Comment by masonBackus** [comment]
Yes, using kali, read you #977 not sure what a PR is, and now I will need to learn how to compile

**Comment by koeppea** [comment]
This pull request is meanwhile merged in master. So you just need to compile the latest master from Github.
