### ISSUE TITLE
FATAL: ARP poisoning needs a non empty hosts list

### ISSUE THREAD

**Issue by thibaultserti** [Ettercap/ettercap#983]
I'm running Manjaro Linux and I currently have this error when trying the command 
`sudo ettercap -T -q -i wlp5s0 -M arp:remote /192.168.43.1/ /192.168.1.100/ -w result.pcap`

I searched a bit and found that ettercap can send this error when the device is enabled but when there is no connection found. However there is a connection, (I do have an IP and can ping other computers).

Here are the logs
```Listening on:
wlp5s0 -> A0:51:0B:AD:E9:4F
          192.168.43.33/255.255.255.0
          fe80::f0d8:5b0d:93b5:5eca/64

SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to EUID 65534 EGID 65534...

mdns_spoof: etter.mdns:52 Invalid IPv4 or IPv6 address
mdns_spoof: etter.mdns:54 Invalid IPv4 or IPv6 address
mdns_spoof: etter.mdns:61 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:71 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:78 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:81 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:90 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:99 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:112 Invalid IPv4 or IPv6 address
  34 plugins
  42 protocol dissectors
  57 ports monitored
24609 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services

Scanning for merged targets (2 hosts)...

* |==================================================>| 100.00 %

0 hosts added to the hosts list...

FATAL: ARP poisoning needs a non empty hosts list.
```

**Comment by koeppea** [comment]
Hi,
this is a known issue with _libpcap_ version 1.9.1.
This is fixed in the latest code base on GitHub.
Check out our [Wiki pages](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) where you find information how to compile and test the latest Code from GitHub.

**Comment by Antonowan225** [comment]
┌──(antonowan225㉿Antonow)-[~]
└─$ sudo ettercap -T -S -i wlan0 -M arp:remote /192.168.178.1// /192.168.178.34//                                                                                                                                                    255 ⨯

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

Listening on:
 wlan0 -> 6E:E5:FB:60:3D:9D


Privileges dropped to EUID 65534 EGID 65534...

  34 plugins
  42 protocol dissectors
  57 ports monitored
28230 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
Lua: no scripts were specified, not starting up!

Scanning for merged targets (2 hosts)...

* |==================================================>| 100.00 %

0 hosts added to the hosts list...

FATAL: ARP poisoning needs a non empty hosts list.

The Ip Adresses are correct. I run Kali on a Virtual Machine (VirtualBox by Oracle).

**Comment by harmis03** [comment]
yout find any solution of this problem i am also facing this same issues right now ?

**Comment by koeppea** [comment]
Which version are you running?
 
This issue has been fixed quite since time ago. I've also made a few videos on YouTube.
