### ISSUE TITLE
i can't not use dns_spoof.

### ISSUE THREAD

**Issue by caiyaonan** [Ettercap/ettercap#984]
`SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 72 byte packet (86dd:3a) destined to ff02::1:ff00:1 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 160 byte packet (86dd:11) destined to ff02::fb was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 76 byte packet (86dd:3a) destined to ff02::16 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 198 byte packet (86dd:11) destined to ff02::fb was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)
SEND L3 ERROR: 76 byte packet (86dd:3a) destined to ff02::16 was not forwarded (libnet_write_raw_ipv6(): -1 bytes written (No route to host)
)`
System : MAC OS Catalina
Start Command ：sudo /usr/local/Cellar/ettercap/0.8.3_2/bin/ettercap -Tq -i en0 -P dns_spoof -M arp /192.168.0.1//192.168.0.2-210/

I set /usr/local/Cellar/ettercap/0.8.3_2/.bottle/etc/ettercap/etter.dns    * A 192.168.0.7
my compute ip is :192.168.0.7, Apache Service is running, 192.168.0.7 can normal open website,i try it.
buy i use dns_spoof plugins redirect , any host Not affected。

**Comment by koeppea** [comment]
1. The error messages are only related to IPv6 - not IPv4 so can be ignored in your case
  2. To spoof DNS for the victims, you must be sure that they're using IPv4 to reach their DNS Server when you only do IPv4 MITM
  3. I think you're editing the wrong `etter.dns` file. What gives `find /usr/local -name etter.dns 2> /dev/null`?

**Comment by caiyaonan** [comment]
> 1. The error messages are only related to IPv6 - not IPv4 so can be ignored in your case
> 2. To spoof DNS for the victims, you must be sure that they're using IPv4 to reach their DNS Server when you only do IPv4 MITM
> 3. I think you're editing the wrong `etter.dns` file. What gives `find /usr/local -name etter.dns 2> /dev/null`?

Thanks you reply

**Comment by koeppea** [comment]
It's hard to give any more advises w/o getting more insights.
To provide these insights, please read through our [Wiki page](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) how to support us troubleshooting the problem you're facing.

**Comment by caiyaonan** [comment]
Thanks

**Comment by koeppea** [comment]
@caiyaonan any updates?

**Comment by koeppea** [comment]
Closing idle issue.
