### ISSUE TITLE
Ettercap crashes with segmentation error

### ISSUE THREAD

**Issue by hugohab** [Ettercap/ettercap#986]
Could please help me with the problem.
When I press and hold ctrl+s(scan for hosts), Ettercap crashes with segmentation fault. This is what it says:
"Ooops ! This shouldn't happen...
Segmentation Fault...

Please recompile in debug mode, reproduce the bug and send a bugreport

 Have a nice day!"
Can someone please take me through the steps to make it work?

**Comment by koeppea** [comment]
Hi, I've written a dedicated [Wiki page](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) covering this topic.

**Comment by nabielmada** [comment]
in my problem ..
says :

set_redir_commands(): cannot setup the redirect for IPv6, did you uncomment the redir6_command_on command on your etter.conf file?

Ooops ! This shouldn't happen...
Segmentation Fault...                                                           
                                                                                
Please recompile in debug mode, reproduce the bug and send a bugreport

wht should i do ? :(

**Comment by koeppea** [comment]
Can we close this issue now?

**Comment by koeppea** [comment]
Closing the issue now as no more response. Feel free to reopen if you still experience the issue and have collected the requested debug information.
