### ISSUE TITLE
Ettercap crashes 

### ISSUE THREAD

**Issue by iwahak** [Ettercap/ettercap#995]
Hi, I need help....I've been trying for days to make it works. I did capture some packet and I got the debug file. Could you take a look at it?
[ettercap-0.8.3_debug.log](https://github.com/Ettercap/ettercap/files/4062992/ettercap-0.8.3_debug.log)
[01test.pcap.gz](https://github.com/Ettercap/ettercap/files/4063011/01test.pcap.gz)

 Thank you

**Comment by koeppea** [comment]
When it crashed with a segmentation fault, a file named _core_ should be in the directory where it had been executed. Please provide this file in addition.

**Comment by iwahak** [comment]
I haven't found the file named '' core '' could you be more specific about that file. I did executing it in root directory

**Comment by koeppea** [comment]
The file is just named "core" or "core.N" if multiple core files exist. 
It is only the case when ettercap is built in Debug Mode which it should 
be as it also produces the debug log file.

Did it crash with a Segmentation Fault?

**Comment by iwahak** [comment]
I did compile in debug mode and didn't crash this time but I got those to warning:
"Cannot change tcp-segmentation-offload"
"Cannot change large-receive-offload

I think, with your help, I'm getting close to a solution.Unfortunately  I haven't found any core files, probably I delete them... Anyways I uploaded some info that may be usefull

[packets.pcap.gz](https://github.com/Ettercap/ettercap/files/4074920/packets.pcap.gz)
[ettercap-0.8.3_debug.log](https://github.com/Ettercap/ettercap/files/4074921/ettercap-0.8.3_debug.log)

**Comment by iwahak** [comment]
> Hi, I need help....I've been trying for days to make it works. I did capture some packet and I got the debug file. Could you take a look at it?
> [ettercap-0.8.3_debug.log](https://github.com/Ettercap/ettercap/files/4062992/ettercap-0.8.3_debug.log)
> [01test.pcap.gz](https://github.com/Ettercap/ettercap/files/4063011/01test.pcap.gz)
> 
>II did purge ettercap and retry without debug mode and :
ettercap -G

ettercap 0.8.3 copyright 2001-2019 Ettercap Development Team


(ettercap:108352): Gtk-WARNING **: 23:56:32.155: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators

(ettercap:108352): Gtk-WARNING **: 23:57:23.367: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators

**Comment by koeppea** [comment]
> "Cannot change tcp-segmentation-offload"
> "Cannot change large-receive-offload

You need to have **ethtool** installed. Then these warnings should go away.
However normally it's not of a big deal.

The Gtk-Warnings are warnings. However it would be interessting what you did or click when the appeared.

Now evaluating the newly providided logfile and packet capture.....

**Comment by iwahak** [comment]
Thanks for your help, now everything is working good!
